### ISSUE TITLE
Keyboard events do not contain valid keyCode or charCode

### ISSUE THREAD

**Issue by beverlycodes** [teampoltergeist/poltergeist#131]
Webkit has an annoying quirk in that when you create a UI or Keyboard event, the keyCode, charCode, and which properties (and maybe others) are set read-only.  If you assign to them, the assignment silently fails.  The end result is that any keyup, keydown, and keypress events fired by Poltergeist have 0 and '' for keyCode and charCode respectively.

The keypressed event in agent.coffee can be fixed simply by passing "Events" to document.createEvent in place of "UIEvents".

The keyup, keydown events can be fixed by passing "HTMLEvents" to document.createEvent in place of "UIEvents".

This is how capybara-webkit resolved the issue.

Those changes will allow Poltergeist to send keyCode, charCode, and which in events.  HOWEVER, I'm not sure what other bugs might be introduced by NOT using UIEvents.  I made those changes and ran a couple of my larger test suites.  Everything worked okay.  I don't know if that would hold true for everyone.

I can submit a pull request if these changes seem sound, but otherwise I'm just going to leave the suggestion here and let you play around with this information if and when you want to tackle it.  The good news is, making the changes is quick.  I'm just not familiar enough with Poltergeist yet to know how to sufficiently test that these changes wouldn't introduce unwanted behavior elsewhere.

**Comment by spreuss** [comment]
This issue is still present. Above commit was reverted by commit [c7ba561](https://github.com/teampoltergeist/poltergeist/commit/70304cc7f645dc8471a89f2651f1ef17bd0372bd) (Revert "Use native keyboard events to fill inputs") and thereby reintroduced "UIEvent" instead of "HTMLEvent" and "Event".
Could this be fixed?
