### ISSUE TITLE
Clicking a rotated element fails

### ISSUE THREAD

**Issue by jonleighton** [teampoltergeist/poltergeist#140]
See https://github.com/jonleighton/poltergeist/pull/138

**Comment by twalpole** [comment]
PhantomJS doesn't support CSS 3D. This is basically impossible to support until they do, since without support for CSS 3D the .back element is actually in front of the .front element since it comes after it in document order

**Comment by twalpole** [comment]
Closing this because there's nothing poltergeist can do about it -- If phantomjs adds support for CSS 3D transforms then this should just work
