### ISSUE TITLE
Capybara::Poltergeist::ObsoleteNode error

### ISSUE THREAD

**Issue by andyw8** [teampoltergeist/poltergeist#146]
I have a page which contains a list of text divs, each of which have an Add button that appears when you hover over it.

My code for clicking the link is like this:

  page.find('li .foo', :text => name).click_link('Add')

With v0.7.0, I was getting an error that the link can't be clicked because it wasn't visible.

I saw the note in the README about the changed behaviour in v0.8.0. That doesn't seem have been release yet (see #145), so I pointed my Gemfile to Github to get the latest version. However, my test now fails with:

  Capybara::Poltergeist::ObsoleteNode

**Comment by thiagogsr** [comment]
:+1: :+1: :+1: thanks

**Comment by ricardoemerson** [comment]
I had a problem to click on a button that only appear when the mouse was positioned on a picture (photo) and after much research got this:

    find('#follow', visible: false).trigger(:click)

In my case, the button was a link and only this way i can make my tests pass.

**Comment by twalpole** [comment]
@ricardoemerson Clicking on non-visible objects should be a solution of last resort so suggesting it on issues closed 3 years ago isn't really helpful
