### ISSUE TITLE
Be able to manipulate confirm boxes.

### ISSUE THREAD

**Issue by jcarres-mdsol** [teampoltergeist/poltergeist#153]
I know Poltergeist auto-accept confirmation boxes but I need to check for the text of the confirmation dialog.
Then /^I should see a confirmation box with the message "([^"]*)"$/ do |message|
    page.driver.browser.switch_to.alert.text.should include( message)
end

It uses the internal API of selenium to get the text. 
I would like to be able to check for this text somehow (maybe not the same API) in poltergeist also.

**Comment by twalpole** [comment]
modals are now supported
