### ISSUE TITLE
undefined method `manage' for #<Capybara::Poltergeist::Browser:0x007fdc58d682d8>

### ISSUE THREAD

**Issue by pivotal-medici** [teampoltergeist/poltergeist#165]
We're getting the above error every time we try to run tests with poltergeist. There's nothing special in the test. It's just a simple visit the page and check for have_content.

We are using
- OS X 10.7.4
- Phantom JS 1.7.0 installed via homebrew
- ruby 1.9.3
- capybara 1.1.2
- rspec-rails 2.11.1

**Comment by marlonmantilla** [comment]
Just in case someones found with this error, I manage to resolve this adding this in `spec_helper.rb` 

    config.before(:each, js: true) do
      Capybara.page.driver.resize("1300","1240")
    end

**Comment by thejourneydude** [comment]
@marlonmantilla Unfortunately, that does not work for me. I'm receiving this error.

    NoMethodError:
            undefined method `resize' for #<Capybara::RackTest::Driver:0x000001095772e0>

**Comment by twalpole** [comment]
@thejourneydude Notice the "Capybara::RackTest::Driver" in your error message - that means your using it in a test that isn't actually using poltergeist.

**Comment by thejourneydude** [comment]
Interesting. I followed the instructions. I'll investigate it further.
