### ISSUE TITLE
Another timeout issue

### ISSUE THREAD

**Issue by tfwright** [teampoltergeist/poltergeist#169]
I'm currently getting this error fairly frequently:

```
An error occurred in an after hook
  Capybara::Poltergeist::TimeoutError: Timed out waiting for response to {"name":"reset","args":[]}
  occurred at /Users/tfwright/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/poltergeist-943398fdd23a/lib/capybara/poltergeist/web_socket_server.rb:147:in `rescue in send'
```

It appeared after updating to 0.7 PhantomJS 1.7, briefly disappeared after a restart but came back. I know there have been other timeout issues reported but I haven't seen this particular error (with reset).   I'm now using 943398fdd23a5c187df39a520265350a6168bbeb as advised in the other thread.  PhantomJS works fine in the console and there don't appear to be any hung processes.  On OS X 10.8.2

**Comment by dangan249** [comment]
I am seeing this error constantly while running my test with parallel_tests.  My phantomjs version is 1.9.7 with mac os mavericks + ruby 2.2.1p85  + and Rails 4.1.9.

Other members in my team don't have the problem though, so it's probably related to my local environment.  Any idea in what may have caused this??

```code
  An error occurred in an after hook
    Capybara::Poltergeist::TimeoutError: Timed out waiting for response to {"name":"reset","args":[]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker.
    occurred at /Users/andang/.rvm/gems/ruby-2.2.1@dandelion/gems/poltergeist-1.5.1/lib/capybara/poltergeist/web_socket_server.rb:87:in `rescue in send'

!!!!! EXCEPTION: Timed out waiting for response to {"name":"visit","args":["http://localhost:62668/app/products/='foo:'bar'"]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker..  Retrying once !
```

**Comment by BandanaPandey** [comment]
As you have mentioned, your phantomjs version is 1.9.7, this may be causing problem, also your poltergeist version need to be updated. According to me,  you should update your Poltergeist gem, and also update PhantomJS to version >= 2.1.0.
use bundle update poltergeist.
Hope this works for you.
