### ISSUE TITLE
DeadClient occurring randomly on linux only

### ISSUE THREAD

**Issue by tgaff** [teampoltergeist/poltergeist#200]
This may or may not be a poltergeist issue.  

I'm seeing a lot of: 
The PhantomJS client died while processing {"name":"click","args":[38,3]} 
Capybara::Poltergeist::DeadClient:

This occurs in various places throughout our tests but usually when clicking the login button.  Occasionally it has also happened when doing a 'visit'.  

This only happens in linux, specifically CentOS6.2 which logs:
I do get saved core dump of pid 10666 (/usr/local/bin/phantomjs) to /var/spool/abrt/ccpp-201....
but then:
Corrupted or bad dump /var/spool/abrt/ccpp-201...., deleting

I've tried:
* phantomjs 1.7.0 binary 
* compiling the latest developmental build (phantomjs 1.8.0)
* after(:each) { Capybara.current_session.driver.reset! }
* disabling ttf fonts - based on this issue: https://github.com/jonleighton/poltergeist/issues/44 
       yes, that says OSX, but someone else there is reporting CentOS issues as well.

Any suggestions?

**Comment by constantm** [comment]
I'm still having this issue. I get random DeadClient errors when running tests on SemaphoreCI. It only happens with one of the tests, and it seems to be related to `visit current_path`, which is used to refresh the page.

**Comment by twalpole** [comment]
I'm closing this due to the age of the issue and lack of detailed followup -- If anyone is still experiencing it with the latest version provide detailed version info and logs in a new issue.
