### ISSUE TITLE
Problem with jQuery 'change' event after using select to change selected option.

### ISSUE THREAD

**Issue by thegreatape** [teampoltergeist/poltergeist#204]
When I use Poltergeist's `select` method to change the value of a select box, the event that is fired seems to have something wrong with its target property. With the html provided below in a route that's returned via a GET to '/', under Chrome 23.0, changing the value of the select fills in both the "from-target" and"globally" divs. However, under Capybara with the Poltergeist driver, only the "globally" target div is filled correctly- e.g. `$(evt.target).find(':selected').text()` is incorrectly returning an empty string. A failing test for this is below.

```html
<html>
  <head>
    <title>jquery :select test</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="text/javascript"></script>
    <script>$(function(){
        $('select').on('change', function(evt){
          $('.from-target').text( $(evt.target).find(':selected').text() );
          $('.globally').text( $(':selected').text() )
        });
      })</script>
  </head>
  <body>
    <label for="test-select">Test Select</label>
    <select name="test-select">
      <option value="1">A</option>
      <option value="2">B</option>
    </select>
    <div class="from-target"> </div>
    <div class="globally"> </div>
  </body>
</html>
```

```ruby
require 'test_helper'

class JquerySelectTest < ActionDispatch::IntegrationTest
  test ":selected should work" do
    Capybara.current_driver = :poltergeist

    visit '/'
    select "B", from: "test-select"
    assert_equal "B", page.find('.from-target').text
  end
end
```

I'm using PhantomJS 1.7.0 and Poltergeist 1.0.2 (with Rails 3.2.8), all under Mac OS 10.8.2. Please let me know if there's any more information that would be helpful in tracking this down.

**Comment by jbaudanza** [comment]
Now that #581 is merged, I think this can be closed.

**Comment by route** [comment]
Yep thanks!

**Comment by mockdeep** [comment]
Is there a plan to release a new gem version for this? Running off of head my specs pass, but the latest gem release breaks because select options aren't triggering the right events.

**Comment by cseelus** [comment]
I read its [issued for the next release](https://github.com/teampoltergeist/poltergeist/blob/master/CHANGELOG.md), ran into problems too.
