### ISSUE TITLE
window.location and current_path/current_url

### ISSUE THREAD

**Issue by zekus** [teampoltergeist/poltergeist#220]
I have the following scenario to test a drop-down menu that redirects to a new page when an option is selected using javascript window.location

``` ruby
scenario "reload the page selecting the city", :js => true do
  select('London', from: 'search_location')
  current_path.should == '/London'
end
```

Using the Selenium driver the test passes but when I use Poltergeist, unless I put a **sleep 0.1** statement between the select and the current_path test, it refuses to pass.

**Comment by monsteronfire** [comment]
@hakanensari That fix helped me. Thank you! :)

**Comment by twalpole** [comment]
@monsteronfire That answer is from 4 years ago, and completely outdated.  Nowadays, just use the `have_current_path` matcher 
 
    expect(page).to have_current_path('whatever path you expect')

**Comment by monsteronfire** [comment]
@twalpole Yes, I realised that when I started testing it and realised it passes with any phrase at all.

Thanks for your comment, I'll try it out. 👍 🦄

**Comment by monsteronfire** [comment]
@twalpole I don't think that solution works for me, unfortunately. I'm trying to test a redirect that is triggered by setting `window.location.href` to an external domain in JS. Thanks, anyway. :)

**Comment by twalpole** [comment]
@monsteronfire Shouldn't make any difference how you're triggering the page change, the have_current_path matcher will wait/retry until the "browser" tells Capybara it's on that page, or Capybara.default_max_wait_time seconds has expired (which will raise an error).  The only difference when dealing with an external domain is that you might want to pass the `url` option so the entire url gets compared

    expect(page).to have_current_path('http://external-domain.com', url: true)

**Comment by monsteronfire** [comment]
@twalpole Thank you so much! It worked perfectly after I added `url: true`.
