### ISSUE TITLE
fill_in autocomplete form

### ISSUE THREAD

**Issue by BrandonMathis** [teampoltergeist/poltergeist#274]
Seems like to me that poltergeist is having some issues doing a fill_in on an autocomplete form, especially on fields that already have content.

ie: `fill_in :name, with: "Bo"` shows no change to the input field when I generate a capybara_screenshot

A workarround I found for this is to fill in our autocomplete fields via: 
```
page.execute_script "$('input[name=#{locator}]').val('#{with}')"
```

**Comment by jjb** [comment]
I'm experiencing this problem as well.

**Comment by twalpole** [comment]
If a minimal test case is provided that exhibits this behavior with latest poltergeist we can reopen, otherwise I'm closing this due to age
