### ISSUE TITLE
click_link fails

### ISSUE THREAD

**Issue by ghost** [teampoltergeist/poltergeist#277]
I am trying to switch a project from selenium to poltergeist. I am having a problem with a test that clicks a link.

Here is my example:

``` ruby
it 'can sign out', :js do
  login_as user
  find_link('sign out').click
  current_path.should == root_path
end
```

This test fails, and if I run it with pry, I receive `{"status"=>"fail", "click"=>{"x"=>949, "y"=>19.5}}` when `find_link('sign out').click` runs.

Here's the output of `page.driver.render 'tmp/page.png', full: true`

![page](https://f.cloud.github.com/assets/29762/264728/ebd0292e-8d98-11e2-9ca7-7103c54dab56.png)

It certainly looks like 949,19.5 is a valid place to click the sign out link, and there are no overlapping elements.

I have tried the following:

``` ruby
click_link 'sign out' # => {"status"=>"fail", "click"=>{"x"=>949, "y"=>19.5}}
find_link('sign out') # => #<Capybara::Element tag="a">
find_link('sign out').trigger('click') # => "click"
current_path == root_path # => false
find("a[href='#{ destroy_user_session_path }']") #=> #<Capybara::Element tag="a">
find("a[href='#{ destroy_user_session_path }']").trigger('click') #=> "click"
current_path == root_path # => false
```

It is probably worth mentioning that this test passes with selenium, and it works in the browser.

What [c|sh]ould I be doing differently?

**Comment by TriptiMittal** [comment]
Is there any solution to this thread? I am facing the same issue.

**Comment by abhay-da** [comment]
we are still facing this issue. 

  phantomjs (2.1.1.0)
  poltergeist (1.15.0)
  capybara (~> 2.1)
  cliver (~> 0.3.1)
  websocket-driver (>= 0.2.0)
  powerpack (0.1.1)
