### ISSUE TITLE
Fails silently when force_ssl set to true

### ISSUE THREAD

**Issue by pwim** [teampoltergeist/poltergeist#278]
In my application, I had `config.force_ssl = true`

When I tried adding poltergeist, no requests were showing up in my `test.log`. After some investigation, I saw the url was `about:blank` and the body of the request was

```html
<html><head></head><body></body></html>
```

I had given up on poltergeist, and tried webkit-capybara instead. It gave me the error

```
Unable to load URL: http://127.0.0.1:57361/ because of error loading https://127.0.0.1:57361/: SSL handshake failed
```

which helped me figure out the problem with poltergeist was trying to load the SSL page.

It would be nice if their was a warning or exception under the same circumstances with poltergeist. But my main motivation in reporting this bug is so if other people have the same issue, it will show up in their search results (I wasn't able to find any clues by googling).

**Comment by twalpole** [comment]
In the master branch `network_traffic` should now include the error information for resources that were requested in a page
