### ISSUE TITLE
`within_window` raises `TimeoutError`

### ISSUE THREAD

**Issue by xhh** [teampoltergeist/poltergeist#282]
Hi, I used the following code in my Cucumber steps (where a new window is opened):

```ruby
  puts current_path
  page.within_window('/practices/do') do
    puts current_path
  end
```

It prints two different path when using the Selenium driver. However with poltergeist it raises the following `TimeoutError`.

> Timed out waiting for response to {"name":"push_window","args":["/practices/do"]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker. (Capybara::Poltergeist::TimeoutError)

Any ideas? Thanks!

**Comment by twalpole** [comment]
Closing due to a number of poltergeist versions having been released with support for the Capybara window API (other than maximize).
