### ISSUE TITLE
TypeError: 'undefined' is not a function

### ISSUE THREAD

**Issue by barmstrong** [teampoltergeist/poltergeist#292]
I get this error when running my test:

```
     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

       TypeError: 'undefined' is not a function (evaluating 'function(e) {
                    this.visible = true;
                    this.update(e)
                }.bind(this)')
           at http://127.0.0.1:59232/assets/rickshaw.js:1729
           at http://127.0.0.1:59232/assets/rickshaw.js:1562
           at http://127.0.0.1:59232/assets/rickshaw.js:174 in klass
           at http://127.0.0.1:59232/assets/rickshaw.js:2705
           at http://127.0.0.1:59232/assets/jquery.js:975
           at http://127.0.0.1:59232/assets/jquery.js:1085
           at http://127.0.0.1:59232/assets/jquery.js:407
           at http://127.0.0.1:59232/assets/jquery.js:84
```

But this error doesn't show up when I visit the page at localhost:3000 in development (nothing in the chrome javascript console).  So I'm not sure why it's happening during the test.  Could the load order of jquery etc be different in the test environment? (this is rails).  In development jquery loads before rickshaw, but I'm not sure I'm reading the output correctly above that this is showing load order.

Any other ideas?

**Comment by amypivo** [comment]
I'm also having issues with React. I'm trying to run functional tests so I can't directly change the code. I writing a prototype bind script and using poltergeistjs run with no luck. Any idea?

**Comment by yaauie** [comment]
@amypivo have you tried using the implementation of `Function.prototype.bind` submitted by @cairo140 above? Perhaps providing additional information can help isolate the problem (e.g., ruby, poltergeist, phantomjs versions, failure backtraces, etc.).

This specific ticket is closed, has been for a long time, and no new information has been added to indicate that the initial resolution was invalid; it may be best to provide a wholly new bug report (with complete, minimal reproduction steps) and to reference this one if you think they're related.

**Comment by nrevko** [comment]
@cauro140 suggestion almost worked for me, but had to add return:
```ruby
        if(typeof Function.prototype.bind == 'undefined') {
          Function.prototype.bind = function(target) {
            var f = this;
            return function() {
              return f.apply(target, arguments);
            };
          };
        }
```

**Comment by kalashnikovisme** [comment]
same problem

**Comment by twalpole** [comment]
@kalashnikovisme You're commenting on an issue that has been closed for over 2 years, with no version info, and no actual details.  If you actually have a real problem please open a new issue with all relevant details and a minimal example that shows the problem
