### ISSUE TITLE
Possible xpath bug with Poltergeist/PhantomJS?

### ISSUE THREAD

**Issue by buob** [teampoltergeist/poltergeist#317]
I don't know enough about either one of these gems to say what the problem is, but my console told me to report it, so I am.

    When I click the "li" element with "Edit page styles" # features/step_definitions/general_steps.rb:63
      There was an error inside the PhantomJS portion of Poltergeist. This is probably a bug, so please report it. 
      
      [object Object]
          at /Users/jakebuob/.rvm/gems/ruby-1.9.3-p286/gems/poltergeist-1.2.0/lib/capybara/poltergeist/client/compiled/web_page.js:350
          at /Users/jakebuob/.rvm/gems/ruby-1.9.3-p286/gems/poltergeist-1.2.0/lib/capybara/poltergeist/client/compiled/web_page.js:38
          at /Users/jakebuob/.rvm/gems/ruby-1.9.3-p286/gems/poltergeist-1.2.0/lib/capybara/poltergeist/client/compiled/browser.js:136
          at /Users/jakebuob/.rvm/gems/ruby-1.9.3-p286/gems/poltergeist-1.2.0/lib/capybara/poltergeist/client/compiled/main.js:23
          at /Users/jakebuob/.rvm/gems/ruby-1.9.3-p286/gems/poltergeist-1.2.0/lib/capybara/poltergeist/client/compiled/connection.js:16
          at /Users/jakebuob/.rvm/gems/ruby-1.9.3-p286/gems/poltergeist-1.2.0/lib/capybara/poltergeist/client/compiled/connection.js:1 (Capybara::Poltergeist::BrowserError)
      ./features/step_definitions/general_steps.rb:64:in `/^I click the "(.*?)" element with "(.*?)"$/'
      features/pages.feature:20:in `When I click the "li" element with "Edit page styles"'

The step that triggered it was the following:

      When(/^I click the "(.*?)" element with "(.*?)"$/) do |element, content|
        find("//#{element}[text()='#{content}']").click
      end

**Comment by twalpole** [comment]
This issue is over 2 years old,  I'm going to close it for now since there have been a lot of versions of both poltergeist and phantomjs  in that time and we don't have a test case to replicate it.  If it's still happening for anyone and they can provide the html and the xpath expression that causes the error we can reopen
