### ISSUE TITLE
Not supported error with page.execute_script

### ISSUE THREAD

**Issue by IdahoEv** [teampoltergeist/poltergeist#325]
I tried switching my Capybara configs from Selenium to PhantomJS.  The docs say that page.execute_script is supported, but when I try it, I get this error:

```
Capybara::NotSupportedByDriverError:
  Capybara::Driver::Base#execute_script
```

Is there a config I'm missing, perhaps?

**Comment by nathantech2005** [comment]
I am getting this error on Poltergeist 1.13.0 and 1.12.0

Capybara::NotSupportedByDriverError:
       Capybara::Driver::Base#execute_script

Is there a workaround?

**Comment by twalpole** [comment]
Did you read the previous resolution? You're not actually using poltergeist in the test giving you the error.

**Comment by nathantech2005** [comment]
I am using Capybara with Poltergeist/PhantomJS. I tried to work around the error with this code.

page.find("##{field_id}").trigger(:focus)

And now it's saying the driver doesn't support 'trigger'.

**Comment by twalpole** [comment]
@nathantech2005 Read the previous resolution - If your test was using the poltergeist driver any found elements would support `trigger` - https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/node.rb#L154 - You are not actually using Poltergeist for the failing test (which would be obvious if you looked at the full stacktrace - you will most likely see files with 'rack_test' in them, indicating that you are actually using the rack_test driver for that test)
