### ISSUE TITLE
Support for drop files?

### ISSUE THREAD

**Issue by runemadsen** [teampoltergeist/poltergeist#342]
I have a bunch of JS that handles drag/dropping files form the desktop into the browser, uploading them to a server, and displaying them in the browser.

I can't find any docs on how you would test this using Poltergeist. Would I use drag_drop functionality with some uploaded file element? Would I fake a JQuery.Event object and trigger the "drop" event manually with `execute_script`?

Is any of this supported and working in Poltergeist?

**Comment by twalpole** [comment]
Closing as this is apparently working now.
