### ISSUE TITLE
Waiting for email to be delivered

### ISSUE THREAD

**Issue by LegendSzymon-P** [teampoltergeist/poltergeist#359]
I'm using poltergeist in spec along with email_spec gem (for testing email deliveries).

Given I have the following spec:

```
click_link 'Contact'
fill_in 'Email', with: 'john@example.com'
fill_in 'Message', with: 'Hello!'
click_button 'Send'

open_email('admin@mysite.com')
current_email.should be_delivered_from('john@example.com')
current_email.body.should include('Hello!')
```

This spec doesn't work, I've found out that it is because the "open_email" line is triggered before email is sent.

This spec works after I add "sleep 1" before "open_email" line.

When I was using webkit driver, this spec was working fine, so I'm assuming that it is poltergeist thing.

Do you know what is causing it?

**Comment by victorhazbun87** [comment]
Damm, I have the same issue.

**Comment by brntsllvn** [comment]
Same here
