### ISSUE TITLE
Capybara::Poltergeist::TimeoutError Kills Pry Session

### ISSUE THREAD

**Issue by phy5ics** [teampoltergeist/poltergeist#393]
When invoking binding.pry in an Rspec test that runs using Poltergeist, as soon as the timeout is reached, the Capybara::Poltergeist::TimeoutError is thrown. This unfortunately kills the Pry session that was started and makes debugging difficult. While a workaround is to set the timeout to an absurdly high number, this causes issues if a test is actually failing due to a timeout issue.

**Comment by tomprats** [comment]
@phy5ics Did you find a good solution to this? I'm seeing the same problem
