### ISSUE TITLE
Referrer set through driver.add_header doesn't set document.referrer correctly.

### ISSUE THREAD

**Issue by tomtaylor** [teampoltergeist/poltergeist#394]
I'd like to test behaviour when a user lands on a page on our site with a referrer set, but I can't seem to make Poltergeist accept a custom referrer.

The examples suggest that doing should work.

    page.driver.add_header("Referer", "http://example.com", permanent: false)
    page.driver.headers # => { "User-Agent" => "Poltergeist", "Referer" => "http://example.com" }
    visit(login_path)

But it doesn't make the referrer available through `document.referrer` in Javascript. Presumably because executing `visit` is the same behaviour as typing a URL in the address bar.

This gist demonstrates a mechanism of setting it explicitly, by adding a link in JS and then clicking it: https://gist.github.com/papoms/3453137. Would there be interest in accepting a patch to implement a script like this in Poltergeist?

**Comment by lasektom** [comment]
Any news about the issue? I wanted to BDD this kind of behaviour but this is effectively preventing us.
Thanks in advance!

**Comment by alexfarrill** [comment]
+1

**Comment by twalpole** [comment]
Closing due to age, if someone wants to produce a failing minimal test case we can reopen, or a PR would be considered
