### ISSUE TITLE
Document or provide an examle how to use onResourceRequested

### ISSUE THREAD

**Issue by antifarben** [teampoltergeist/poltergeist#403]
In phantomjs it is possible to block requests for example if you want to block requests to microsoft something like this:

```javascript
page.onResourceRequested = function ( requestData, networkRequest ) {
  if (!site)
    return;

  if (/microsoft/.test(requestData.url)) {
    networkRequest.abort();
    return;
  }
};
```

But I was unable to create something equivalent with poltergeist for now.
It would be great if you could provide an example or documentation howto do this.

Thank you very much!

**Comment by route** [comment]
Just merged #551
