### ISSUE TITLE
Drag&drop issue

### ISSUE THREAD

**Issue by gregmolnar** [teampoltergeist/poltergeist#413]
I am trying to test a drag&drop feature and I am not sure if it's a bug or I am doing something wrong but my test fails with poltergeist and passes with selenium. 
In my test I drag an element to another and that test if it's been removed from the first and added to the other:
```ruby
item = page.find("#column1 li#foo")
target = page.find("#column2")
item.drag_to(target)
refute page.has_selector?("#column1 li#foo")
assert page.has_selector?("#column2 li#foo")
```
Should this approach work at all? Oddly it works with selenium but fails with poltergeist and capybara-webkit.

**Comment by IDragonfire** [comment]
Similiar problem for me ...
I try to drag one element on another element.
Both are parts of `ui-sortable`,
but nothing happen.

**Comment by gregmolnar** [comment]
@IDragonfire my solution to the problem was to use selenium for those tests and poltergeist for the rest. I didn't have the time to dig deeper.

**Comment by IDragonfire** [comment]
@gregmolnar I used this solution now:
http://heywill.com/blog/2012/12/15/using-capybara-to-drag-a-jquery-ui-sortable-onto-a-jquery-ui-droppable

**Comment by twalpole** [comment]
Closing this as it doesn't seem to be a Poltergeist issue, but rather a sortable configuration issue -  If anyone believes otherwise please provide a minimal testcase and we can reopen
