### ISSUE TITLE
Server sent events with poltergeist

### ISSUE THREAD

**Issue by b0ric** [teampoltergeist/poltergeist#417]
if you're using Server Sent events (https://developer.mozilla.org/en-US/docs/Server-sent_events/Using_server-sent_events ) in your project and ActionController::Live then poltergeist always fails complaining on corresponding pages with error
```
Capybara::Poltergeist::TimeoutError:
    Timed out waiting for response to ... 
```
But this is actually a feature of Server events, not an error. Also this error do not happen if I use long-polling with AJAX.

PS: sorry, I'm quite new to RoR, so haven't figured out how to write proper rspec test for this issue, instead I created repository with test project to reproduce this error: https://github.com/b0ric/poltergeist-sse-test

**Comment by twalpole** [comment]
Is this working with PhantomJs 2 now?

**Comment by npassaro** [comment]
@twalpole haven't tested this in a long time...

**Comment by twalpole** [comment]
Closing due to lack of updates - If this is still and issue in PhantomJS 2.1.1+ we can reopen later
