### ISSUE TITLE
Issue with double encoding

### ISSUE THREAD

**Issue by woto** [teampoltergeist/poltergeist#418]
Hi sorry for bad English. First of all i don't know if it Poltergeist problem or may be Capybara or Phantomjs, and i trying to find right place to bug report :)

When i use it with Poltergeist i had a dobule encoded current_url variable for example 

```ruby
Capybara.default_driver = :poltergeist
Capybara.javascript_driver = :poltergeist

http://localhost:3000/user/products/new?utf8=%25E2%259C%2593&catalog_number=2&product_id=121242168&return_path=%252Fuser%252Fproducts%252Fstatus%252Fall%253Fprimary_key%253D44%2526sort_column%253Dcached_brand%2526sort_direction%253Dasc
```

when i use it with selenium it works as expected and looks like

```ruby
Capybara.default_driver = :selenium
Capybara.default_driver = :selenium

http://localhost:3000/user/products/new?utf8=%E2%9C%93&catalog_number=2&product_id=121242168&return_path=%2Fuser%2Fproducts%2Fstatus%2Fall%3Fprimary_key%3D44%26sort_column%3Dcached_brand%26sort_direction%3Dasc
```

Does anybody else found this bug? I can make a small demo if you need. Thanks.

**Comment by jsmestad** [comment]
I am still getting this when using master. Is anyone else?

**Comment by route** [comment]
@hampei I pushed some changes in master related to this issue, mind testing it?

**Comment by jonathan-fantham** [comment]
@route I've just hit this issue in my test suite and found that v1.6.0 still has the problem, but master seems to be fixed.

**Comment by route** [comment]
@jonathan-fantham yes I haven't released yet

**Comment by Staniiiik** [comment]
Hi, I have this problem in version 2.x.x again. It's working in version 1.9.7.

For example:

Url:
`http://mydomain/?param=a+b`

Version 1.9.7:
`http://mydomain/?param=a%20b`

Version 2.x.x
`http://mydomain/?param=a%2520b`

It's encoding "+" to "%20" and then again encoding "%" in "%20" to "%25", so I get "%2520".
