### ISSUE TITLE
PATCH http request not sending body with poltergeist

### ISSUE THREAD

**Issue by dezmathio** [teampoltergeist/poltergeist#424]
I've got a barebones scenario here with a test that shows poltergeist cannot support a patch http request, and does not send the params
https://github.com/dezmathio/patch_error

what is should have looked like:
![screen shot 2013-12-05 at 2 14 20 pm](https://f.cloud.github.com/assets/515228/1686100/7a34f1b8-5de1-11e3-9fae-0a421e1494c4.png)

what happens in poltergeist:

![screen shot 2013-12-05 at 2 06 21 pm](https://f.cloud.github.com/assets/515228/1686079/25e21776-5de1-11e3-866f-abb3c8fc814e.png)

**Comment by twalpole** [comment]
According to https://github.com/ariya/phantomjs/issues/11384 this was fixed in phantomjs 2  - closing
