### ISSUE TITLE
Triggering a click on a rails UJS delete link (data-method="delete") will sometimes request via GET, and sometimes via DELETE 

### ISSUE THREAD

**Issue by jaredbeck** [teampoltergeist/poltergeist#429]
Cross-posting http://stackoverflow.com/questions/20509011/why-does-phantomjs-intermittently-submit-get-xhr-request-for-a-rails-delete-xhr because I now believe it is a bug.

To Reproduce
-----------

**Given** the following link drawn by rails

    <a id="leave_community" data-method="delete" 
        data-confirm="Are you sure?" 
        href="/group_memberships/1">
      Leave Us
    </a>

**And** the following versions

    rails 3.2.16
    phantomjs 1.9.2 from brew bottle
    poltergeist 1.5.0
    capybara 2.2.0

**When** I run the following Capybara action 10 times

    find("#leave_community").trigger('click')

**Then** five times it passed and five times I got

    Internal Server Error No route matches [GET] "/group_memberships/1"

Symptom
---------

Expected `[DELETE]`, got `[GET]`

Logs
--------

    egrep -i '(GET|DELETE) "/group_memberships' log/test.log | tail -n 10
    Started DELETE "/group_memberships/1" for 127.0.0.1 at 2013-12-10 20:15:12 -0500
    Started GET "/group_memberships/1" for 127.0.0.1 at 2013-12-10 20:15:38 -0500
    Started GET "/group_memberships/1" for 127.0.0.1 at 2013-12-10 20:16:06 -0500
    Started DELETE "/group_memberships/1" for 127.0.0.1 at 2013-12-10 20:16:32 -0500
    Started DELETE "/group_memberships/1" for 127.0.0.1 at 2013-12-10 20:16:57 -0500
    Started GET "/group_memberships/1" for 127.0.0.1 at 2013-12-10 20:17:23 -0500
    Started GET "/group_memberships/1" for 127.0.0.1 at 2013-12-10 20:17:51 -0500
    Started GET "/group_memberships/1" for 127.0.0.1 at 2013-12-10 20:18:18 -0500
    Started DELETE "/group_memberships/1" for 127.0.0.1 at 2013-12-10 20:18:45 -0500
    Started DELETE "/group_memberships/1" for 127.0.0.1 at 2013-12-10 20:19:13 -0500

Debugging a `DELETE`
-----

A combination of `debug: true` on `Capybara::Poltergeist::Driver`, and various `puts` and `console.log`s.

    poltergeist Browser.find(css, #leave_community) returned {"page_id"=>4, "ids"=>[5]}
    {"name"=>"visible", "args"=>[4, 5]}
    poltergeist: main.js: runCommand(visible)
    poltergeist: browser.js: runCommand(visible)
    poltergeist: agent.js: nodeCall(isVisible)
    {"response"=>true}
    {"name"=>"attribute", "args"=>[4, 5, "data-method"]}
    poltergeist: main.js: runCommand(attribute)
    poltergeist: browser.js: runCommand(attribute)
    poltergeist: agent.js: nodeCall(getAttribute)
    {"response"=>"delete"}
    poltergeist Node.trigger(click)
    {"name"=>"trigger", "args"=>[4, 5, "click"]}
    poltergeist: main.js: runCommand(trigger)
    poltergeist: browser.js: runCommand(trigger)
    poltergeist: browser.js: trigger(click)
    poltergeist: agent.js: nodeCall(trigger)
    poltergeist: agent.js: Node.trigger(click)
    {"response"=>"click"}
    When I trigger delete link "#leave_community"                                                          # features/step_definitions/web_steps.rb:55
    capybara Node::Matchers.has_no_text?(["#members_count"])
    Started DELETE "/group_memberships/1" for 127.0.0.1 at 2013-12-11 12:01:33 -0500

Debugging a `GET`
------------

    poltergeist Browser.find(css, #leave_community) returned {"page_id"=>4, "ids"=>[5]}
    {"name"=>"visible", "args"=>[4, 5]}
    poltergeist: main.js: runCommand(visible)
    poltergeist: browser.js: runCommand(visible)
    poltergeist: agent.js: nodeCall(isVisible)
    {"response"=>true}
    {"name"=>"attribute", "args"=>[4, 5, "data-method"]}
    poltergeist: main.js: runCommand(attribute)
    poltergeist: browser.js: runCommand(attribute)
    poltergeist: agent.js: nodeCall(getAttribute)
    {"response"=>"delete"}
    poltergeist Node.trigger(click)
    {"name"=>"trigger", "args"=>[4, 5, "click"]}
    poltergeist: main.js: runCommand(trigger)
    poltergeist: browser.js: runCommand(trigger)
    poltergeist: browser.js: trigger(click)
    poltergeist: agent.js: nodeCall(trigger)
    poltergeist: agent.js: Node.trigger(click)
    Started GET "/group_memberships/1" for 127.0.0.1 at 2013-12-11 12:00:06 -0500
    {"response"=>"click"}
        When I trigger delete link "#leave_community"                                                          # features/step_definitions/web_steps.rb:55

**Comment by jaredbeck** [comment]
Closing due to lack of attention.

**Comment by route** [comment]
Hey @jaredbeck sorry it took so long to answer, basically you theory sounds correct to me. Have you tried PhantomJS 2.0? Maybe they fixed it?

**Comment by jaredbeck** [comment]
No worries, I switched to webkit.  Back in Dec '13 when I was trying out phantom, it didn't seem ready for production.  Now that so much time has passed, I'm sure it's more stable.
