### ISSUE TITLE
Events fired on fill_in

### ISSUE THREAD

**Issue by mremolt** [teampoltergeist/poltergeist#43]
I tried switching from capybara-webkit to poltergeist and stumbled over some differences, especially which events get fired. 

When I execute fill_in on a textarea, CW fires:
- focus
- keydown/keyup for every letter inserted
- change
- blur

Poltergeist fires: 
- change

This doesn't really simulate real user interaction and resulted in some broken tests in my suite.

**Comment by jjb** [comment]
I am also experiencing this problem.

**Comment by Bastes** [comment]
I'm also bumping into it ; sadly, this is a feature that would make sense to test what happens when emptying a search field for example.
