### ISSUE TITLE
TypeError: 'null' is not an object (when calling save_screenshot)

### ISSUE THREAD

**Issue by meaningfy** [teampoltergeist/poltergeist#431]
I just came across a request from the library to report a bug so here it is.... Thanks!

~

There was an error inside the PhantomJS portion of Poltergeist. This is probably a bug, so please report it. 

TypeError: 'null' is not an object (evaluating 'result.error')
TypeError: 'null' is not an object (evaluating 'result.error')
    at /Users/home/.rvm/gems/ruby-1.9.3-p125@myproject/gems/poltergeist-1.4.1/lib/capybara/poltergeist/client/compiled/web_page.js:364
    at /Users/home/.rvm/gems/ruby-1.9.3-p125@myproject/gems/poltergeist-1.4.1/lib/capybara/poltergeist/client/compiled/web_page.js:36
    at /Users/home/.rvm/gems/ruby-1.9.3-p125@myproject/gems/poltergeist-1.4.1/lib/capybara/poltergeist/client/compiled/web_page.js:292
    at /Users/home/.rvm/gems/ruby-1.9.3-p125@myproject/gems/poltergeist-1.4.1/lib/capybara/poltergeist/client/compiled/web_page.js:298
    at /Users/home/.rvm/gems/ruby-1.9.3-p125@myproject/gems/poltergeist-1.4.1/lib/capybara/poltergeist/client/compiled/browser.js:357
    at /Users/home/.rvm/gems/ruby-1.9.3-p125@myproject/gems/poltergeist-1.4.1/lib/capybara/poltergeist/client/compiled/browser.js:342
    at /Users/home/.rvm/gems/ruby-1.9.3-p125@myproject/gems/poltergeist-1.4.1/lib/capybara/poltergeist/client/compiled/browser.js:65
    at /Users/home/.rvm/gems/ruby-1.9.3-p125@myproject/gems/poltergeist-1.4.1/lib/capybara/poltergeist/client/compiled/main.js:21
    at /Users/home/.rvm/gems/ruby-1.9.3-p125@myproject/gems/poltergeist-1.4.1/lib/capybara/poltergeist/client/compiled/connection.js:16
    at /Users/home/.rvm/gems/ruby-1.9.3-p125@myproject/gems/poltergeist-1.4.1/lib/capybara/poltergeist/client/compiled/connection.js:1/Users/home/.rvm/gems/ruby-1.9.3-p125@myproject/gems/poltergeist-1.4.1/lib/capybara/poltergeist/browser.rb:255:in `command'
/Users/home/.rvm/gems/ruby-1.9.3-p125@myproject/gems/poltergeist-1.4.1/lib/capybara/poltergeist/browser.rb:166:in `render'
/Users/home/.rvm/gems/ruby-1.9.3-p125@myproject/gems/poltergeist-1.4.1/lib/capybara/poltergeist/driver.rb:156:in `save_screenshot'
/Users/home/.rvm/gems/ruby-1.9.3-p125@myproject/gems/capybara-2.1.0/lib/capybara/session.rb:344:in `save_screenshot'

**Comment by twalpole** [comment]
Closing since this is working for me with latest poltergeist/phantomjs, If you can produce a minimal test case that exhibits the issue we can reopen
