### ISSUE TITLE
js_errors and phantomjs_logger options are getting ignored

### ISSUE THREAD

**Issue by rwz** [teampoltergeist/poltergeist#436]
Here's the setup I'm using:

Rails 4.0.2, cucumber-rails-1.4.0, poltergeist-1.5.0, capybara: 2.2.0

```ruby
Capybara.register_driver :poltergeist_debug do |app|
  Capybara::Poltergeist::Driver.new(app, js_errors: true, phantomjs_logger: Logger.new(STDOUT))
end

Capybara.javascript_driver = :poltergeist_debug
```

I've deliberately put some `console.log` and `console.error` calls in my application.js and I see it in the browser on every page I hit. But poltergeist ignores them completely and still runs my specs like nothing is happening showing green where I expect it to error.

If I add `debug: true` to the options, I'm getting a bunch of debug output, but still no trace of my errors or log messages.

**Comment by killthekitten** [comment]
@GUI does not work for me

**Comment by sfate** [comment]
The actual problem may be in javascript hoisting.
And in case of using frameworks you can encounter with outputless `console` calls in phantomjs.

Which would work is to call it in old fashion way specifying window object.
e.g. `window.console.log`.

**Comment by twalpole** [comment]
This issue seems to be 2 things, 1 - phantomjs_logger needs to be an IO object not a Logger object (as documented) and as @sfate pointed out, if your app/library is overriding console to make it outputless you're not going to get any output.  If anyone disagrees with this, please provide a reproducible test case and we can reopen.

**Comment by momolog** [comment]
@twalpole What is an "IO object"? I cannot find any documentation on this. Could you add a link to the README, please?

**Comment by simi** [comment]
@momolog https://ruby-doc.org/core-2.2.0/IO.html. For example [File](https://ruby-doc.org/core-2.3.1/File.html) is inherited from IO. [StringIO](https://ruby-doc.org/stdlib-1.9.3/libdoc/stringio/rdoc/StringIO.html) is also inherited from IO.

**Comment by momolog** [comment]
@simi Ah, of course, makes perfect sense. Thanks.
