### ISSUE TITLE
autocomplete can't be tested

### ISSUE THREAD

**Issue by ghost** [teampoltergeist/poltergeist#439]
I realize that there are some open issues around this, but while some people have claimed to have solved this, I have found it to be impossible. My assertions for the presence of the jQuery autocomplete fields always fail, regardless of what events I trigger. Even calling the autocomplete field manually generates nothing. The code works flawlessly when tested in the browser.

After 40 hours straight of trying to troubleshoot this one line, I am wondering if anyone else has overcome the issue of Poltergeist not being able to test the jQuery UI autocomplete.

**Comment by joxxoxo** [comment]
I'm also unable to make it work with `send_keys` :(
phantomjs 2.0.0, poltergeist 1.6.0

**Comment by TommyF87** [comment]
@mmrwoods thanks for this solution, it works nicely.
