### ISSUE TITLE
Button that calls click on hidden button not invoked

### ISSUE THREAD

**Issue by justin808** [teampoltergeist/poltergeist#440]
I've got a rails remote button that I had to make hidden so that I could put the calling button inside of another form. This "dummy" button calls the real button with this simple bit of JS code:
```
    $("#js-cancel-shoot").click (event) ->
      event.preventDefault()
      $("#js-cancel-reservation-button-hidden").click()
```

When the visible "dummy" button (really a link) calls the hidden button in my capybara test, I can verify the confirm dialog shows doing a sleep. But that is not the way that capybara is supposed to wait for elements to show.

If I run this code in the test to call the hidden button directly, then my test works:

    page.execute_script(%Q{ $('#js-cancel-reservation-button-hidden').click() })

Is this likely to be a capybara issue or a poltergeist issue?

**Comment by twalpole** [comment]
I'm closing this due to age of the report and not fully understanding exactly what is being asked for by "not the way capybara is supposed to wait for elements to show".  If this is still a real issue with latest poltergeist, please clarify the issue and we can reopen
