### ISSUE TITLE
zeus rspec doesn't return to shell when js: true and driver = :poltergeist-debug

### ISSUE THREAD

**Issue by ccmcbeck** [teampoltergeist/poltergeist#442]
Per https://github.com/jonleighton/poltergeist#remote-debugging-experimental the `:inspector => true` debugging feature is experimental (and wonderful I might add).  

However, it doesn't co-exist well with `zeus`.  When that feature is turned on in the javascript driver, `zeus rspec spec/` doesn't return control to the bash shell when the command terminates.

See http://stackoverflow.com/questions/20894390/zeus-rspec-doesnt-return-to-shell-when-jstrue-and-driver-poltergeist-debug for a complete explanation

**Comment by twalpole** [comment]
Closing due to this not really being a poltergeist bug

**Comment by ccmcbeck** [comment]
Sorry, I should have closed this myself.  Keep up the great work.
