### ISSUE TITLE
Strange bug with element.hover

### ISSUE THREAD

**Issue by rahul-sekhar** [teampoltergeist/poltergeist#443]
I've come across a strange issue that has made my test suite unstable. `element.hover` occasionally fails to work and has a side effect.

After investigating various things, I inspected the element tag_name and text before calling `element.hover` and after. The element is changed to the `html` element after the call. This happens about 10% of the time.

Any insights into this behaviour? Those intermittent failing tests are driving me crazy.

**Comment by twalpole** [comment]
Closing due to lack of response
