### ISSUE TITLE
CSS does not match :focus-ed element

### ISSUE THREAD

**Issue by rubyruy** [teampoltergeist/poltergeist#444]
Trying to create a cucumber step that is basically just "start typing" (i.e. wherever the cursor already is).

Using the capybara selenium driver, this works as expected:

``` ruby
find("input:focus").native.send_keys(keys)
```

Using poltergeist however, I just get `ElementNotFound`

This may be related to ariya/phantomjs#10427

Barring a fix to that, is there any other way of just sending keys over to the browser without having to specify a particular element?

**Comment by twalpole** [comment]
When there is a resolution to https://github.com/ariya/phantomjs/issues/10427 this should be fixed - there's nothing Poltergeist can do about it.

**Comment by twalpole** [comment]
I'm closing this because it's a phantomjs issue we can do nothing about.  As a workaround, to basically do the same thing you can run

    evaluate_script('document.activeElement').send_keys(keys)
