### ISSUE TITLE
send_keys does not trigger keydown and keyup events

### ISSUE THREAD

**Issue by orslumen** [teampoltergeist/poltergeist#453]
When I use the ```send_keys``` method only the ```keypress``` event is sent.

Is there a specific reason not to fire the ```keydown``` and ```keyup``` events?

**Comment by twalpole** [comment]
PhantomJS appears to translate the keypress event we send into keyup and keydown events https://github.com/ariya/phantomjs/blob/master/src/webpage.cpp#L1431 - if this isn't correct for someone please provide a minimal testcase showing the issue and we can reopen this and see what we can do
