### ISSUE TITLE
Screenshots fail on some pages

### ISSUE THREAD

**Issue by DaniG2k** [teampoltergeist/poltergeist#457]
When trying to take automated screenshots, the process often fails. Not sure if this is a Poltergeist issue or phantomjs. Here is an example URL I've had the problem on:

http://www.scmp.com/news/hong-kong/article/1433980/pictures-first-domestic-workers-myanmar-arrive-hong-kong-amid

Please note that I've increased the timeout to 5 minutes and it still fails. The message I get upon failure is:

Timed out waiting for response to {"name":"visit","args":["http://www.scmp.com/news/hong-kong/article/1433980/pictures-first-domestic-workers-myanmar-arrive-hong-kong-amid"]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker.

Thanks

**Comment by twalpole** [comment]
Closing due to lack of response
