### ISSUE TITLE
Poltergeist raises TimeoutError randomly with CKEditor

### ISSUE THREAD

**Issue by mtsmfm** [teampoltergeist/poltergeist#461]
Poltergeist raises TimeoutError randomly with CKEditor.

Following steps will reproduce the problem.

1. `click` somewhere in page using CKEditor
2. call some Poltergeist's methods (`find`, `evaluate_script`, etc)
3. Poltergeist raises TimeoutError randomly

Please look at [this repository](https://github.com/mtsmfm/ckeditor-test).

As far as I have examined, Poltergeist raises TimeoutError if it with [CKEditor gem](https://github.com/galetahub/ckeditor) or [ckeditor-releases](https://github.com/ckeditor/ckeditor-releases), but doesn't with [ckeditor-dev](https://github.com/ckeditor/ckeditor-dev) (tested in [this PR](https://github.com/mtsmfm/ckeditor-test/pull/1)).
Perhaps, Poltergeist raises with minified CKEditor.

I wanted to identify the code that causes the problem, but really, it's seems difficult to me, sorry :cry:

**Comment by twalpole** [comment]
From looking at the log this seems to have been a case where the responses got out of sync with the commands sent and therefore cause all sorts of weird behavior.  The out of sync behavior was fixed in poltergeist 1.8.0 so hopefully this should be fixed.  If it's not we can reopen
