### ISSUE TITLE
Setting `screen.width`

### ISSUE THREAD

**Issue by tpreusse** [teampoltergeist/poltergeist#465]
Please add a proper interface to set `screen.width` or at least use `:window_size`.

Old issue that was closed by owner: https://github.com/jonleighton/poltergeist/issues/254

### Workaround
```
visit '/'
page.evaluate_script('window.screen = {width: 1280, height: 960}')
```
This evil hack seems to kind of work for my case but relies on the script being evaluated before jquery dom ready. A proper interface would be much better.

**Comment by twalpole** [comment]
Closing since Window#resize is now supported
