### ISSUE TITLE
Firing a click at co-ordinates...

### ISSUE THREAD

**Issue by GCorbel** [teampoltergeist/poltergeist#466]
Hello,

I'm trying to click on a button and I have this message : 

```
Firing a click at co-ordinates [1043.5, 288] failed. Poltergeist detected another element with CSS selector '' at this position. It may be overlapping the element you are trying to interact with. If you don't care about overlapping elements, try using node.trigger('click').
```

If I look by css and I do `trigger('click')`, I have this message : 

```
Unable to find css "provider_service_formula_id_3"
```

But when I'm trying with capybara-webkit or with chrome it works. What can I do?

Thanks!

**Comment by mmcfarland-cavulus** [comment]
This still seems to be a problem -- hidden elements don't register events, but Poltergeist still seems to be throwing a hidden-element-catcher error (see [here](https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/client/compiled/agent.js#L503-L522)). Hidden elements don't seem to catch events, so this seems like there should be a test of the elements visibility or something. Right?
