### ISSUE TITLE
Setting proxy details and then opening new session clears proxy?

### ISSUE THREAD

**Issue by maxrosecollins** [teampoltergeist/poltergeist#474]
Am I setting the proxy correctly when using sessions? It doesn't seem to work if I open a new session

This doesn't work with a proxy
```ruby
    options = {
       :js_errors => false,
       :phantomjs_options => ["--proxy=#{proxy.ip}:#{proxy.port}", "--proxy-auth=#{proxy.username}:#{proxy.password}"]
    }
    Capybara.register_driver :poltergeist do |app|
      Capybara::Poltergeist::Driver.new(app, options)
    end
    Capybara.default_driver = :poltergeist
    Capybara.javascript_driver = :poltergeist
    Capybara.default_wait_time = 20
    Capybara.ignore_hidden_elements = true
    Capybara.run_server = false
    Capybara.app_host = 'http://www.facebook.com'


    session = Capybara::Session.new(:poltergeist)

    session.visit('/')

    session.driver.quit
```

This does work with a proxy but obviously doesn't open a new session, what am I doing wrong?
```ruby
    options = {
       :js_errors => false,
       :phantomjs_options => ["--proxy=#{proxy.ip}:#{proxy.port}", "--proxy-auth=#{proxy.username}:#{proxy.password}"]
    }
    Capybara.register_driver :poltergeist do |app|
      Capybara::Poltergeist::Driver.new(app, options)
    end
    Capybara.default_driver = :poltergeist
    Capybara.javascript_driver = :poltergeist
    Capybara.default_wait_time = 20
    Capybara.ignore_hidden_elements = true
    Capybara.run_server = false
    Capybara.app_host = 'http://www.facebook.com'

    visit('/')
```

**Comment by omerpucit** [comment]
Try to run it in controller action, so when it will control through controller level it will update the new proxy ip. Like this way

<pre>
def index
    options = {
       :js_errors => false,
       :debug => true,
       :phantomjs => "/Users/Umer/Desktop/phantomjs-2.0.0-macosx/bin/phantomjs",
       #:phantomjs_options => ["--proxy=#{proxy.ip}:#{proxy.port}", "--proxy-auth=#{proxy.username}:#{proxy.password}"]
       :phantomjs_options => ["--proxy=88.150.136.178:3128"]
    }
    Capybara.register_driver :poltergeist do |app|
      Capybara::Poltergeist::Driver.new(app, options)
    end
    Capybara.default_driver = :poltergeist
    Capybara.javascript_driver = :poltergeist
    Capybara.default_wait_time = 20
    Capybara.ignore_hidden_elements = true
    Capybara.run_server = false
    Capybara.app_host = 'http://mxtoolbox.com'


    session = Capybara::Session.new(:poltergeist)

    session.visit('/WhatIsMyIP/')

    file = File.new("test3.html", "w+")
    file.write(session.body)
    file.close

    session.driver.quit
end
</pre>

**Comment by twalpole** [comment]
Closing due to lack of response about running with debug: true
