### ISSUE TITLE
Can't fill in <input type="date">

### ISSUE THREAD

**Issue by Bastes** [teampoltergeist/poltergeist#480]
This issue was initially [posted on Capybara's](https://github.com/jnicklas/capybara/issues/1293), where [twalpole](https://github.com/twalpole) closed it saying it was due here ; so here it is ^^

I'm using capybara and poltergeist for feature testing on a form that has an &lt;input type="date"&gt; field. It works fine but for the date field not being filled at all by the:
```Ruby
fill_in "Date", with: I18n.l(Date.today)
```

The fill_in method ends well, but the test fails because the field remains empty.

================================================

Hope this will help:
```Ruby
find_field("Date").tap { |f| puts f.value.inspect }.set(I18n.l(Date.today))
find_field("Date").tap { |f| puts f.value.inspect }
```
Produces:
```
""
"15/04/2014"
```
(yes, my locale is fr ^^)

But the test still fails because the "Date" field remains empty.

================================================

More diagnosis material:
Filling the field on the page in JavaScript, it expects a "YYYY-MM-DD" value. Though doing this:
```Ruby
fill_in "Date", with: I18n.l(Date.today, format: '%Y-%m-%d'))
```
Or:
```Ruby
find_field("Date").tap { |f| puts f.value.inspect }.set(I18n.l(Date.today, format: '%Y-%m-%d'))
```
Doesn't work any better.

**Comment by bdvholmes** [comment]
@Bastes this appears to work as long as you provide the date in the format that the DOM understands i.e. 2014-04-23

I guess the challenge with entering the date as the user is that there are different locales.

**Comment by Bastes** [comment]
@bdvholmes As I mentionned in the description, I tried entering the date in YYYY-MM-DD format, and that didn't work either. I did:
```ruby
fill_in "Date", with: I18n.l(Date.today, format: '%Y-%m-%d'))
```
It still didn't set the field.

**Comment by bdvholmes** [comment]
It might not be immediately obvious what's happening in capybara but I'm finding my form submits fine. What happens if you do something like:

    fill_in "Date", with: '2004-04-23'
    $('element').get(0).value

or something

**Comment by route** [comment]
Yeah it just works.
