### ISSUE TITLE
What is the default downoad directory If I download a CSV file via poltergeist

### ISSUE THREAD

**Issue by barek2k2** [teampoltergeist/poltergeist#485]
Hello, Right now I am downloading CSV file using selenium driver and I can specify download directory but how to specify the download directory for poltergeist? and what is the default download directory if I download file using poltergeist? Please help!

**Comment by Paxa** [comment]
@barek2k2 Did you find an answer?

**Comment by RKushnir** [comment]
@thedelchop There's actually an issue here — with the gem's documentation.

**Comment by s2t2** [comment]
unanswered here: http://stackoverflow.com/questions/35585994/downloading-a-csv-with-capybara-poltergeist-phantomjs

**Comment by twalpole** [comment]
Poltergeist doesn't support downloading, so there is no "default download directory" - workarounds are documented in the SO question you linked to.
