### ISSUE TITLE
Any way of setting field text without triggering a blur?

### ISSUE THREAD

**Issue by lsimoneau** [teampoltergeist/poltergeist#488]
I'm implementing a Trello-style inline edit functionality, where clicking on a piece of text replaces it with an input field. Focusing out of the input field leaves the edits but doesn't save them, pressing enter triggers a save.

This turns out to be essentially impossible to test with Poltergeist: I can't use `send_key` to fire the enter keypress on the input, as the act of filling it in with `set` has already blurred it and therefore caused it to disappear and be replaced by static text. The end of the `set` method always triggers `blur` on the input:

https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/client/agent.coffee#L203

(I also can't add a "\n" to the end of the input, as the `keycode` and `which` on the triggered event always come up as 0, which I think is because of https://bugs.webkit.org/show_bug.cgi?id=16735).

Ideally there would be a way to fill out a form field without automatically blurring it in the process.

**Comment by twalpole** [comment]
You should be able to use Node#send_keys to just send the keystroke events without losing focus at the end
