### ISSUE TITLE
Incorrect handling of apostrophe and quotation marks with send_keys

### ISSUE THREAD

**Issue by aprescott** [teampoltergeist/poltergeist#492]
It's possible that this is a phantomjs issue but I'm unsure. I'm happy to move it over to them if so.

If you hook up a `keydown` handler and log `event.which`, you discover the following values for given characters inputted to `send_keys`:

```ruby
element.native.send_keys(%{'}) # event.which === 0
element.native.send_keys(%{"}) # event.which === 222
```

In a real browser, both of these keys leave `event.which === 222`, but in the case of `"`, `event.shiftKey === true`.

The end result is that when you `send_keys(%{"})`, the browser really sees a `'` keypress.

I'd love a workaround for this if there is one.

This is somewhat related to #420 (adding modifier support for `send_keys`), I think.

**Comment by twalpole** [comment]
Closing this as a phantomjs issue  -- if it's still an issue we can reopen
