### ISSUE TITLE
Support accepting javascript confirmation dialogs

### ISSUE THREAD

**Issue by atambo** [teampoltergeist/poltergeist#50]
Selenium allows you to:

``` ruby
page.driver.browser.switch_to.alert.accept
```

How can I do something like the above with poltergeist?

**Comment by badosu** [comment]
@michaelglass solution works very well until a proper fix is pushed.

This should be referenced somewhere as it would have saved a lot of time for me.

**Comment by Bastes** [comment]
@michaelglass Waiting for a proper implementation in poltergeist, this is an awesome solution ^^ kudos sir, you've made my and my teammate's day ^^d

**Comment by twalpole** [comment]
@Bastes Poltergeist has had support for Capybaras modal api since September 2015 - you shouldn't need to be including anything else.  If it's not working for you please open a new issue with details.
http://www.rubydoc.info/github/jnicklas/capybara/Capybara%2FSession%3Aaccept_alert

**Comment by Bastes** [comment]
@twalpole Indeed it works ^^ could benefit from a little publicity too imo, I'll see if I can send a pull request with a little something in the readme. Thanks ^^d
