### ISSUE TITLE
Timeout on screenshot

### ISSUE THREAD

**Issue by AlreadyTalk** [teampoltergeist/poltergeist#507]
I can´t take a screenshot if the server its on the same machine.
I pass to explain. I try to take a screenshot from my machine (that is the server, its on development ) and it gives me the timeout. But if a try to take a screenshot from the same page, but its running on my associate machine, it works. I just don't now how to resolve this.
Can someone help me please.
I'm using  Poltergeist, Capybara and PhantomJS.

**Comment by twalpole** [comment]
Closing due to age and lack of response
