### ISSUE TITLE
Incompatibility with jQuery MaskMoney

### ISSUE THREAD

**Issue by emaiax** [teampoltergeist/poltergeist#508]
Hey guys,

I'm using the [jQuery MaskMoney] (https://github.com/plentz/jquery-maskmoney) to apply mask on my application inputs and it started to behave strangely while testing under capybara + poltergeist.

```ruby
fill_in 'Cost', with: '21,90'
```

```javascript
$(':input').filter('[mask="decimal"]').each(function () {
  value = parseFloat(this.value).toFixed(2);

  $(this)
    .val(value)
    .maskMoney({ allowNegative: true, thousands:'.', decimal:',', precision: 2, affixesStay: true })
    .maskMoney('mask');
});
```

Taking a screenshot of application after this filling shows the value '00,021,90'.

I'm not sure what specific point broke yet. Do you have something in mind about that?

**Comment by twalpole** [comment]
If someone wants to produce a minimal testcase exhibiting the problem behavior we can try and fix this, otherwise I'm closing it for now since we can't test support for every JS library out there.
