### ISSUE TITLE
Support new capybara window api

### ISSUE THREAD

**Issue by fabn** [teampoltergeist/poltergeist#509]
Is there any plan to support the new window api introduced in capybara 2.3.0?

Here is the pull request: jnicklas/capybara#1235

Current poltergeist with capybara 2.3.0 gives some warnings about that such as

```
DEPRECATION WARNING: Passing string argument to #within_window is deprecated. Pass window object or lambda.
```

**Comment by ghallberg** [comment]
Any progress on this?

**Comment by cykhoo** [comment]
Hi, @ghallberg, have a look at commit 2d23867279e1ccd7e064a51bb750ea75a71ecd0e, which adds window support. My code is no longer emitting deprecation warnings.

**Comment by ghallberg** [comment]
@cykhoo Are you running on poltergeist master then? If this is all done then I'll just hope and wait for a release soonish :)

**Comment by cykhoo** [comment]
Not running master, just the specific ref:

gem 'poltergeist', git: 'git@github.com:teampoltergeist/poltergeist.git', ref: '2d23867279e1ccd7e064a51bb750ea75a71ecd0e'

**Comment by ghallberg** [comment]
@cykhoo I see, thank you very much!

**Comment by twalpole** [comment]
This has been supported for the last couple of releases (other than Window#maximize) - Closing
