### ISSUE TITLE
error inside the PhantomJS portion of Poltergeist when trigger a javascript event

### ISSUE THREAD

**Issue by cintamani** [teampoltergeist/poltergeist#515]
Hi all, 

I have a link, that open a popup via javascript with a 'onclick' event. Here the HTML portion: 

``` <a id="wonky_wabbits" href="#" onclick="Netent_splash.openFullscreen(212, 'real');return false;">Şimdi Oyna</a> ``` 

When I try to trigger the event with this: ```page.find_link('Free Play').trigger('onclick')```
this is the error I have: 

```
Unknown event
[object Object]
    at /Users/cintamanipuddu/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/poltergeist-1.5.1/lib/capybara/poltergeist/client/compiled/web_page.js:387
    at /Users/cintamanipuddu/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/poltergeist-1.5.1/lib/capybara/poltergeist/client/compiled/web_page.js:36
    at /Users/cintamanipuddu/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/poltergeist-1.5.1/lib/capybara/poltergeist/client/compiled/node.js:23
    at /Users/cintamanipuddu/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/poltergeist-1.5.1/lib/capybara/poltergeist/client/compiled/browser.js:310
    at /Users/cintamanipuddu/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/poltergeist-1.5.1/lib/capybara/poltergeist/client/compiled/browser.js:65
    at /Users/cintamanipuddu/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/poltergeist-1.5.1/lib/capybara/poltergeist/client/compiled/main.js:21
    at /Users/cintamanipuddu/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/poltergeist-1.5.1/lib/capybara/poltergeist/client/compiled/connection.js:16
    at /Users/cintamanipuddu/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/poltergeist-1.5.1/lib/capybara/poltergeist/client/compiled/connection.js:1
from /Users/cintamanipuddu/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/poltergeist-1.5.1/lib/capybara/poltergeist/browser.rb:275:in `command'
``` 

I'm using capybara (2.3.0) and rspec-rails (~> 2.0) with rails 3.2.17 and ruby 1.9.3p429
I have no error if I try to trigger every other events that have no javascript active. 
Also, the error show up 9/10 times I run it, 1/10 it work... 

I'm using the trigger because the simple find_link('Free Play').click or click 'Free Play' doesn't start the javascript event. If you have any other solution that does not involve the trigger, please let me know.

Thanks

**Comment by mikekellyio** [comment]
really simple fix, you're triggering the wrong thing. In general, when triggering, don't specify the "on" part of the event.

it should be: ``find_link('Free Play').trigger('click')``
