### ISSUE TITLE
page.status_code == nil

### ISSUE THREAD

**Issue by runa** [teampoltergeist/poltergeist#524]
Hello :)

We're debugging a strange problem where sometimes, `page.status_code` is `nil`;

When this happens, we take a screenshot and save the HTML and both look good (so, we should have got a `page.status_code == 200`.

This doesn't happens all the time, but from time to time we get wrongly failing tests.

Any hints on what might be going on?

ps: we're using poltergeist with capybara.

**Comment by muan** [comment]
Just got this problem as well, but only on circle CI, seems to be fine locally. The tests are doing something like this:

```ruby
paths.each do |path|
  visit path
  assert_equal 200, page.status_code, path
end
```

This is the debug log:

```
{"name":"set_js_errors","args":[false]}
{"response":true}
{"name":"set_debug","args":[true]}
{"response":true}
{"name":"visit","args":["http://127.0.0.1:42353/users"]}
{"response":{"status":"success"}}
{"name":"status_code","args":[]}
{"response":200}
{"name":"visit","args":["http://127.0.0.1:42353/products/0002/orders/new"]}
{"response":{"status":"success"}}
{"name":"status_code","args":[]}
{"response":200}
{"name":"visit","args":["http://127.0.0.1:42353/account"]}
{"response":{"status":"success"}}
{"name":"status_code","args":[]}
{"response":null}
{"name":"current_url","args":[]}
{"response":"http://127.0.0.1:42353/account"}
{"name":"body","args":[]}
{"response":"**the correct page html here**"}
{"name":"render","args":["/tmp/circle-artifacts.yzgHvEe/screenshot_2015-05-06-20-50-50.524.png",true,null]}
{"response":true}
    HTML screenshot: /tmp/circle-artifacts.yzgHvEe/screenshot_2015-05-06-20-50-50.524.html
    Image screenshot: /tmp/circle-artifacts.yzgHvEe/screenshot_2015-05-06-20-50-50.524.png
BasicViewsTest
  test_a_user_should_be_able_to_visit_these_paths                   FAIL (6.03s)
MiniTest::Assertion:         account_path.
        <200> expected but was
        <nil>.
        /home/ubuntu/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/test/unit/assertions.rb:36:in `assert'
        /home/ubuntu/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/test/unit/assertions.rb:250:in `assert_equal'
        /home/ubuntu/testapp/test/integration/basic_views_test.rb:110:in `block (2 levels) in <class:BasicViewsTest>'
        /home/ubuntu/testapp/test/integration/basic_views_test.rb:108:in `each'
        /home/ubuntu/testapp/test/integration/basic_views_test.rb:108:in `block in <class:BasicViewsTest>'
        /home/ubuntu/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/test/unit/testcase.rb:17:in `run'
        /home/ubuntu/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/test/unit.rb:27:in `run'
        /home/ubuntu/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/test/unit.rb:780:in `run'
        /home/ubuntu/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/test/unit.rb:372:in `block (2 levels) in autorun'
        /home/ubuntu/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/test/unit.rb:33:in `run_once'
        /home/ubuntu/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/test/unit.rb:371:in `block in autorun'
```

Any thoughts?

**Comment by gavinsimmons** [comment]
Not sure if this is the same issue, but I am getting consistent `status_code` is `nil` for at least 1 test.

I only seem to be getting it when I use:

    within_window open_new_window do
      visit url
      check status_code, save screenshot etc 
    end

But it does not always fail when I use `within_window open_new_window do`. The case where it is failing is a link that has 1 redirect. I tried adding a sleep statement to make sure the redirect was finished before I check the status code, but that does not seem to be the issue.

Here is the relevant part of my debug log:

    {"name":"window_handles","args":[]}
    {"response":["0"]}
    {"name":"open_new_window","args":[]}
    {"response":true}
    {"name":"window_handles","args":[]}
    {"response":["0","1"]}
    {"name":"window_handle","args":[]}
    {"response":"0"}
    {"name":"switch_to_window","args":["1"]}
    {"response":true}
    {"name":"visit","args":["http://counter-strike.net"]}
    [cycle] terminating; zero elements found by selector
    [cycle] terminating; zero elements found by selector
    {"response":{"status":"success"}}
    {"name":"resize","args":[1024,768]}
    {"response":true}
    {"name":"status_code","args":[]}
    {}
    {"name":"current_url","args":[]}
    {"response":"http://blog.counter-strike.net/"}

Thanks for any help that anybody can provide!

**Comment by twalpole** [comment]
@gavinsimmons  I believe open_new_window returns a boolean not a window handle, so caliing within_window open_new_window isn't really valid

**Comment by twalpole** [comment]
After a quick look through the code - it appears this happens when a visited site like http://counter-strike.net redirects, phantomjs calls onResourceReceived with a redirectURL of http://blog.counter-strike.net but then the next onResourceRequested callback comes with a URL of http://blog.counter-strike.net/   -  due to the trailing / on the one the two aren't equal, so poltergeist loses track of the request it's supposed to get the status code from.  I'm not really sure why this happens for some sites and not others though.

**Comment by twalpole** [comment]
This should be fixed in the master branch
