### ISSUE TITLE
Unsafe JavaScript attempt to access frame with URL http://googleads.g.doubleclick.net/pagead/html/r20140819/r20140417/zrt_lookup.html from frame with URL about:blank. Domains, protocols and ports must match.

### ISSUE THREAD

**Issue by gaoguoxin** [teampoltergeist/poltergeist#526]
Sometimes  I got this error  
```ruby
Unsafe JavaScript attempt to access frame with URL http://googleads.g.doubleclick.net/pagead/html/r20140819/r20140417/zrt_lookup.html from frame with URL about:blank. Domains, protocols and ports must match.
```
and here is my code
```ruby
require "capybara"
require 'capybara/poltergeist'
require "proxy"
class Man
  	include Capybara::DSL
  	def initialize(site,wait=10)
  		proxy = Proxy.new

		options = {
		   :js_errors => false,
		   :phantomjs_options => ["--proxy=#{proxy.host}:#{proxy.port}"]
		}

		Capybara.register_driver :poltergeist do |app|
		  Capybara::Poltergeist::Driver.new(app, options)
		end

        Capybara.configure do |conf|
        	conf.run_server              = false
        	conf.app                     = ''
        	conf.default_driver          = :poltergeist
        	conf.javascript_driver       = :poltergeist
        	conf.default_wait_time       = wait        
        	conf.ignore_hidden_elements  = false
        	conf.app_host                = site
        end
  		super()
  	end

  	def get_info
  		visit('/')
  	end
end
```

if I have some error? or something that I forget to config?

**Comment by twalpole** [comment]
Is this still an issue with latest poltergeist and phantomjs ?

**Comment by twalpole** [comment]
Closing due to lack of response, if this is still an issue with latest versions of poltergeist and phantomjs we can reopen

**Comment by AhmedKamal20** [comment]
It's still happening with 'poltergeist => 1.9.0' & 'phantomjs => 1.9.8'

**Comment by simi** [comment]
@AhmedKamal20 can you provide any script to reproduce?

**Comment by AhmedKamal20** [comment]
@simi 
```
Given(/^I'm on "([^"]*)"$/) do |url|
  visit url
  page.driver.network_traffic.each do |request|
      request.response_parts.uniq(&:url).each do |response|
       puts "Error : #{response.url}" if response.status == 500
      end
    end
  page.driver.clear_network_traffic
end
```

**Comment by AhmedKamal20** [comment]
[ariya/phantomjs#12697](https://github.com/ariya/phantomjs/issues/12697)

**Comment by AhmedKamal20** [comment]
Is there any solution for poltergeist ? most of the workarounds in this issue are for casperjs, and i can't make it work

**Comment by twalpole** [comment]
@AhmedKamal20 First step would be to get off phantomjs198 - 2.1.1 has been released, has multiple platform binaries available and is MUCH better than 1.9.8 as far as support of features in current browsers.  If that doesn't fix your issue then you'll need to provide a reproducible test case -- what you have provided won't produce the issue without the specific url that is causing the issue.

**Comment by AhmedKamal20** [comment]
I can't find any guide for updating for 2.1.1, without building
the structure of 2.1.1 folder very different from 1.9.8 one

**Comment by AhmedKamal20** [comment]
But got another one : 

```
Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.
```

@twalpole Did you faced this before ?

**Comment by twalpole** [comment]
It's a security restriction, but unrelated to this issue - if you can't figure it out create a new issue here or on stackoverflow with enough info for someone to reproduce
