### ISSUE TITLE
jQuery $.ajax requests missing parameters when using poltergeist

### ISSUE THREAD

**Issue by jordanmaguire** [teampoltergeist/poltergeist#532]
Hi team,

I'm trying to test a piece of basic ajax functionality using RSpec feature test.

Here's the test:

``` ruby
require 'spec_helper'

feature 'Users can fill in their Objectives Tracker' do

  sign_in_as(:member)

  background do
    report = FactoryGirl.create(:report, club: current_user.club, current_step: "summary")
    @new_assignee = FactoryGirl.create(:user, club: report.club)

    # ReportPillars
    first = FactoryGirl.create(:report_pillar, pillar_name: "A First Pillar", report: report)
    second = FactoryGirl.create(:report_pillar, pillar_name: "B Second Pillar", report: report)

    # Objectives
    @report_objective = FactoryGirl.create(:report_objective, enabled: true, accepted: true, report_pillar: first, objective_statement: "First Objective")

    # Strategies
    FactoryGirl.create(:report_strategy, accepted: true, report_objective: @report_objective, strategy_statement: "First Objective's Accepted Strategy")

    open_main_menu_option("Objectives Tracker")
  end

  scenario 'User fills in details for an Objective', :ajax, :js do
    within(".objective-tracker tbody") do
      # Select a new assignee
      select(@new_assignee.name)
    end

    # Member fills in due date using calendar (this will select current month)
    find(".ui-datepicker-trigger").click
    click_button("Done")

    wait_for_ajax!

    expect(@report_objective.reload.assignee).to eq(@new_assignee)
    expect(@report_objective.due_date).to eq(Date.today.beginning_of_month)
  end
end
```

So here's the important parts:
- The functionality works in browser
- The same test passes using selenium as a web driver

After a little investigation, I found that when using poltergeist the issue is that the request parameters don't come through. In the controller actions, the `params` hash doesn't include them.

I think it's something to do with the [headers](https://github.com/teampoltergeist/poltergeist#manipulating-request-headers). My rough theory is that without a certain type of header Rails doesn't know what to do with the data and ignores it.

I've done some googling and can't find anything to do with poltergeist and ajax requests failing so I figured I'd raise the issue here.

I would have thought AJAX requests would be pretty common, so perhaps I'm missing something obvious.

If it helps, here's the coffeescript that makes the request:

``` coffeescript
# Initialize an empty namespace
TopClub.ObjectivesTracker = {} if !TopClub.ObjectivesTracker

class TopClub.ObjectivesTracker.ObjectiveRow

  constructor: (objectiveRow) ->
    @_objectiveRow = $(objectiveRow)
    @_idInput = @_objectiveRow.find("input[name*=id][type=hidden]")
    @_assigneeSelect = @_objectiveRow.find("select")
    @_dateInput = @_objectiveRow.find("input.month_year_date_picker")
    @_doneInput = @_objectiveRow.find("input[name*=complete][type=checkbox]")

    @_assigneeSelect.change(@_updateObjectiveOnAPI)
    @_dateInput.change(@_updateObjectiveOnAPI)
    @_doneInput.change(@_updateObjectiveOnAPI)

  _asQueryParams: =>
    {
      objective: {
        id: @_idInput.val(),
        assignee_id: @_assigneeSelect.val(),
        due_date: @_dateInput.val(),
        complete: @_doneInput[0].checked
      }
    }

  _updateDidFail: =>
    $cells = @_objectiveRow.find("td")
    $cells.removeClass("error")

    addErrorClass = ->
      $cells.addClass("error")
    # Need to have timeout or animation will not be replayable
    setTimeout(addErrorClass, 1)

  _updateDidSucceed: =>
    # no-op

  _updateObjectiveOnAPI: =>
    $.ajax(@_updateURL(), {
      data: @_asQueryParams(),
      type: "PATCH"
    }).fail(@_updateDidFail).done(@_updateDidSucceed)

  _updateURL: ->
    $("form")[0].action
```

As a workaround, I ended up using an :ajax tag on my test so I could use another web driver for ajax requests. EG:

``` ruby
# in spec_helper.rb

  config.around(:each, ajax: true) do |ex|
    original_driver = Capybara.javascript_driver
    Capybara.javascript_driver = :selenium
    ex.run
    Capybara.javascript_driver = original_driver
  end
```

**Comment by pokonski** [comment]
This still happens.

That way:
```coffee
  $.ajax(
    url: "/profiles"
    type: "DELETE"
    data:
      some_param: 1
```

does not send any params, while:

```coffee
  $.ajax(
    url: "/profiles"
    type: "POST"
    data:
      _method: "DELETE"
      some_param: 1
```

works.

**Comment by twalpole** [comment]
@pokonski what version of phantomjs are you using? It's a limitation of QtWebKit (and a bunch of older versions of browsers - not sure about current versions). This is because the HTTP spec was/is pretty ambiguous about whether or not delete requests should pass entity bodies or not, and whether or not servers should accept or ignore entity bodies from delete requests.  This may be supported in newer QtWebKit so maybe try phantomjs 2, but if you really insist on doing delete requests with params you're going to need to test it on all the browsers you want to support (especially mobile).  There's nothing poltergeist can do to "fix" this issue

**Comment by pokonski** [comment]
@twalpole thanks for the answer, I checked the RFC to realize the behavior is undefined. 

I'm on 1.9.0 version of PhantomJS.

**Comment by lvanhung** [comment]
Hi @jordanmaguire  
I got same problem.  
>I found that when using poltergeist the issue is that the request parameters don't come through. In the controller actions, the params hash doesn't include them. 

could you please tell me how to workaround the problem? my project is stable in production so I can't update code.

**Comment by jordanmaguire** [comment]
I included a workaround at the bottom of my original post - switch driver for that one test.

**Comment by lvanhung** [comment]
@jordanmaguire 
I see your comment. I want to workaround by a way which don't need to switch driver. I tried to research but seem it can't be. 
finally I have to use your way  switch from poltergeist to selenium driver.
thanks you so much.

**Comment by route** [comment]
You gotta be kidding 1.9.0
