### ISSUE TITLE
screenshot with selector not working

### ISSUE THREAD

**Issue by introvert** [teampoltergeist/poltergeist#533]
Hello,
I'm trying to use Poltergeist's save_screenshot function with selector option, but its not working. It won't give any error, just save the screenshot of the whole surface. I'm using the latest version of gem and phantom js 1.97. I'm calling:

    page.save_screenshot 'testing.png' , :selector => '#wrap'

Here's also the HTML that I've been trying to test:

	<!DOCTYPE html>
	<html>
	<head>
	  <title></title>
	</head>
	<style type="text/css">
	#wrap {
		height: 150px;
		width: 150px;
		background: red;
	}
	</style>
	<body>

	<div id="wrap">
	<h2>test</h2>
	</div>

	</body>
	</html>

Any ideas why this isn't working?

**Comment by Carpela** [comment]
Having exactly the same problem. 
Just seems to ignore the selector and takes a screenshot of the whole page.

**Comment by gutierlf** [comment]
I'm having the same problem too. Ignoring the selector.

**Comment by twalpole** [comment]
Trying this with poltergeist 1.8.1 paired with both phantomjs 1.9.8 and 2.0.0 this appears to work fine.  It's also something specifically tested for in poltergeists test suite.  If someone wants to provide a minimal example that reproduces this issue we can reopen
