### ISSUE TITLE
Not following Meta refresh

### ISSUE THREAD

**Issue by momolog** [teampoltergeist/poltergeist#537]
I am using RSpec with capybara 2.4.3 and poltergeist to do continuous integration tests. Now, when a page specifies a HTTP refresh like so:

    <html>
      <head>
        <meta content="0; URL=http://www.example.com:53957/otherpage" http-equiv="refresh">

the driver does not follow this refresh and stays on the wrong page (neither did webkit-capybara). 

Is this a bug? If not, how to deal with HTTP refreshes?

**Comment by twalpole** [comment]
What version of phantomjs are you using?  Have you tried it with a newer version?

**Comment by twalpole** [comment]
Closing for now, we can reopen if/when information is provided

**Comment by dgorodnichy** [comment]
I have the same issue. My phantomjs version is 2.1.1

**Comment by route** [comment]
That's anyway PhantomJS issue which is abandoned now
