### ISSUE TITLE
Cliver::Dependency::NotFound

### ISSUE THREAD

**Issue by paramaw** [teampoltergeist/poltergeist#539]
Hi Guys,

I'm getting this, when running rspec feature, using capybara, and rubinius 2.2.10, and phantomjs 1.9.7.1

`Cliver::Dependency::NotFound: Could not find an executable ["phantomjs"] on your path.`

Can you give me a suggestion on how to make this work?

Thanks

**Comment by dustinhansen** [comment]
What ended up being the solution to this? I'm having the same problem right now and can't get it working: http://stackoverflow.com/questions/30223743/poltergeist-1-6-0-phantomjs-2-0-0-cliverdependencynotfound

**Comment by yaauie** [comment]
@dustinhansen if you're having an issue with cliver's dependency detection, please file a bug on me at yaauie/cliver so I can help you resolve it. The README on that project also has a "GET OUT OF MY WAY" section that shows how to get Cliver out of your way.

**Comment by dustinhansen** [comment]
@yaauie Thanks. I seem to get a different error when I try to run my tests via terminal instead of Sublime and it's making me think it's a poltergeist issue or possibly user error:

Request failed to reach server, check DNS and/or server status (Capybara::Poltergeist::StatusFailError)

**Comment by tdubb** [comment]
I'm getting this error but only when I add
```
    Capybara.register_driver :poltergeist do |app|
      Capybara::Poltergeist::Driver.new(app, {debug: true})
    end

**Comment by yaauie** [comment]
@tdubb do you have phantomjs installed and available on your path? Cliver is just a tool to help us *find* the appropriate executable, and this error is telling you that we cannot find phantomjs.

> Linux/Mac:
>  - `which phantomjs`
>  - `echo $PATH`
> 
> Windows:
>  - `where phantomjs`
>  - `echo %PATH%`
 - `echo %PATHEXT%`

**Comment by tdubb** [comment]
The tests run fine with phantomjs without the above code.  I am spun up in a vagrant file and 
```
which phantomjs
```
 returns nothing while
```
    echo $PATH
```
returns

```
    /home/rails/.rvm/bin:/home/rails/.rvm/gems/ruby-2.1.5/bin:/home/rails/.rvm/gems/ruby-2.1.5@global/bin:/home/rails/.rvm/rubies/ruby-2.1.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/rails/.rvm/bin
```

I've included phantomjs and poltergeist via the gemfile

```
  gem 'poltergeist', '~> 1.5.1'
  gem 'phantomjs', :require => 'phantomjs/poltergeist'
```

**Comment by tdubb** [comment]
This code runs fine

![screen shot 2015-06-04 at 12 22 44 pm](https://cloud.githubusercontent.com/assets/3487685/7990135/78d3d9ac-0ab4-11e5-81c8-c28f300208e7.png)

I'd like to enable debugging though and that seems to be when the issue arrises.

**Comment by yaauie** [comment]
@tdubb: it looks like the phantomjs helper gem doesn't install phantomjs onto your path, instead opting to register it explicitly, so you'll need to do the same to explicitly point your newly-registered driver at the executable:
> ~~~ ruby
> Phantomjs.path # Force install on require
> Capybara.register_driver :poltergeist do |app|
>   Capybara::Poltergeist::Driver.new(app, :phantomjs => Phantomjs.path)
> end
> ~~~
> -- https://github.com/colszowka/phantomjs-gem/blob/master/lib/phantomjs/poltergeist.rb

**Comment by tdubb** [comment]
@yaauie Awesome, thanks so much for your quick and informative response!

**Comment by mjsommer** [comment]
@yaauie, worked for me as well. Thank you!

**Comment by ganbootyard** [comment]
@yaauie Fixed my problem in 2018.
