### ISSUE TITLE
PhantomJS crashes when clicking on link that open `window.open` multiple times

### ISSUE THREAD

**Issue by pkang** [teampoltergeist/poltergeist#546]
Test case is here: https://github.com/pkang/phantom-fail.

The test demonstrates a PhantomJS crash when clicking on a link that executes `window.open`. The crash doesn't happen the first time it's clicked, but on subsequent times.

The HTML that is served by the Sinatra app is `test.html`.

This was run with PhantomJS 1.9.8 on OS X 10.9.5.

**Comment by twalpole** [comment]
I can't replicate this with current poltergeist (1.8.0)  -  if a minimal reproducible test case with current poltergeist is presented we can reopen
