### ISSUE TITLE
Clicking button crashes phantomjs

### ISSUE THREAD

**Issue by mhenrixon** [teampoltergeist/poltergeist#548]
Hi,

Using master (to be able to accept some modals/dialogs) I am at the end of a long form trying to submit it by doing the following `session.find_by_id('finish').click`

This crashes phantomjs completely with the following message:

```
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/4A332119-B566-4D8E-B0CD-99716507AD0E.dmp
Capybara::Poltergeist::DeadClient: PhantomJS client died while processing {"name":"click","args":[10,0]}
from /Users/mhenrixon/.rvm/gems/ruby-2.1.3/bundler/gems/poltergeist-df101eb04d6a/lib/capybara/poltergeist/server.rb:33:in `send'
```

Any ideas why this is happening? Switching driver to selenium everything runs fine.

**Comment by tgjonestx** [comment]
I hit a similar issue on Linux. See [phantomjs/issues/13055](https://github.com/ariya/phantomjs/issues/13055)

**Comment by twalpole** [comment]
There have been a number of releases since this issue was reported. Does it happen with the latest poltergeist and phantomjs 2 ?  If so please provide a minimal test case and we can reopen
