### ISSUE TITLE
Stripe.js doesn't seem to load with Poltergeist?

### ISSUE THREAD

**Issue by bsodmike** [teampoltergeist/poltergeist#560]
Hi guys,

If I run this same step with Capybara (non-JS), it works fine, but with Poltergeist set to raise JS errors, I'm seeing this,

```
     Failure/Error: visit new_user_session_path
     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

       ReferenceError: Can't find variable: Stripe
       ReferenceError: Can't find variable: Stripe
           at http://127.0.0.1:63192/login:1
```

The button click's callback calls `Stripe.createToken()`.  Any ideas?

Thanks, M.

**Comment by PlugIN73** [comment]
Thank you!

**Comment by JohnBDonner** [comment]
Hey I know it's been some time on this issue, but the above solutions (using `phantomjs_options: ['--ignore-ssl-errors=yes', '--ssl-protocol=any']`) don't work for me with the following library versions: 
```
phantomjs | 2.1.1
poltergeist | 1.16.0
capybara | 2.15.1
```

I'm loading stripejs in my `<head>` like so: `<script src="https://js.stripe.com/v2/"></script>` and I'm calling the following from the asset pipeline:
```js
Stripe.setPublishableKey(...)
// => ReferenceError: Can't find variable: Stripe
```

Does anyone have any ideas about what could be the issue in 2018?

**Comment by amaranthrose** [comment]
@JohnBDonner did you find a solution maybe? If so, could you share it here? Thanks

**Comment by joshm1204** [comment]
Same issue! Any solution?
