### ISSUE TITLE
PDF data not included in page.source

### ISSUE THREAD

**Issue by tvon** [teampoltergeist/poltergeist#561]
This may be related to some pdf-specific comments in https://github.com/teampoltergeist/poltergeist/issues/282

If you have a controller that returns pdf data via (via `send_data` in this case), e.g. in this contrived example:

```ruby
  def pdf
    filepath = Rails.root.join('sample.pdf')
    data = File.open(filepath, 'rb') { |io| io.read }
    send_data data, filename: "sample.pdf", disposition: :inline, type: 'application/pdf'
  end
```

With `capybara-webkit` the `page.source` will contain the binary PDF data, with `poltergeist` `page.source` returns a minimal html document.

Note that it is not clear to me if this should be expected to work or not.  The closing of https://github.com/teampoltergeist/poltergeist/issues/299 indicates that the goal is HTML testing and not JSON (and I'd guess, not PDF either).  However, testing PDF content with capybara is fairly common so I can see the current implementation as a surprise to a lot of people (as it was to me).

**Comment by twalpole** [comment]
This is not expected to work in poltergeist, only html is supported for page source
