### ISSUE TITLE
Browser state set in Client initialization gets lost if PhantomJS client dies

### ISSUE THREAD

**Issue by bri3d** [teampoltergeist/poltergeist#564]
Issue as observed:

After a PhantomJS client dies and is automatically restarted, js_errors option gets lost (i.e., JS errors are reported as exceptions again).

This issue is because a few pieces of state, including js_errors, extensions, and debug, are set in the driver when the Browser is first created: 

https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/driver.rb#L26

However, the restart logic operates at the Browser/Client level: 

https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/browser.rb#L324

and

https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/client.rb#L13

and as this state is only maintained inside of the PhantomJS side once initialized, the browser and client don't know that they need to send the set_js_errors command to reset this state once a new PhantomJS process is spawned.

I suggest that the Browser object maintain these pieces of state on the Ruby side and, upon restart, should trigger these setters again.

I will try to write a pull request to solve this issue at the Browser level. If a different architecture (for example, making the Driver aware of restarts) is desired, let me know and I can try that approach instead.

**Comment by route** [comment]
Closed because of merged PR
