### ISSUE TITLE
phantom.args is deprecated and removed from PhantomJS 2.0

### ISSUE THREAD

**Issue by NameFILIP** [teampoltergeist/poltergeist#566]
The [phantom.args](http://phantomjs.org/api/phantom/property/args.html) is deprecated. It's recommended to use [system.args](http://phantomjs.org/api/system/property/args.html) which has a script name as the first argument, and the rest is like `phantom.args`.

In order to support PhantomJS 2.0 we have to change [this line](https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/client/main.coffee#L93) to use `system.args`.

**Comment by route** [comment]
Could you send a PR please?

**Comment by NameFILIP** [comment]
Created a pull-request for this - https://github.com/teampoltergeist/poltergeist/pull/567
