### ISSUE TITLE
'Timed out waiting for response' since Rails 4.2.0

### ISSUE THREAD

**Issue by zedtux** [teampoltergeist/poltergeist#571]
While all my tests are passing with Rails 4.1.9, upgrading (only) Rails to 4.2.0 make all my tests failing with the following error:

    Timed out waiting for response to {"name":"visit","args":["http://127.0.0.1:33290/"]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker. (Capybara::Poltergeist::TimeoutError)

I have tried to analyse which processes are running or the open ports in both cases but I can't figure out why it's not working.

**Comment by simi** [comment]
Is there any way how to reproduce this?

**Comment by zedtux** [comment]
I guess a fresh Rails application should be enough as I really encounter this issue just by upgrading Rails only.

**Comment by chuckd** [comment]
Check it's not asset compilation taking ages: try doing a

```sh
RAILS_ENV=test rake assets:precompile
```

before running your tests. Worked for us.

**Comment by zedtux** [comment]
@chuckd it was a clever trick but it doesn't fix my issue. I have also try to remove the `public/assets` folder in order to check if it is recreated while running my tests but it doesn't.

**Comment by route** [comment]
I barely think poltergeist is related

**Comment by zedtux** [comment]
I'm trying to reproduce this with fresh rails applications (Version 4.1.9 and 4.2.0).

**Comment by twalpole** [comment]
You may be running into a concurrency issue - rails 4.2 changed to not allowing concurrency in the default test environment setup (by injecting Rack::Lock into the middleware stack https://github.com/rails/rails/commit/112077c255879351edf4530791cc4bcc7bd4005b ), you can set config.allow_concurrency = true  in your test.rb to get back to the previous behavior although there are potential constant loading issues.

**Comment by zedtux** [comment]
Thank you @twalpole for the suggestion but it's not working :(

**Comment by route** [comment]
@zedtux what about barebone application? Does it work?

**Comment by zedtux** [comment]
@route I tried during half an hour to build a new Rails 4.1.9 and 4.2.0 application and wasn't able to reproduce the issue. It obviously need more time on order to integrates more and more the tools I'm using ... Like devise first.

I should try to find some time in my life to extend more and more this from-scratch-project in order to reproduce the bug.

**Comment by zedtux** [comment]
@chuckd you should be right. I have the capybara-screenshot gem installed and when it's failing with the timeout error, and I open the print screen, I see the home page but with a lot of missing CSS.

As I'm using Docker (and Fig) the command should be integrated in my `Dockerfile` so I'm trying this...

**Comment by zedtux** [comment]
Adding the following to the `env.rb` file make it working:

```ruby
Capybara.register_driver :poltergeist do |app|
  Capybara::Poltergeist::Driver.new(app, timeout: 10000)
end
```

It's taking quite long time on the first `visit` call and then working. I have tried with calling `rake assets:precompile` in my `Dockerfile` but it's not working. The assets are generated but it is still taking a long time before to start.

**Comment by zedtux** [comment]
So based on my previous comment, I guess we should close this issue and I should open a new one in the Rails project, right ?
(To try to determine what has changed which has increased the boot time)

**Comment by route** [comment]
Sounds correct to me, also try to run application in test env in order to debug or maybe play with `environment/test.rb` settings, because we have 4.2 application and it just works.

**Comment by zedtux** [comment]
I did it. I've tried the solution from @twalpole, I tried to disable the asset compilation and so on but nothing worked.
I have also copy/past the `environment/test.rb` file from a fresh rails 4.2 application.

Do you have an example of Rails 4.2 `environment/test.rb` file ?

**Comment by zedtux** [comment]
Well adding the following to the `config/environments/test.rb` make it no more waiting:

    config.assets.compile = false

But then all scenario fail with:

    No route matches [GET] "/assets/application.css" (ActionController::RoutingError)

So it's really about the assets...

**Comment by route** [comment]
My conf is standard. What if you precompile assets and set `compile = false`?

**Comment by zedtux** [comment]
> What if you precompile assets

As I'm using Docker (with Fig) I need to figure out how to do it. I will keep you informed.

**Comment by route** [comment]
@zedtux too much abstraction layers nowadays :)

**Comment by zedtux** [comment]
@route it's fine for me... RVM or Docker is the same : )
