### ISSUE TITLE
Ignores Traveling in Time with Timecop

### ISSUE THREAD

**Issue by dre-hh** [teampoltergeist/poltergeist#572]
Poltergeist ignores rubys time, when using poltergeist-1.5.1 with capybara-2.4.3

Reproduce steps: 
````ruby
visit root_path
page.evaluate_script('new Date();')
Timecop.travel(Time.current.advance(days: 1))
visit root_path
page.evaluate_script('new Date();')
````

`new Date();` will both times return the same Date, whereby ruby has traveled one day in Time.

**Comment by simi** [comment]
Timecop "mocks" Ruby DateTime, but you're evaluating JavaScript. You will need to use some JS library to handle JS Date mocks if you need that in your tests.

**Comment by dre-hh** [comment]
did so, used (and still using) `sinon`. However there is no posibility to advance time between two visits of a page. On the second visit the time gets reseted to normal, even if previosly set by `sinon`
