### ISSUE TITLE
window.top.location fails within iframe

### ISSUE THREAD

**Issue by fny** [teampoltergeist/poltergeist#573]
I have an iframe on a page in a Rails app, which has a button that is supposed to redirect the user to the root URL.

```html
<!-- /apples/new -->

<iframe src="/apple-tree.html"> <!-- ...which loads the following... -->
  <div id="home-button">Go Home</div>
  <script>
    $('#home-button').click(function() {
      window.top.location = '/';
    });
  </script>
</iframe>
```
The controller for the root url then redirects the user to a particular page.  This works as expected when running the page in a browser, but curiously fails when being run as a spec:

```ruby
expect(current_path).to eq('/apples/new') # => ✔
home_button = find('#home-button')
home_button.click # => {"status"=>"fail", "position"=>{"x"=>263.5, "y"=>456}}
```

At this point, I see the following in the test.log:

```
Started GET "/" for 127.0.0.1 at 2015-01-12 12:55:34 -0500
Processing by RootController#index as HTML
  Apple Exists (0.3ms)  SELECT  1 AS one FROM "apples"  WHERE "apples"."id" = $1 LIMIT 1  [["id", 1]]
Redirected to /dashboard
Completed 302 Found in 2ms (ActiveRecord: 0.3ms)
```

Despite that, poltergeist hasn't been redirected. It's as if using `window.top.location` from within the iframe had no effect.

```ruby
current_path # => /apples/new, should be /dashboard or at least /
```

Interestingly, executing the script manually seems to work without an issue, so perhaps the iframe is the culprit:

```ruby
execute_script %q[window.top.location = '/']
```

**Comment by twalpole** [comment]
What version of phantomjs and poltergeist was this with?  Is it still an issue with master poltergeist and phantomjs 2?

**Comment by twalpole** [comment]
Closing due to lack of response
