### ISSUE TITLE
PhantomJS 2.0 Landed

### ISSUE THREAD

**Issue by metaskills** [teampoltergeist/poltergeist#574]
So PhantomJS 2.0 has landed and I wondered if there have been any blocking issues with that version and Poltergeist. 

https://github.com/ariya/phantomjs/wiki/PhantomJS-2

**Comment by route** [comment]
Oh my, we have to run test suit on it and see what happens. Actually Aria recommended me to try to update to 2.0 because this can possibly get rid us of crashes we see in master now.

**Comment by futhr** [comment]
Hi, it would be nice with a release with da2e9035eb24b3264da1c4a47c3967efc3798212. 

For the moment using `add_development_dependency 'poltergeist'` does not work due to this (for brew people).

E.g.

```
brew update && brew upgrade
# run your awesome headless feature specs..
Cliver::Dependency::VersionMismatch:
       Could not find an executable 'phantomjs' that matched the requirements '~> 1.8', '>= 1.8.1'. Found versions were {"/usr/local/bin/phantomjs"=>"2.0.0"}.
```

**Comment by route** [comment]
In my test suit I see failures for http basic authentication, scrolling and file uploading for new PhantomJS

**Comment by PhilT** [comment]
Uploading is a known issue. There is a fix: https://github.com/ariya/phantomjs/issues/12506.

**Comment by DaveBlooman** [comment]
The Cliver dependency is causing us some issues.

**Comment by yaauie** [comment]
@DaveBlooman Cliver just helps us validate command-line dependencies, there is no issue with it.

As this issue states, PhantomJS 2.0 was *just* released, and there's some work we need to do to make sure Poltergeist works well with PhantomJS 2.0 (and continue to work well with 1.8.x and 1.9.x) before we can relax the dependency. Cliver helps us validate that you have a compatible version of PhantomJS installed so everything will work properly, and correctly prevents Poltergeist from selecting an incompatible version of PhantomJS.

Called out above are a couple of issues preventing the compatibility, and these issues all need to be resolved before we can relax the dependency. If you'd like to assist, we would gladly accept patches that get us closer to 2.x compatibility.

**Comment by gangster** [comment]
In the interim:

```code
brew install phantomjs192
```code

is working for me.

**Comment by route** [comment]
Just released new version, but like I said there are number of bugs in 2.0 and we have to wait until they're fixed

**Comment by mipearson** [comment]
Given that 1.9.x is irreparably crashy & buggy (oh, timeouts, I love thee), why is keeping 1.8/1.9 necessary at all once 2.0 is stable?

**Comment by route** [comment]
We'll drop support when tests are green I suppose.

**Comment by mipearson** [comment]
That's sensible. If I wanted to help out & fix bugs, would fixing breaking tests be a good way to start? Is there anybody co-ordinating this or triaging issues so that work isn't duplicated?

**Comment by route** [comment]
@mipearson Well, it's not poltergeist issues to be honest. I mean the tests were green, now after upgrading to 2.0 a few of them fail. So we could probably find a workaround for them, but not for all. Because such things as file uploading is not under Poltergeist's control.

**Comment by mipearson** [comment]
Reading the thread it looks like we will be waiting until the cows come home for that to get a fix. Would the click workaround that is in use with capybara-WebKit work?

Regards,

Michael Pearson
(sent from my phone)
