### ISSUE TITLE
Poltergeist keeps timing out

### ISSUE THREAD

**Issue by Vygo** [teampoltergeist/poltergeist#575]
Hey!
I am having problem trying to access couple of international urls. Poltergeist keeps constantly timing out even when I increased timeout to 180 seconds

http://www.huffingtonpost.kr/news/politics
http://www.huffingtonpost.co.uk/politics
Capybara::Poltergeist::TimeoutError: Capybara::Poltergeist::TimeoutError
	from /Users/bvygovsky/.rvm/gems/ruby-2.1.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/web_socket_server.rb:87:in `rescue in send'
	from /Users/bvygovsky/.rvm/gems/ruby-2.1.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/web_socket_server.rb:83:in `send'
	from /Users/bvygovsky/.rvm/gems/ruby-2.1.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/server.rb:33:in `send'
	from /Users/bvygovsky/.rvm/gems/ruby-2.1.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/browser.rb:316:in `command'
	from /Users/bvygovsky/.rvm/gems/ruby-2.1.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/browser.rb:31:in `visit'
	from /Users/bvygovsky/.rvm/gems/ruby-2.1.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/driver.rb:95:in `visit'
	from /Users/bvygovsky/.rvm/gems/ruby-2.1.0/gems/capybara-2.4.4/lib/capybara/session.rb:227:in `visit'
	from /Users/bvygovsky/.rvm/gems/ruby-2.1.0/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
	from (irb):17
	from /Users/bvygovsky/.rvm/rubies/ruby-2.1.0/bin/irb:11:in `<main>'

here is my poltergeist setup:
Capybara.register_driver :poltergeist do |app|
  Capybara::Poltergeist::Driver.new(app, {
    debug: true,
    js_errors: false,
    :timeout => 60,
    inspector: false,
    window_size: [1900, 1200],
    phantomjs_logger: open('/dev/null'),
     phantomjs_options: ['--load-images=no', '--ignore-ssl-errors=yes', '--ssl-protocol=any'],
  })
end

When I turned on debug on I see:

{"name":"visit","args":["http://www.huffingtonpost.co.uk/politics/"]}
{"name":"reset","args":[]}
{"response":true}
{"name":"find","args":["xpath","/html/body/*"]}
{"response":{"page_id":0,"ids":[]}}

**Comment by twalpole** [comment]
Is this still an issue with the latest poltergeist and phantomjs?  Is it waiting the timeout length you specify and then timing out? or is it just timing out early?

**Comment by twalpole** [comment]
Closing due to lack of response
