### ISSUE TITLE
PhantomJS 2 migration plan?

### ISSUE THREAD

**Issue by mipearson** [teampoltergeist/poltergeist#576]
Tried looking for this in an existing issue, couldn't find anything.

We're hoping against hope that PhantomJS 2 with the new Qt version corrects PhantomJS extremely frequent unpredictable timeouts, crashes, etc.

What's the plan to get Poltergeist using PhantomJS 2? Is there one? Is there a beta? How can we help?

**Comment by vbalazs** [comment]
But there was an existing issue, see #574 . Check the last comment. I don't know what those bugs are exactly.

**Comment by mipearson** [comment]
Ah, cheers. Closing.
