### ISSUE TITLE
Not loading jQuery

### ISSUE THREAD

**Issue by bias** [teampoltergeist/poltergeist#58]
I'm at a loss how to get my jQuery loaded into my cucumber test with poltergeist.

This is the type of error I'm seeing

```
      ReferenceError: Can't find variable: jQuery
```

Is `app/assets/javascripts/application.js` somehow not being loaded?

Someone else has a [similar issue posted on stackoverflow](http://stackoverflow.com/q/8792848/79168) with webkit, but they haven't had any answers and the question has been up for half a year.

**Comment by jayshepherd** [comment]
For me, dropping the `https:` in the cdn href made the difference. I was having this same issue on Master.

**Comment by rwehresmann** [comment]
I'm having the same issue here, and couldn't figure out how to solve yet. I'm loading jquery from `gem 'jquery-rails'`, it works fine when I run the server, but in my feature tests not.

**Comment by jarrett** [comment]
Short answer: try deleting `public/assets`.

Longer answer:

I got this error today calling `page.execute_script` from Capybara. I'm serving jQuery from the asset pipeline, not from a CDN. After some investigation, I found:
 
- Calling `sleep 30` before `page.execute_script` made no difference.
- `bundle update` made no difference.
- `save_and_open_page` showed that the JS was included from the `<head>` element.
- The jQuery code was included in compiled `public/assets/application-[hash].js`.
- However, **recent changes to custom JavaScript files were not included** in the compiled JS.

Based on that last observation, I guessed that there was a weird interaction between Poltergeist and precompiled assets. On this hunch, I deleted `public/assets`. That resolved the issue.

**Comment by jonatasrancan** [comment]
I faced the same problem

```
Failure/Error: click_on 'Login'

     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

       ReferenceError: Can't find variable: $
```

Only on the test environment.
And after some investigation, I found out that trying to pass a default value on a param, was causing the problem.

I had this function:
```js
drawInput: function(inputName, inputClass, value, rowIndex, columnIndex, readonly = false)
```

And the problem was the `readonly = false`. 
After changing it to `drawInput: function(inputName, inputClass, value, rowIndex, columnIndex, readonly)`, the tests started working without problem.

I know that default value on function params exist since  ES6/ES2015, but what I don't get is why that worked on development and on tests it failed.

**Comment by twalpole** [comment]
@jonatasrancan Because PhantomJS (used by Poltergeist) is basically equivalent to 7 year old version of Safari, and in dev mode you`re using a real browser. It’s time to move to a more modern Capybara driver.
