### ISSUE TITLE
rack_mock_session not present

### ISSUE THREAD

**Issue by kitofr** [teampoltergeist/poltergeist#584]
I just tired to incorporate poltergeist to a pretty old and huge rails app.
We've been using browser tests via capybara, selenium and Firefox. I however would like to use poltergeist but ran into some problems with cookie/session handling.

We try to set up cookies using:
```ruby
page.driver.browser.rack_mock_session.cookie_jar << Rack::Test::Cookie.new("#{cookie_name}=#{login_cookie.payload}", nil, '.lvh.me')
```
Which renders:

```
NoMethodError:
       undefined method `rack_mock_session' for #<Capybara::Poltergeist::Browser:0x007fbbe6ecaac8>
```

Using:

```
Using phantomjs 1.9.8.0
Using poltergeist 1.6.0

$ ruby -v
ruby 2.0.0p598 (2014-11-13 revision 48408) [x86_64-darwin14.0.0]
```
Any ideas?

**Comment by route** [comment]
Correct, because rack-test is another driver for capybara. See https://github.com/teampoltergeist/poltergeist#manipulating-cookies

**Comment by kitofr** [comment]
Thanks
