### ISSUE TITLE
Needs url whitelist option

### ISSUE THREAD

**Issue by mxrguspxrt** [teampoltergeist/poltergeist#588]
In most of the tests, I would be happy to block everything expect localhost.

**Comment by route** [comment]
PR is appriciated

**Comment by espen** [comment]
This is how this works in Capyabara Webkit:

    page.driver.block_unknown_urls
    page.driver.allow_url("custom.dev")

Will block all requests except localhost and custom.dev

**Comment by lpender** [comment]
:+1: this would be great

**Comment by konpyu** [comment]
+1

**Comment by tylerhunt** [comment]
In migrating from `capybara-webkit` where I was using the aforementioned `allow_url`/`block_unknown_urls` options, I agree this would be nice to have, and seems like an easier approach than the blacklist.

**Comment by hakunin** [comment]
+1, there is also https://github.com/teampoltergeist/poltergeist/issues/600 which talks about some urls not being really blacklisted

**Comment by twalpole** [comment]
PR #701 was merged in a few days ago which provides whitelist support -- The README needs an update sometime before the next release documenting its behavior, but the support is in master currently.
