### ISSUE TITLE
Spurious css selector failure with value=SecureRandom.hex

### ISSUE THREAD

**Issue by LarsWestergren** [teampoltergeist/poltergeist#589]
Versions:
poltergeist (1.5.1)
      capybara (~> 2.1)
      cliver (~> 0.3.1)
      multi_json (~> 1.0)
      websocket-driver (>= 0.2.0)
phantomjs-1.9.7-linux-x86_64

Given html:
 
```html
  <input id="token_1" name="token" type="hidden" value="6a64a06e39c36125ad1d" />
```

and rspec test like

```ruby
   expect(page).to have_css("#token_#{@model.id}[type=hidden][value=#{@model.token}]")
```

where the value is generated by SecureRandom.hex(10).

The test sometimes passes, and sometimes fails with 
Capybara::Poltergeist::InvalidSelector:
       The browser raised a syntax error while trying to evaluate css selector "#token_13[type=hidden][value=6176b25dae7e5de7f989]"

Changing the test to 

```ruby
expect(page).to have_xpath("//input[@id='token_#{@model.id}' and @type='hidden' and @value='#{@model.token}'] " )
```

Then it always passes.

**Comment by twalpole** [comment]
In CSS attribute values must be either strings or identifiers.  Unquoted values therefore must meet the definition of identifiers which cannot start with a digit, so when your token starts with a-f your selector is valid, when it starts with a digit it is not - you need to do

   expect(page).to have_css("#token_#{@model.id}[type=hidden][value='#{@model.token}']")

Which will then produce a valid selector with a string as the value like this

    #token_13[type=hidden][value='6176b25dae7e5de7f989']

**Comment by LarsWestergren** [comment]
Ah, thank you.
