### ISSUE TITLE
URI error when working with 'within_frame'

### ISSUE THREAD

**Issue by fuko-fabio** [teampoltergeist/poltergeist#591]
A following exception is thrown when trying to test something inside iframe

     Failure/Error: within_frame 'preview' do
     Capybara::Poltergeist::BrowserError:
       There was an error inside the PhantomJS portion of Poltergeist. This is probably a bug, so please report it. 
       
       URIError: URI error
       [object Object]
           at /home/npabian/.rvm/gems/jruby-1.7.10/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client/compiled/web_page.js:447
           at /home/npabian/.rvm/gems/jruby-1.7.10/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client/compiled/web_page.js:42
           at /home/npabian/.rvm/gems/jruby-1.7.10/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client/compiled/browser.js:219
           at /home/npabian/.rvm/gems/jruby-1.7.10/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client/compiled/browser.js:51
           at about:blank:35
           at /home/npabian/.rvm/gems/jruby-1.7.10/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client/compiled/connection.js:16
           at /home/npabian/.rvm/gems/jruby-1.7.10/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client/compiled/connection.js:1

ubuntu: 12.10
capybara: 2.4.4
poltergeist: 1.6.0
jruby: 1.7.10

**Comment by jlbenc** [comment]
Could you post example code that triggers the issue?

**Comment by fuko-fabio** [comment]
Example code:

    within '.my-class' do
        within_frame 'preview' do
          expect(page).to have_css('img[alt="Android QR Code"]')
          expect(page).to have_css('img[alt="iOS QR Code"]')
        end

        fill_in xxx, :with => 'yyy'
        click_button 'continue'
    end

Works like a charm on previous poltergeist versions.

**Comment by twalpole** [comment]
This error appears to have been thrown while attempting to call currentUrl which used to decode and encode window.location.href in v1.6.0 but was changed for 1.7.0 not to do that -  Does this error still occur with poltergeist 1.7+ ?

**Comment by twalpole** [comment]
Closing due to lack of response - we can reopen if more info is forthcoming
