### ISSUE TITLE
updated to PhantomJs 2.0, Cliver::Dependency::VersionMismatch 

### ISSUE THREAD

**Issue by madhuA14** [teampoltergeist/poltergeist#595]
Hi Team, 

I recently updated to phantomjs 2.0. results below error,

Could not find an executable 'phantomjs' that matched the requirements '~> 1.8', '>= 1.8.1'. Found versions were {"/usr/local/bin/phantomjs"=>"2.0.0", "/usr/bin/phantomjs"=>"2.0.0"}

previously I was working with phantomjs 1.9.8. which worked fine for me.

Does the recent release of phantomjs is not supported with my current setup ?
ruby 1.9.3p550
capybara (2.4.4)
poltergeist (1.5.1)

Thanks

**Comment by route** [comment]
Try to update poltergeist

**Comment by madhuA14** [comment]
Updated Poltergeist, no more errors, thanks.
