### ISSUE TITLE
phantomjs 2.0 cannot attach file with js: true

### ISSUE THREAD

**Issue by lewang** [teampoltergeist/poltergeist#596]
I originally opened this with capybara - https://github.com/jnicklas/capybara/issues/1494

---------

On Mac, I upgraded to phantomjs 2.0 using homebrew and immediately couldn't attach a file in test cases that required :js. It's working without js: true.

Downgrading to "phantomjs192" resolved the issue.

**Comment by route** [comment]
It's known issue see phantomjs issues

**Comment by pjg** [comment]
@route can you reference the phantomjs issue? I mean upgrading to poltergeist 2.0 makes no sense if you cannot attach a file in specs :/

**Comment by pjg** [comment]
Upstream issue: https://github.com/ariya/phantomjs/issues/12506
