### ISSUE TITLE
open_new_window has size 400x300 (PhantomJs default?)

### ISSUE THREAD

**Issue by IDragonfire** [teampoltergeist/poltergeist#597]
If I create a new window over `open_new_window`it has the size `400x300`.

My test code

```
@first = current_window
save_screenshot('old.png')
@test = open_new_window
switch_to_window @test
save_screenshot('new.png')
```

`old.png` has the correct default size (`1024x768`)
`new.png` has the size `400x300`

Resizing is not possible ...
`@test.resize_to(1024, 768)` is not supported, yet #534:
`Capybara::Driver::Base#resize_window_to (Capybara::NotSupportedByDriverError)`

```
poltergeist (1.6.0)
capybara (2.4.4)
cucumber (1.3.19)
cucumber-rails (1.4.2)
PanhtonJs (1.9.7)
```

**Comment by IDragonfire** [comment]
Is the default size missing?

https://github.com/teampoltergeist/poltergeist/blob/f826d135dd54a91f674992e2b5cab60a081e39c4/lib/capybara/poltergeist/client/browser.coffee#L206

**Comment by route** [comment]
I think the set view port should have been used, sounds like PhantomJS bug to me

**Comment by IDragonfire** [comment]
The question is why the initial window is working ...
Did you test your branch with the newest PhantomJs 2.0 release?
http://phantomjs.org/release-2.0.html

btw. I have no idea how to build a custom gem and install it on my machine ....

**Comment by route** [comment]
No I didn't test it yet. The answer is you don't have to build new gem, you can run test suits and experiment on fly or if you need to add changed poltergeist version to your project you can add it like this 'gem "poltergeist", path: "path to your dir"'

**Comment by twalpole** [comment]
This is fixed in master now
