### ISSUE TITLE
Blacklisting doesn't apply in all cases and is generally awkward to configure

### ISSUE THREAD

**Issue by christiannelson** [teampoltergeist/poltergeist#600]
Our cucumber javascript specs were starting to get slow, so I spent some time sleuthing out the reason. I found that if I commented out one line in our layout (the one that loads typekit), our cukes would run more than 3 time faster.

__With ```script src='//use.typekit.com/zza4vex.js'...```__
```
24 scenarios (24 passed)
257 steps (257 passed)
1m38.619s
cucumber  0.14s user 0.05s system 0% cpu 1:39.33 total
```

__Without ```script src='//use.typekit.com/zza4vex.js'...```__
```
24 scenarios (24 passed)
257 steps (257 passed)
0m28.191s
cucumber  0.14s user 0.04s system 0% cpu 28.898 total
```

This seemed like the perfect use case for `blacklist_urls`, so I gave it a try. To my surprise, it didn't make _any_ difference in the runtime. I traced all the way down into the client javascript that runs in poltergeist (`onResourceRequestedNative`) and checked which requests were being made using `page.driver.network_traffic`, and typekit looked like it was actually blacklisted.

I haven't gone any further in figuring out why blacklisting doesn't have the same effect as removing the script tag. I wanted to log my findings in case anyone else had a recommendation. I will keep digging.

/cc @kelvinst

PS: Using v1.6.0 of the gem and PhantomJS 1.9.8 on Mac OS X.

**Comment by christiannelson** [comment]
Our feature specs do a lot with multiple sessions and the blacklisted_urls don't appear to apply to sessions other than the default session. For us, this means that almost none of the requests are blacklisted. I have tried 2 strategies to set the blacklisted urls as often as possible, with hopes that it would work:

```ruby
Before do
  puts "**** Blacklisting..."
  if page.driver.browser.respond_to?(:url_blacklist)
    page.driver.browser.url_blacklist = %w(use.typekit.com)
  end
end
```

And...
```ruby
Capybara.register_driver :poltergeist do |app|
  Capybara::Poltergeist::Driver.new(app, debug: false, js_errors: true).tap do |driver|
    driver.browser.url_blacklist = %w(use.typekit.com)
  end
end
```

No dice. A majority of the typekit requests are still made and the suite remains slow.

I think there's room for significant improvement to blacklisting. I found this thread over at capaybara-webkit (https://github.com/thoughtbot/capybara-webkit/issues/717) and I really like where they landed.:

* By default, warn on every non-local request
* Allow blocking of all non-local requests with a single setting
* Whitelist remote requests that should be allowed, with support for wildcards

Bonus: by aligning with their solution, we're one step closer to a convention, one which could be codified by capybara itself at some point.

**Comment by kelvinst** [comment]
@christiannelson very nice investigations!

I am totally agreed with you about their conclusions, it would be awesome to have all of them.

And of course, the more we were aligned to they, better for us...

Maybe some time I'll get some time to a PR on some of them...

Much thanks to you!!!

**Comment by christiannelson** [comment]
@kelvinst Thanks! I'm still hacking on it and will share what I find if anything is interesting.

If there's any chance I can work on a solution, or one of our devs can, then we'll start a PR.

Thanks for introducing the feature in the first place... we're one step closer. :)

**Comment by twalpole** [comment]
Master branch now supports configuring default white/blacklist settings in the driver registration as well as wildcard support.  Those settings will be used by all new sessions created using that driver, and new windows opened will inherit the white/blacklist settings of the parent window.  I think this makes whitelist/blacklist usable and predictable enough to close this issue now.
