### ISSUE TITLE
Better way to `fill_in`?

### ISSUE THREAD

**Issue by lencioni** [teampoltergeist/poltergeist#609]
I am building an app with React.js, which likes to maintain a very tight control over the DOM. When using poltergeist to run my feature specs that `fill_in` fields that already have values, I'm noticing that the values I want to `fill_in` are appended to the value already in the field instead of replacing the value already in the field.

I had a similar problem with the Selenium driver and was able to fix it by sending backspace keys preceding the new field value. I have a PR here that implements `fill_options` with an option to use this backspace clearing behavior: https://github.com/jnicklas/capybara/pull/1498

However, I still have this problem with poltergeist and would like your help in figuring out how to best fix it. I've looked through the poltergeist code to see if I can implement the same solution, but I haven't figured out where I should do that.

It looks like the value just gets passed down to the browser (https://github.com/teampoltergeist/poltergeist/blob/f826d13/lib/capybara/poltergeist/node.rb#L76) which then just gets sent to the server (https://github.com/teampoltergeist/poltergeist/blob/f826d13/lib/capybara/poltergeist/browser.rb#L92 https://github.com/teampoltergeist/poltergeist/blob/f826d13/lib/capybara/poltergeist/browser.rb#L320) when then I think eventually makes it over into `::WebSocket::Driver` (https://github.com/faye/websocket-driver-ruby). I don't see where the field is ever cleared.

Can you help point me in the right direction? Also, what do you think about this idea?

**Comment by geminiyellow** [comment]
i have the same error. please help me, too.

**Comment by malrase** [comment]
@lencioni did you ever figure this out?

**Comment by lencioni** [comment]
@malrase fancy seeing you here!

> did you ever figure this out?

Nope.

**Comment by twalpole** [comment]
The order of clearing/focusing an input changed in a recent version of poltergeist (1.7.0 iirc) so this issue may be fixed in newer releases -  otherwise pull requests implementing the driver specific options (preferably matching what Capybara now has in the master branch - :clear option with different settings) would be considered.  It would basically involve modifying the set: methods in browser.coffee, agent.coffee,and Poltergeist::Node#set I think

**Comment by twalpole** [comment]
Closing due to lack of followup
