### ISSUE TITLE
Poltergeist does not follow redirect

### ISSUE THREAD

**Issue by razmig** [teampoltergeist/poltergeist#611]
Hi!

I have a simple form for reset password and submit, all the steps pass but the redirect after the submit
It is not a js redirect, just a backend redirect

When i follow the system log i can see the test is going to the correct route and then submit the form but it never navigates to the page it should get redirected to!

When i replace the default_driver in capybara from ':poltergeist' to ':selenium' it works like a charm

Any idea about this issue?

**Comment by route** [comment]
Hey @razmig I barely think Poltergeist and in this particular case PhantomJS cannot follow redirects since it's major feature. I cannot say more without an application. So if you need help create reproducible repo and I'll take a look.

**Comment by razmig** [comment]
Yes! you are absolutely right. After some investigation i have noticed that my problem appear when i use some helper functions, for example wait_for_js_to_load (i add a special class to the body when when my requirejs module is fully excuted). When i do this the browser wont redirect.

I still could not figuer out what causes this problem
