### ISSUE TITLE
Callback onResourceReceived

### ISSUE THREAD

**Issue by fist28** [teampoltergeist/poltergeist#614]
How can I use callback onResourceReceived in application? 
https://github.com/ariya/phantomjs/wiki/API-Reference-WebPage#webpage-onResourceReceived

I tired add script to `extensions` in phantomjs init but variable `page` is not defined.

Is it supported by poltergeist?

**Comment by twalpole** [comment]
From my reading of the code extensions don't have access to the objects which the phantomjs callbacks get fired on.
