### ISSUE TITLE
TypeError: 'undefined' is not an object (evaluating '_ref.length')

### ISSUE THREAD

**Issue by sentience** [teampoltergeist/poltergeist#616]
Seeing this intermittently in our test suite with Poltergeist 1.6.0 (also tested master) and PhantomJS 1.9.8 on CircleCI. Any tips on diagnosing the problem?

```
     Capybara::Poltergeist::BrowserError:
       There was an error inside the PhantomJS portion of Poltergeist. This is probably a bug, so please report it. 
       
       TypeError: 'undefined' is not an object (evaluating '_ref.length')
       [object Object]
           at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client/compiled/web_page.js:447
           at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client/compiled/web_page.js:42
           at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client/compiled/node.js:23
           at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client/compiled/node.js:48
           at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client/compiled/browser.js:302
           at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client/compiled/browser.js:320
           at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client/compiled/browser.js:51
           at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client/compiled/main.js:21
           at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client/compiled/connection.js:16
           at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client/compiled/connection.js:1
```

Here’s the debug output from Poltergeist at the point of failure: 

```
{"name":"find","args":["xpath",".//input[./@type = 'submit' or ./@type = 'reset' or ./@type = 'image' or ./@type = 'button'][((./@id = 'Sit the Test' or ./@value = 'Sit the Test') or ./@title = 'Sit the Test')] | .//input[./@type = 'image'][./@alt = 'Sit the Test'] | .//button[(((./@id = 'Sit the Test' or ./@value = 'Sit the Test') or normalize-space(string(.)) = 'Sit the Test') or ./@title = 'Sit the Test')] | .//input[./@type = 'image'][./@alt = 'Sit the Test']"]}
{"response":{"page_id":3,"ids":[2]}}
{"name":"visible","args":[3,2]}
{"response":true}
{"name":"disabled","args":[3,2]}
{"response":false}
{"name":"click","args":[3,2]}
{"error":{"name":"Poltergeist.BrowserError","args":["TypeError: 'undefined' is not an object (evaluating '_ref.length')","[object Object]\n    at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/bundler/gems/poltergeist-e3fc25919afb/lib/capybara/poltergeist/client/compiled/web_page.js:456\n    at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/bundler/gems/poltergeist-e3fc25919afb/lib/capybara/poltergeist/client/compiled/web_page.js:42\n    at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/bundler/gems/poltergeist-e3fc25919afb/lib/capybara/poltergeist/client/compiled/node.js:23\n    at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/bundler/gems/poltergeist-e3fc25919afb/lib/capybara/poltergeist/client/compiled/node.js:48\n    at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/bundler/gems/poltergeist-e3fc25919afb/lib/capybara/poltergeist/client/compiled/browser.js:302\n    at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/bundler/gems/poltergeist-e3fc25919afb/lib/capybara/poltergeist/client/compiled/browser.js:320\n    at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/bundler/gems/poltergeist-e3fc25919afb/lib/capybara/poltergeist/client/compiled/browser.js:51\n    at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/bundler/gems/poltergeist-e3fc25919afb/lib/capybara/poltergeist/client/compiled/main.js:21\n    at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/bundler/gems/poltergeist-e3fc25919afb/lib/capybara/poltergeist/client/compiled/connection.js:16\n    at /home/ubuntu/sitthetest/vendor/bundle/ruby/2.2.0/bundler/gems/poltergeist-e3fc25919afb/lib/capybara/poltergeist/client/compiled/connection.js:1"]}}
```

This certainly doesn’t seem like a recent issue. I’ve reproduced it on Poltergeist 1.5.1 and PhantomJS 1.9.7 as well.

**Comment by sentience** [comment]
This certainly doesn’t seem like a recent issue. I’ve reproduced it on Poltergeist 1.5.1 and PhantomJS 1.9.7 as well.

**Comment by route** [comment]
Can you show us a test case?

**Comment by sentience** [comment]
It’s a fairly complex app, so whittling it down to a test case would prove difficult. Is there anything else I can do? Is there some way to get more information out of PhantomJS, for example?

Do I understand correctly that the `TypeError: 'undefined' is not an object (evaluating '_ref.length')` is being generated by our application’s code and not anything internal to Poltergeist or PhantomJS? If so, I’d love to get a filename and line number or even a stack trace. Is there some way to get that out of PhantomJS?

**Comment by route** [comment]
It looks like poltergeist issue for me, so we need to track it down.

**Comment by sentience** [comment]
@route I’m not opposed to giving someone temporary access to our code and CI environment (where I’m currently able to reproduce the issue 100% reliably by running a single test). Contact me at kyank@avalanche.com.au if you’d like to set something up.

Failing that, I’ve got a long road ahead to whittle this big app down to a simple test case. Any advice or alternatives welcome.

**Comment by sentience** [comment]
Interestingly, running my app without stylesheets prevents the error from occurring. I’m continuing to try to simplify it to something approaching a test case.

**Comment by route** [comment]
Yes sure let's figure it out! I'll give you some direction for now and mail you a little bit later if you won't solve this. Basically everything works good in my opinion, the link is found and when you try to click it poltergeist sends command click to PhantomJS, `browser.mouse_event` function is called and then `node.mouseEvent` which calls `mouseEventTest` next, which is delegated in the end to `agent.mouseEventTest`. So I would start with cloning the poltergeist repo, then you can add this cloned repo to your app like this `gem 'poltergeist', path: 'where-it-is-locally'`, this will give you an ability to patch/debug poltergeist, then you can start debugging the result of that last function `mouseEventTest` in agent.coffee. Don't forget to recompile coffee to js with `rake compile`

**Comment by sentience** [comment]
@route Thanks! Will do.

**Comment by sentience** [comment]
@route We think we may have found the culprit. The page under test is similar to this: https://sitthetest.com/sitthetest/css-core The test is failing when it attempts to click the green “Sit the Test” button. Notice the blue UserVoice speech bubble in the bottom-right, which depending on the viewport size can overlap the button. Could that lead to the error we’re seeing here, do you think?

Here’s the screenshot that the test is generating on failure:

![Failure screenshot](https://dl.dropboxusercontent.com/u/555885/451901329632.png)

As you an see, the speech bubble is nowhere near that button, but perhaps it’s using a different viewport size for the screenshot than it is for the test?

I’m happy to continue working towards debugging the issue if you think it’s still worthwhile. Let me know.

**Comment by sentience** [comment]
OK, that screenshot was being generated by the capybara-screenshot gem. Here’s a screenshot generated by Poltergeist just before the button click:

![](https://dl.dropboxusercontent.com/u/555885/poltergeist_viewport.png)

The floating blue speech bubble isn’t visible for some reason, but if I set my desktop browser to a viewport of that size, it definitely sits right over the button. What do you think? Mystery solved? Still worth debugging if only to handle issues like this better?

**Comment by route** [comment]
We have an ability in Poltergeist to catch overlapping elements and the error is different for this sort of issues.. It still looks for me like poltergeist issue, we just have to find why, what and when it's happening :)

**Comment by sentience** [comment]
@route OK, I’ll get to work on some debugging tomorrow. In the meantime, however, we’ve found that both disabling the UserVoice widget and increasing the Poltergeist window size resolve the test failure completely in our case.

**Comment by route** [comment]
Sounds reasonable to me since we see cut off button, but still weird :)

**Comment by sentience** [comment]
OK, I’ve done some debugging and I can confirm the problem is definitely the click coordinates mapping to an overlapping element (the Uservoice widget in this case).

Looking at [`mouseEventTest` in agent.coffee](https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/client/agent.coffee#L310-L324):

```coffeescript
  mouseEventTest: (x, y) ->
    frameOffset = this.frameOffset()

    x -= frameOffset.left
    y -= frameOffset.top

    el = origEl = document.elementFromPoint(x, y)

    while el
      if el == @element
        return { status: 'success' }
      else
        el = el.parentNode

    { status: 'failure', selector: origEl && this.getSelector(origEl) }
```

The method is called with coordinates `973`, `740.5`. The `frameOffset` is (0,0), so it calls `document.elementFromPoint(973. 740.5)`. This returns an `SVGSVGElement`, rather than the expected `HTMLInputElement` (which is `@element`). The only SVG on the entire page is that Uservocie widget, so that’s clearly what it’s finding.

The `while` loop then walks the parent element chain from the `SVGSVGEleemnt` looking for the `HTMLInputElement`. It gets an `HTMLDivElement`, an `HTMLBodyElement`, an `HTMLHtmlElement`, an `HTMLDocument`, and finally null. When it then tries to access `el.parentNode` when `el` is `null`, that’s what triggers the error.

So, I’d say that whatever mechanism is supposed to detect when an overlapping element has interfered with a click is not doing the trick here. The loop should probably bail out cleanly if `el` is `null`, allowing the failure status to be returned on the final line of this method.

**Comment by twalpole** [comment]
I believe this error is actually from getSelector where the code attempts to iterate through the classList of the overlapping element.  PhantomJS < 2 doesn't support classList on SVG elements so it returns undefined -- fixing

**Comment by twalpole** [comment]
Should be fixed via PR #682

**Comment by nodejquery11** [comment]
Hi Guys,
Am also receiving same error while running then test cases. My error is 

`Safari 10.1.0 (Mac OS X 10.11.6) ERROR TypeError: undefined is not an object (evaluating '_ref.input.onChange') at 
webpack:///src/components/customIncrementDecrementButton/CustomIncrementDecrementButton.js:53:21 <- /Users/vikas.bose/canadasalesapp/CanadaSalesApp/src/components/customIncrementDecrementButton/CustomIncrementDecrementButton.test.js:44179

Chrome 57.0.2987 (Mac OS X 10.11.6) ERROR Uncaught TypeError: Cannot read property 'onChange' of undefined at webpack:///src/components/customIncrementDecrementButton/CustomIncrementDecrementButton.js:53:21 <- /Users/vikas.bose/canadasalesapp/CanadaSalesApp/src/components/customIncrementDecrementButton/CustomIncrementDecrementButton.test.js:44179

Am trying to find the resolution and read lots of block but issue / error not been resolve. Please help me and it is urgent as well.

Thanks

**Comment by twalpole** [comment]
@nodejquery11 That error is coming from code (as evidenced by the error location) in your project, not in Poltergeist - You've either got an error in your code/libraries, or you're using ES6 features (which the latest released PhantomJS doesn't support) without transpiling/polyfilling them to <=ES5
