### ISSUE TITLE
Hidden elements are being 'shown'

### ISSUE THREAD

**Issue by amitz** [teampoltergeist/poltergeist#618]
I'm using Capybara in conjunction with Poltergeist, and I have a problem which I'm not totally sure where it oriented from - Capybara or Poltergeist. I'm using the following Capybara query:

```ruby
all(:xpath, '//table[@class="myClass"]//tr)
```

My table contains two entries:

    <tr class="myClass" style="visibility: hidden;">
    <tr class="myClass">

The code above is a bit simplified compared to the original, but It serves the example. When running Capybara against Chrome or Firefox, the query results one element (the non-hidden element). When running the same code against Poltergeist, I'm getting both elements. I tried to play around with explicitly telling Capybara to ignore hidden elements, but I'm still getting the hidden one. Is this Poltergesit 'showing' hidden elements? or Capybara problem? I'm using the latest Capybara (2.4.4) and Poltergesit (1.6.0).

**Comment by twalpole** [comment]
This is because Poltergeist doesn't check the visibility style property when determining whether an element is visible on the page currently

**Comment by twalpole** [comment]
Should have been fixed by PR #675

**Comment by amitz** [comment]
Thank you very much @twalpole. I will give it a try :)
