### ISSUE TITLE
Can't connect to HTTPS sites on 10.10.3 (Yosemite)

### ISSUE THREAD

**Issue by monfresh** [teampoltergeist/poltergeist#619]
Hi. I'm not sure what the underlying issue is, and what is causing it, but it seems like changes in 10.10.3 have affected browser integration tools like Poltergeist, PhantomJS(?), and Qt.

In my project, I have an RSpec test that [checks that Google Translate is translating the page](https://github.com/codeforamerica/ohana-web-search/blob/master/spec/features/general/translate_spec.rb). This test passes on OS X 10.10.2 and on Linux (Travis and Vagrant running Ubuntu 14.04), but upgrading to OS X 10.10.3 causes the test to fail, with no other changes.

I inspected the network traffic in one of the specs by adding this line:
```ruby
puts page.driver.network_traffic.map { |t| [t.response_parts.last.status, t.response_parts.last.url] }
```
I noticed that all of the calls made during the tests are over HTTP, except for two calls over HTTPS to `https://translate.googleapis.com/translate_static/css/translateelement.css` and `https://translate.googleapis.com/translate_static/js/element/main.js`. All of the HTTP calls have a status associated with them, either `200` or `304`. However, both of the HTTPS calls have no status at all. Here is an excerpt from the output:
```
304
http://www.lvh.me:62028/assets/util/geolocation/geolocate-action.js
200
http://translate.google.com/translate_a/element.js?cb=GoogleTranslate.googleTranslateElementInit
200
http://fonts.gstatic.com/s/quattrocentosans/v8/efd6FGWWGX5Z3ztwLBrG9c2kigAIKUS7C8wDj9A45hI.ttf
200
http://fonts.gstatic.com/s/quattrocentosans/v8/tXSgPxDl7Lk8Zr_5qX8FIWAK5Gcw6LbjBo2-NRTaHPD3rGVtsTkPsbDajuO5ueQw.ttf
200
http://www.lvh.me:62028/assets/fontawesome-webfont.ttf?v=4.3.0

https://translate.googleapis.com/translate_static/css/translateelement.css

https://translate.googleapis.com/translate_static/js/element/main.js
```
On the capybara-webkit repo, someone mentioned that using [protocol agnostic URLs](https://github.com/thoughtbot/capybara-webkit/issues/755) fixed the issue for them. Unfortunately, those HTTPS calls are not instantiated directly from my app, so I can't change them.

Any ideas what might be going on here and how to fix it? Is this a PhantomJS issue?

**Comment by monfresh** [comment]
To prove that this is an HTTPS issue, I changed my protocol agnostic font urls from `//fonts.googleapis.com/css?family=Libre+Baskerville:400,700` to `https://fonts.googleapis.com/css?family=Libre+Baskerville:400,700`, and when I run the test again, the network requests to the HTTPS fonts URLs now have a status of nil whereas before, they were returning `200`.

**Comment by monfresh** [comment]
Here are some PhantomJS issues that might possibly be related: https://github.com/ariya/phantomjs/issues/12790
https://github.com/ariya/phantomjs/issues/12746

Is there any way to check for SSL handshake errors in Poltergeist?

**Comment by monfresh** [comment]
I just noticed the `phantom_js` options! Adding `phantomjs_options: ['--ignore-ssl-errors=yes']` fixed the issue. Feel free to close this if that is the expected thing to do in this case.

**Comment by bsodmike** [comment]
@monfresh I also recall getting caught out on that about a year ago; that is indeed the 'trick'.  This issue should be closed.
