### ISSUE TITLE
Timeout on go_back

### ISSUE THREAD

**Issue by jvanbaarsen** [teampoltergeist/poltergeist#624]
I'm currently working on upgrading rspec to rspec 3 in the GitLab project.

I'm now running into a problem that one of our test cases is getting a timeout on the `go_back` and `go_forward` calls. I tried increasing the timeout to over 50, but it did not help.

The testcase is attached here: 
**Feature steps:** https://gist.github.com/1b9482e6cb63eec4a22c
**Feature file:** https://gist.github.com/535caade59f816883068

The problem seems to be in the first go back step: `Then I go back in history`. The error I get on that call is:

```
Timed out waiting for response to {"name":"go_forward","args":[]}.
It's possible that this happened because something took a very long time (for example a page load was slow). 

If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). 

If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker.

 /Users/jeroen/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/web_socket_server.rb:87:in `rescue in send'
```

I enabled `debug: true` and it looks like the `go_back` is actually fired, and is doing what it is suppose to do, but then somehow it times out:

``` json
{"name":"go_back","args":[]}
{"name":"current_url","args":[]}
{"response":"http://127.0.0.1:55616/keyshawn.armstrong1/gitlabhq/blob/master/.gitignore#L1-2"}
{"name":"body","args":[]}
```

I tried this on the browser as well, it's not a slow request.

I hope I provided enough information, if not, please let me know! I'll be glad to provide more! I tried creating a reproduction PR for you, but I got stuck in that process.

**Comment by twalpole** [comment]
Is this still an issue?

**Comment by jvanbaarsen** [comment]
@twalpole Not sure, lets close it and see if we need to reopen it later.

**Comment by shepmaster** [comment]
I'm seeing something similar, but switching from Capybara's `page.go_back` to `page.execute_script('window.history.go(-1);')` causes the timeout to not occur.

Is there a difference in implementation of Poltergeists `go_back` that I could further investigate?

**Comment by twalpole** [comment]
@shepmaster  Capybara's `go_back` with the Poltergeist driver boils down to calling PhantomJS WebPage#go_back http://phantomjs.org/api/webpage/method/go-back.html.  execute_script shouldn't timeout unless the JS triggers a modal dialog.  If it is in any other case and you can produce a reproducible example please open a new issue.

**Comment by twalpole** [comment]
Nevermind I see the issue -- on a call to go_back Poltergeist is waiting for the page to load, however if there has been a history.pushState no page load occurs, so it times out waiting for that.

**Comment by shepmaster** [comment]
Wow, thank you for the amazing response, @twalpole! And thank you for all the work you do here and in Capybara; I see your name quite frequently and it always fills me with hope when I see you are working on something relevant to my interests 😉

**Comment by twalpole** [comment]
@shepmaster You're welcome -- I believe PR #872 will fix the issue - tests running currently

**Comment by twalpole** [comment]
Fixed via PR #872

**Comment by shepmaster** [comment]
FWIW, I pulled master and switched back to `page.go_{back, forward}` and my tests continued to pass. Thank you!

**Comment by twalpole** [comment]
@shepmaster Good to hear.
