### ISSUE TITLE
find() not finding hidden elements

### ISSUE THREAD

**Issue by karlhe** [teampoltergeist/poltergeist#628]
After upgrading to poltergeist 1.6.0,  selectors which were previously targeting elements with `display: none` stopped finding the element correctly. Downgrading to 1.5.1 works.

I have `Capybara.ignore_hidden_elements = true` set as the default, and I'm using the selector like this:

```ruby
find('body > header > nav .management', {:visible => false})
```
Setting `Capybara.ignore_hidden_elements = false` causes it to work fine, so either the `:visible` option to `find` is not working properly or something fishy is going on with `ignore_hidden_elements`

**Comment by twalpole** [comment]
Can you produce a test case for this?

**Comment by twalpole** [comment]
Closing due to lack of response, we can reopen if a test case is provided
