### ISSUE TITLE
No way to access inner_html on poltergeist node

### ISSUE THREAD

**Issue by githorse** [teampoltergeist/poltergeist#629]
When running an rspec test with `js: false`, I can do this:

```
[3] pry(#<RSpec::ExampleGroups::etc>)> page.first("li.question").native
<li id="1" class="question"><div class="inner">etc</div></li>
```
I can quickly see the content of the node I'm dealing with. I find myself doing this all the time. Problem is, when running with Poltergeist and  `js: true`, I get:

```
[2] pry(#<RSpec::ExampleGroups::etc>)> page.first("li.question").native
#<Capybara::Poltergeist::Node tag="li">
```

I get the `<Capybara::Poltergeist::Node>` object instead of the html. I can't figure out how to query that object to give me its html -- `.native`, `.html`, `.inner_html`, etc. do not work, and none of the other instance methods look promising. Obviously the Poltergeist node must actually have some representation of the html it contains, but it doesn't seem to want to give it up.

Is there some way to see the html of a Poltergeist node?

**Comment by wflanagan** [comment]
I have this same issue.

**Comment by chamnap** [comment]
I face the same issue.

**Comment by twalpole** [comment]
page.first("li.question")['outerHTML'] should now return the elements html in the master branch of poltergeist
