### ISSUE TITLE
NTLM Auth Support?

### ISSUE THREAD

**Issue by itslittlejohn** [teampoltergeist/poltergeist#634]
It seems from this [thread](https://github.com/ariya/phantomjs/issues/11037) that there is some basic support for NTLM auth in PhantomJS 2.0. Is there a way to get this working via poltergeist?

**Comment by yaauie** [comment]
We'd gladly work with you to get a pull-request merged in :)

**Comment by itslittlejohn** [comment]
In that case, I'll look into it.

**Comment by twalpole** [comment]
Closing due to lack of follow-up
