### ISSUE TITLE
Can't click through Stripe OAuth flow.

### ISSUE THREAD

**Issue by xaviershay** [teampoltergeist/poltergeist#638]
The following Capybara successfully navigates through a Stripe OAuth development connect flow when using selenium and Firefox:

```
click_link "Connect with Stripe"
click_link "Skip this account form"
```

It does not work with poltergeist however. After the second click, the current page still shows the page containing "Skip this account form". I confirmed this with both a screenshot and `puts page.body`. I also tried doing `find` + `trigger("click")` with the same result.

This worked in the past (maybe within a year?) without changing poltergeist version, so I suspect something changed on Stripe's end. (Or I upgraded to Yosemite? I don't run these specs often.)

Sorry for site-specific issue with lack of a minimal repro, but I thought it would be useful to document a discrepancy between selenium and poltergeist, and also catch any googlers who are having the same issue.

**Comment by twalpole** [comment]
Is this still an issue with poltergeist master branch?? Also - what version of phantomjs are you seeing this with?

**Comment by twalpole** [comment]
Closing due to lack of needed info -- if more info is provided we can reopen

**Comment by xaviershay** [comment]
sorry for lack of response - I will try to repro again and reopen if still a problem.
