### ISSUE TITLE
specs fail - driver is missing `window_size`, other methods

### ISSUE THREAD

**Issue by kdeberk** [teampoltergeist/poltergeist#640]
When I run `bundle exec rake`, then several specs will fail. These specs are all located in the capybara gem.

```text
rspec /home/dberk/.rvm/gems/ruby-2.1.2@axini/gems/capybara-2.4.4/lib/capybara/spec/session/window/window_spec.rb:88 # Capybara::Session Poltergeist Capybara::Window #size should return size of whole window
rspec /home/dberk/.rvm/gems/ruby-2.1.2@axini/gems/capybara-2.4.4/lib/capybara/spec/session/window/window_spec.rb:92 # Capybara::Session Poltergeist Capybara::Window #size should switch to original window if invoked not for current window
rspec /home/dberk/.rvm/gems/ruby-2.1.2@axini/gems/capybara-2.4.4/lib/capybara/spec/session/window/window_spec.rb:106 # Capybara::Session Poltergeist Capybara::Window #resize_to should be able to resize window
rspec /home/dberk/.rvm/gems/ruby-2.1.2@axini/gems/capybara-2.4.4/lib/capybara/spec/session/window/window_spec.rb:112 # Capybara::Session Poltergeist Capybara::Window #resize_to should switch to original window if invoked not for current window
rspec /home/dberk/.rvm/gems/ruby-2.1.2@axini/gems/capybara-2.4.4/lib/capybara/spec/session/window/window_spec.rb:123 # Capybara::Session Poltergeist Capybara::Window #maximize should be able to maximize window
rspec /home/dberk/.rvm/gems/ruby-2.1.2@axini/gems/capybara-2.4.4/lib/capybara/spec/session/window/window_spec.rb:133 # Capybara::Session Poltergeist Capybara::Window #maximize should switch to original window if invoked not for current window
```

The direct cause seems to be that the Poltergeist driver does not implement `window_size`, `resize_to` and `maximize`, as an example of a failing spec:
```ruby
expect(@session.current_window.size)
    .to eq @session.evaluate_script("[window.outerWidth, window.outerHeight];")
```
`@session.current_window` is a Capybara::Window instance, which redirects the call `size` to `Capybara::Poltergeist::Driver#window_size(handle)` which does not appear to be implemented.

What I think is most baffling is that these specs are passing on Travis, but I also notice that Travis only executes 946 specs, while my build executes 1008:

travis:
```text
946 examples, 0 failures, 1 pending
```

my local build (ruby 2.1.2p95):
```text
1008 examples, 6 failures, 1 pending
```

**Comment by route** [comment]
That's right! PhantomJS has difficulties with resizing that's why we don't support it for now and skip those specs on CI. It is handy to see if people's PRs are really failing or failing because of those 6 failures.

**Comment by kdeberk** [comment]
Okay, fair enough. but since I didn't see a mention of this in the README or in the CONTRIBUTIONS file, it took me quite a while to investigate what was going on.

**Comment by route** [comment]
I just hope we'll make it compatible soon :)
