### ISSUE TITLE
Header / Footer in PDF

### ISSUE THREAD

**Issue by jozefvaclavik** [teampoltergeist/poltergeist#645]
Hey guys,

I'm not sure how much is this a bug, or maybe I'm just missing something. In README in the section about screenshots and export to PDF there is a [link](https://github.com/ariya/phantomjs/wiki/API-Reference-WebPage#webpage-paperSize) how to set up paperSize..

The problem I'm hitting is that I'm unable to set up header/footer on a page (page content get shifted based on height, but no header/footer content is displayed). `contents` requires `phantom.callback` with javascript function. Capybara gives page variable, but I don't think I can access directly phantom object. Whatever I try I cant make it work. Any ideas?

I don't have deep understanding of capybara and poltergeist, but if you would send me right direction I could work on a PR.

Jozef

**Comment by twalpole** [comment]
the `contents` setting takes a JS function which can't be passed via JSON from the ruby to JS portion of the app, so it's not possible to use.
