### ISSUE TITLE
CSS calc function not working correctly 

### ISSUE THREAD

**Issue by passa763** [teampoltergeist/poltergeist#646]
I have a couple `calc(100% - 60px)` functions in my CSS attached to parent `div`s and works fine in my regular browser. However when I run my tests, they always fail do to all my child elements inside this div not being positioned correctly.

When I remove these `calc`s, and leave it at just `100%`, everything work in the tests.

Spent a great deal of time trying to find a solution and came up empty.

**Comment by yaauie** [comment]
You likely need to follow up with the PhantomJS project; Poltergeist is just an adapter between the PhantomJS VM and Capybara, and doesn't handle any of the rendering itself.

**Comment by passa763** [comment]
Ahh ok thank you
