### ISSUE TITLE
Capybara::Poltergeist::TimeoutError

### ISSUE THREAD

**Issue by jeremyongws** [teampoltergeist/poltergeist#648]
Have tried setting timeout to 300 and above but still not helping.

Keeps saying that the loading speed is slow but checked that i have stable internet

Running it headless (phantomjs) and windows 7, with ruby v2.2.0

Any help would be greatly appreciated on how to solve this issue./

```
gems/2.2.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/web_socket_server.rb:87:in `rescue in send': Timed out waiting for response to {"name":"visit","args":["http://websta.me/tag/vapormalaysia"]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker. (Capybara::Poltergeist::TimeoutError)
```

**Comment by timimsms** [comment]
I'm also experiencing this on OS X Yosemite after recently upgrading Xcode 7.0. Was working fine prior to the upgrade.

**Comment by timimsms** [comment]
Just went through `brew` dependencies to get a clear `brew doctor`:

````bash
brew unlink qt5
brew unlink qt
brew uninstall qt
brew update
brew install qt5
brew link --force qt5
````

While this cleaned up `brew`, I'm still getting failed tests. Trying a restart now :hourglass_flowing_sand:

**Comment by timimsms** [comment]
Restart didn't work. Tried updating command-line tools + another restart - still having test fail.

**Comment by jeremyongws** [comment]
Hey, I'm still getting this error a lot as well. Not very sure what to do no

**Comment by twalpole** [comment]
Is this still an issue (try master branch) - If so is it only with specific urls or with all urls?

**Comment by twalpole** [comment]
Closing due to lack of response, we can reopen if/when more info is provided

**Comment by Loschcode** [comment]
I've the same problem.
