### ISSUE TITLE
can not set cookies 

### ISSUE THREAD

**Issue by dieuit07** [teampoltergeist/poltergeist#651]
Hi everyone, I have 5 scenario, and must be login first. So I write a Background to do that. But I don't want each Scenario must doing some stub like visit page fill in user/pass, submit. It takes a lot delay time.
So I think: Maybe I just login the first time and set cookies for after to prevent delay time.

Here is some code:
```
step 'login with :params' do |params|
  if $cookie.nil?
    user = params.split('/')[0]
    pass = params.split('/')[1]
    visit '/admin'
    fill_in 'user[email]',  with: user, match: :first
    fill_in 'user[password]', with: pass, match: :first
    click_button("Login")
    $cookie = page.driver.cookies["_user_session"]
  else
    page.driver.set_cookie($cookie.name, $cookie.value, options = {
       "domain"=> $cookie.domain,
       "name"=> $cookie.name,
       "path"=> $cookie.path
      })
  end
```
$cookies in second block (else block) return:
```
#<Capybara::Poltergeist::Cookie:0x00000004577958
 @attributes=
  {"domain"=>"pl.ca",
   "httponly"=>true,
   "name"=>"_user_session",
   "path"=>"/",
   "secure"=>false,
   "value"=>
    "ZC9Wai9hWXphRFFKVVA1enhPSmZEY1kxN0srbFlTdGZKbmNDcm5kL3pISW5oVGV3WXhodHRCdlIvbG9pZEI5NmJNT2FmTmV4YmVhREVQdWNpT0xxY3d6ZHdReU5iZUtMK0dSdkNPY3JVWHJXSHE4dlVkVjd1SS9qSi9HSEM3K2RHWXIzVGlxU0diQU5INFVwS0doc2lNZDQ4VmVRT3JDTUE3Vm84Y2g1R1pyMWZPRllxQ3hPOThZSjdEY1NramN6ZTBqd3ZCM3dYUjRXMVRIOHhlS0JlR1ZGekZ3OUpMR0lDcDR4UXFjUmVINkRzTlF0RUNIUkRCS2x2ZzRVV09tTkdqcFByandvcDhHaC9TREdKL2hrbU5aNWhlTkpqWGlwbURaNzJEOGJ6M1AvS1E0dkxKWVF5aHE5Mi8xLyt3akdLdGw2WkRNN2VIdGVUNDkrcG1Ic0JBPT0tLTc3MG4zYm9CU2owMGJTTEhRczQxUXc9PQ%3D%3D--c49e1ee850a1e40af66b65d518480b75b3ba11ab"}>
```
And when I debug after set cookie
```
page.driver.cookies 
#=> {}
```

**Comment by twalpole** [comment]
page.driver.cookies returns the cookies for the current page, while set_cookie lets you set them for any domain.  Since you haven't yet visited a page right after calling set_cookie you aren't on the domain you set the cookie for and therefore page.driver.cookies will be empty.  Once you visit a page matching the domain you set the cookie for then the cookies should be accessible
