### ISSUE TITLE
Continue from debug pause when not running from TTY

### ISSUE THREAD

**Issue by Nuru** [teampoltergeist/poltergeist#654]
Currently to do remote debugging, you add `page.driver.debug` to the test and at that point the browser ([should](https://github.com/teampoltergeist/poltergeist/issues/579)) open and the test pauses with the message "Press enter to continue." This is a problem when you are not running the tests from a terminal (e.g. when running them using RubyMine's RSpec runner), because there's no way to feed a newline into the program and it hangs forever.

**Comment by route** [comment]
Thanks your commits are in master now
