### ISSUE TITLE
Is there a way to update header for all HTTP requests made within Poltergeist?

### ISSUE THREAD

**Issue by cielo** [teampoltergeist/poltergeist#658]
Hi,

The website that I am writing UI integration tests for is using Kerberos authentication. This means that all HTTP request to the website requires authentication token. 

So I have a block like this in spec_helper.rb.

```Ruby
config.before :each do
  @kerberos_token = SomeRandomLibrary.getKerberosToken(Capybara.app_host)
  page.driver.add_headers("Authorization" => "Negotiate #{@kerberos_token}")
end
```

By having this, the first request to the remote website is successfully handled. However, subsequent requests (getting CSS files, JS files, and making AJAX requests) made from PhantomJS headless browser all get rejected, because same ```@kerberos_token``` value gets used in the header and it does not change over the course of single test. 

The website throws an error if same token gets used because it thinks that requests are 'replay attack'.

Is there a way to configure/override/intercept all HTTP calls? So that I can assign new kerberos token for all of them?

**Comment by twalpole** [comment]
There's nothing built-in to poltergeist - however you could use a proxy to potentially add headers to requests -- Take a look at the puffing-billy gem - it may allow you to do this (although I don't think it allows for modifying requests last time I looked, just setting responses), or at least give you direction on how you can configure poltergeist for a proxy
