### ISSUE TITLE
Can not set input[type=email] field

### ISSUE THREAD

**Issue by geminiyellow** [teampoltergeist/poltergeist#666]
i use `cucmber + capybara + poltergeist` for my `react` project.
everythink work well but it can not reset input to empty, and `SELENIUM` is ok.

so i think may be i can get some help from `poltergeist`.

poltergeist -v : 1.7
phantomjs -v : 1.9.8

i write my step like this:
```
When /^I fill add child form with "(.*?)"$/ do |email|
  find(:field, "Email").set(email)
end
```

and i try:

```
find_field('Email').send_keys([:command, 'a'], :backspace)
find_field('Email').send_keys(email)
```
=> `"child-account@exchild-account2@example.comample.com"`

```
find_field('Email').send_keys(:backspace, ... 25times ... , :backspace)
find_field('Email').send_keys(email)
```
=> `"ample.comchild-account2@example.com"`

```
fill_in('Email', with: email)
```
=> `"child-account@example.comchild-account2@example.com"`

i have no idea, somebody can help me ?

**Comment by geminiyellow** [comment]
change 
```
find(:field, "Email").set(email)
```
to
```
evaluate_script("document.getElementById('email').value = '#{email}'")
```
will work.

**Comment by twalpole** [comment]
Closing as it was stated PR #673 fixed this
