### ISSUE TITLE
'IOError: stream closed' with Poltergeist after calling session.driver.quit

### ISSUE THREAD

**Issue by wakproductions** [teampoltergeist/poltergeist#667]
I am using Capybara 2.4 for web page scraping and was having a memory leak issue with phantomjs remaining in memory and consuming resources. According to the Poltergeist webpage, the recommend fix is to call:

Capybara.session.driver.quit

Now the issue is that whenever I do Capybara.visit after quitting the driver, I receive the error:

IOError: closed stream

I believe resetting the session should fix this, but I get the same error whenever I call any of the _reset! methods on the session or driver. Is there a way to just reinitialize the driver after the call to quit?

**Comment by route** [comment]
@wakproductions I think it's wrong idea. You have to create brand new instance and use it, I think it's better to handle sessions yourself not using `Capybara.session`.

**Comment by route** [comment]
See our spec files as an example:
```ruby
session = Capybara::Session.new(:poltergeist, TestApp)
session.visit(...)
session.driver.quit

# create here another instance
```

**Comment by wakproductions** [comment]
Thanks! That approach resolved the problem.

**Comment by altusx** [comment]
After do |scenario|
    if ENV['BROWSER'] == "headless"
    else	
  	Capybara.current_session.driver.quit
    end
end
