### ISSUE TITLE
Poltergeist  - Request failed to reach server, check DNS and/or server status

### ISSUE THREAD

**Issue by haridak** [teampoltergeist/poltergeist#677]
Hi,
The test suite executes fine with selenium driver but gives the below shown error if the driver is set to poltergeist.
Request failed to reach server, check DNS and/or server status

Could you provide some inputs here? Let me know if am supposed to post this issue somewhere else. Thanks!

**Comment by twalpole** [comment]
This is going to need a lot more info about versions, configuration, what tests are doing exactly, etc before anyone can give any input -- closing -- we can reopen if more info is forthcoming

**Comment by haridak** [comment]
Capybara version - 2.4.4
Poltergeist version - 1.7.0
phantomjs version - 1.9.8.0
OS of client - OS X 10.10.5
Server running on AWS 
The test suite executes fine with selenium driver but gives the below shown error if the driver is set to poltergeist.
Request failed to reach server, check DNS and/or server status. Thanks in advance!

**Comment by twalpole** [comment]
Try using the poltergeist master branch -- it adds the url that is failing to the error message which will let you see url is being requested and make sure it's right --  The is really the most basic functionality of Poltergeist so I would be really surprised if there is an error in it for this behavior.  It's most likely something like a misconfigured driver setup on your end, or maybe an invalid setting of Capybara.app_host.

**Comment by haridak** [comment]
@twalpole Thank you.
I used the gem from master branch. The url in the error message is right, except that it also includes a pipe which isn't in the URL I specified in visit. Could that be the cause?  
message = 'Minitest::UnexpectedError: Capybara::Poltergeist::StatusFailError: Request to |'https://url.toserver.com|' failed to reach server, check DNS

I have Capybara.app_host set to the app url.

**Comment by twalpole** [comment]
no clue where the pipes are coming from - but yes if those are really in the url it's trying to go it would cause errors.  What exactly are you passing to visit and what exactly do you have Capybara.app_host set to

**Comment by haridak** [comment]
'''  Capybara.app_host= 'https://staging.storedgefms.com'
   visit('https://staging.storedgefms.com')''''
Error message: 
Minitest::UnexpectedError: Capybara::Poltergeist::StatusFailError: Request to |'https://staging.storedgefms.com|' failed to reach server, check DNS and/or server status

**Comment by twalpole** [comment]
Are you sure you're using phantomjs 1.9.8 as you indicated above?  That works fine for me while 2.0 generates the error (not sure why though)

**Comment by twalpole** [comment]
Turning on debugging in phantomjs - when using 2.0 I get the following

2015-11-02T14:24:12 [DEBUG] Network - Resource request error: 2 ( "Connection closed" ) URL: "https://staging.storedgefms.com/"

That really seems like the server is dropping the connection for some reason - so you might need to look at the server logs and see what it's doing.  It could be not allowing connections based on user agent or something I guess.

**Comment by haridak** [comment]
I turned on the debugger before posting this issue here. I did see that error. However, I saw the same error for other server on which the tests worked fine.(super confusing) I rechecked the phantomjs version and I see it as 2.0.0 and trust me it was 1.9.8 when I last checked it . I uninstalled 2.0.0 and installed 1.9.8 and everything's working fine. Thanks for all the inputs.  One last question, will this be handled as a bug for phantomjs and 2.0.0?

**Comment by twalpole** [comment]
This doesn't really appear to be a bug in poltergeist, since it appears to be the server actively closing the connection.   We also don't really know what's causing it so to call it a bug with phantomjs 2.0 is tough since it could just be an SSL configuration issue. If there were details provided from server logs on why this is happening then we may be able to provide a "solution" or at least document the issue.  You might want to check over on the phantomjs project to see if they have a bug listed for it.

**Comment by haridak** [comment]
@twalpole 

` options = {js_errors: false, timeout: 30,debug: true, phantomjs_logger: true, stdout: true, phantomjs_options: ['--ignore-ssl-errors=yes','--load-images=yes']}
  Capybara.register_driver :poltergeist do |app|
    Capybara::Poltergeist::Driver.new(app, options)
  end`

**Comment by twalpole** [comment]
the phantomjs_logger option takes an IO Object that is where the logs should go (defaults to STDOUT), not a boolean.  Also  you probably want to add '--debug=true to the phantomjs_options array

**Comment by subimage** [comment]
Running into this also. Hopefully here's some detailed information that will be helpful.

My setup is a bit odd, since I'm upgrading a Rails 2.3.18 > 3.x - but other than that fairly standard...
- OS X 10.10.5
- Ruby 2.1.5p273
- phantomjs: stable 2.0.0 (bottled), HEAD
- poltergeist (1.9.0)
- capybara (2.6.2)

Have a test suite with 16 tests...2 will fail when tested with the entire suite - yet pass in isolation with "focus". Have browsed other threads on this, and tried to alleviate the issue with the following setup and teardown wizardry:

```ruby

Capybara.register_driver :poltergeist do |app|
  options = {
    debug: true,
    timeout: 30,
    window_size: [1280, 1440],
    port: 44678+ENV['TEST_ENV_NUMBER'].to_i,
    phantomjs_options: [
      '--proxy-type=none', 
      '--load-images=no', 
      '--ignore-ssl-errors=yes', 
      '--ssl-protocol=any',
      '--web-security=false','--debug=true'
    ]
  }
  Capybara::Poltergeist::Driver.new(app, options)
end
Capybara.javascript_driver = :poltergeist
Capybara.ignore_hidden_elements = false
Capybara.default_max_wait_time = 30

class Capybara::BaseTest < ActionController::IntegrationTest
  # Make the Capybara DSL available in all integration tests
  include Capybara::DSL
  # Stop ActiveRecord from wrapping tests in transactions
  # Transactional fixtures do not work with Selenium tests, because Capybara
  # uses a separate server thread, which the transactions would be hidden
  # from. We hence use DatabaseCleaner to truncate our test database.
  self.use_transactional_fixtures = false

  def setup
    # Otherwise we can't connect...
    WebMock.disable_net_connect!(allow: [/cashboard.dev/], allow_localhost: true)
  end

  def teardown
    WebMock.disable_net_connect!
    Capybara.reset_sessions!
    # ... enabling/disabling does nothing - as does sleep between these calls
    #page.driver.reset! 
    DatabaseCleaner.clean
  end

  # ...other code
end

```

Getting errors like this:

```
  1) Error:
Capybara::BulletinBoard::AdminTest#test_while_editing_can't_see_rate_boxes_for_a_non-billable_project:
Capybara::Poltergeist::StatusFailError: Request to 'http://paid.cashboard.dev:9887/provider/projects/show/200482051#tasks/200482051/edit' failed to reach server, check DNS and/or server status
    /Users/seth/Work/cashboard/app/vendor/ruby/2.1.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:351:in `command'
    /Users/seth/Work/cashboard/app/vendor/ruby/2.1.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:34:in `visit'
    /Users/seth/Work/cashboard/app/vendor/ruby/2.1.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/driver.rb:95:in `visit'
    /Users/seth/Work/cashboard/app/vendor/ruby/2.1.0/gems/capybara-2.6.2/lib/capybara/session.rb:232:in `visit'
    /Users/seth/Work/cashboard/app/vendor/ruby/2.1.0/gems/capybara-2.6.2/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
    test/integration/capybara/bulletin_board/admin_test.rb:186:in `block in <class:AdminTest>'
    /Users/seth/.rbenv/versions/2.1.5/lib/ruby/2.1.0/minitest/unit.rb:1265:in `run'
    /Users/seth/.rbenv/versions/2.1.5/lib/ruby/2.1.0/test/unit/testcase.rb:17:in `run'
    /Users/seth/Work/cashboard/app/vendor/ruby/2.1.0/gems/activesupport-2.3.18/lib/active_support/testing/setup_and_teardown.rb:24:in `run'
    /Users/seth/Work/cashboard/app/vendor/ruby/2.1.0/gems/actionpack-2.3.18/lib/action_controller/integration.rb:673:in `run'
    /Users/seth/.rbenv/versions/2.1.5/lib/ruby/2.1.0/minitest/unit.rb:940:in `block in _run_suite'
    /Users/seth/.rbenv/versions/2.1.5/lib/ruby/2.1.0/minitest/unit.rb:933:in `map'
    /Users/seth/.rbenv/versions/2.1.5/lib/ruby/2.1.0/minitest/unit.rb:933:in `_run_suite'
    /Users/seth/.rbenv/versions/2.1.5/lib/ruby/2.1.0/minitest/unit.rb:914:in `block in _run_suites'
    /Users/seth/.rbenv/versions/2.1.5/lib/ruby/2.1.0/minitest/unit.rb:914:in `map'
    /Users/seth/.rbenv/versions/2.1.5/lib/ruby/2.1.0/minitest/unit.rb:914:in `_run_suites'
    /Users/seth/.rbenv/versions/2.1.5/lib/ruby/2.1.0/minitest/unit.rb:884:in `_run_anything'
    /Users/seth/.rbenv/versions/2.1.5/lib/ruby/2.1.0/minitest/unit.rb:1092:in `run_tests'
    /Users/seth/.rbenv/versions/2.1.5/lib/ruby/2.1.0/minitest/unit.rb:1079:in `block in _run'
    /Users/seth/.rbenv/versions/2.1.5/lib/ruby/2.1.0/minitest/unit.rb:1078:in `each'
    /Users/seth/.rbenv/versions/2.1.5/lib/ruby/2.1.0/minitest/unit.rb:1078:in `_run'
    /Users/seth/.rbenv/versions/2.1.5/lib/ruby/2.1.0/minitest/unit.rb:1066:in `run'
    /Users/seth/.rbenv/versions/2.1.5/lib/ruby/2.1.0/minitest/unit.rb:802:in `block in autorun'
```

Have attached full debug output for reference.
[poltergeist-phantom-output.txt](https://github.com/teampoltergeist/poltergeist/files/120015/poltergeist-phantom-output.txt)

**Comment by subimage** [comment]
FWIW, my issues disappeared after upgrading multiple things and moving to Rails 3.2

**Comment by hakunin** [comment]
Had the same issue, updating these helped:
```
    cucumber (2.3.2)
    cucumber (2.3.3)
      builder (>= 2.1.2)
      cucumber-core (~> 1.4.0)
      cucumber-wire (~> 0.0.1)

    websocket-driver (0.6.3)
    websocket-driver (0.6.4)
```

**Comment by wojtha** [comment]
Thx @hakunin I've run into this too. My bet is also on assets. I've resolved that by running the development server alongside with the running test suite. This might be also source of the flickering feature specs on our CI, I'll try to precompile assets there.

**Comment by wojtha** [comment]
@hakunin Experimenting with something like this:

```ruby
RSpec.configure do |config|
  config.before :all do
    ENV['PRECOMPILE_ASSETS'] ||= begin
      case self.class.metadata[:type]
      when :feature, :view
        STDOUT.write "Precompiling assets..."

        require 'rake'
        Rails.application.load_tasks
        Rake::Task['assets:precompile'].invoke

        STDOUT.puts " done."
        Time.now.to_s
      end
    end
  end
end
```

Inspired by this https://dzone.com/articles/precompiling-rails-assets but Sprockets::StaticCompiler was ripped of from Sprockets since then.

**Comment by BandanaPandey** [comment]
I also got errors like::
**Capybara::Poltergeist::StatusFailError**
on running tests.
I was using following in my app::
**minitest 5.9.0
capybara 2.8.1
poltergeist 1.10.0
phantomjs 2.1.1**

Solved it by adding following in my test_helper.rb
**Capybara.register_driver :poltergeist do |app|
    Capybara::Poltergeist::Driver.new(app, timeout: 1.minute, phantomjs_options: ['--load-images=no'])
  end** 

According to me, In my case it was timing issue. So i set the timeout to 1 minute and it worked.

**Comment by ziaulrehmandevsinc** [comment]
I had to use 120sec time-out, thank-you @BandanaPandey

**Comment by subimage** [comment]
This bug is happening again for me...the wrinkle this time is I've moved my development environment to a Debian/Vagrant setup - so I'm testing inside of a virtual machine.

- minitest (4.7.5)
- capybara (2.13.0)
- poltergeist (1.14.0)
- phantomjs 2.1.1

**Error is as follows:**

    E /test/integration/capybara/base_test.rb @ 77
    Capybara::BulletinBoard::AdminTest
      test_0001_anonymous
      !! Capybara::Poltergeist::StatusFailError
      Request to 'http://paid.cashboard.dev:55676/' failed to reach server, check DNS and/or server status

**My test file contains...**

  require 'capybara/poltergeist'
  Capybara.register_driver :poltergeist do |app|
    options = {
      debug: true,
      timeout: 1.minute,
      window_size: [1280, 1440],
      phantomjs_options: [
        '--proxy-type=none', 
        '--load-images=no', 
        '--ignore-ssl-errors=yes', 
        '--ssl-protocol=any',
        '--web-security=false'#,'--debug=true'
      ]
    }
    Capybara::Poltergeist::Driver.new(app, options)
  end
  Capybara.javascript_driver = :poltergeist

  setup do
    # Otherwise we can't connect...
    WebMock.disable_net_connect!(allow: [/cashboard.dev/,/paid.cashboard.dev/], allow_localhost: true)
    Capybara.current_driver = Capybara.javascript_driver
    Capybara.default_max_wait_time = 1.minute
    Capybara.ignore_hidden_elements = false
    Capybara.app_host = Capybara.default_host = "http://paid.#{Settings.app_domain}"
    Capybara.server_port = 55676
    Capybara.always_include_port = true
  end

  def teardown
    WebMock.disable_net_connect!
    Capybara.reset_sessions!
    DatabaseCleaner.clean
  end

It looks as if the web server is "up"...

    vagrant@cb-dev-app-1 [/vagrant/log]
    $ netstat -a |grep 55676
    tcp        0      0 localhost:44564         localhost:55676         TIME_WAIT

But if I telnet to it, I get connection refused as well. Anyone have pointers? I've wasted 2 days on this so far.

**Comment by alejoparedes** [comment]
Hi fellas! I had the same issue.

* I was using gems:
   cucumber, cucumber-rails, capybara, poltergeist, selenium-webdriver
* I had solved this issue by including the line:
   require 'cucumber/rails'
* This spared me the need to setup application host configurations, be it either poltergeist driver or selenium-webdriver

I know this' been closed quite a time ago but just in case sharing my experiences!

**Comment by flapjackfritz** [comment]
I too had a similar issue.

When running the tests, I would get the error (only sometimes):
```ruby
     Capybara::Webkit::InvalidResponseError:
       Unable to load URL: http://es.example.com/newest because of error loading http://es.example.com/newest: Unknown error
```

and my capybara-webkit debug output was telling me:
```
Finished "Visit(http://es.example.com/newest)" with response "Success()"
Received 0 from "http://es.example.com/newest"
Page finished with false
Load finished
Page load from command finished
Wrote response false "{\"class\":\"InvalidResponseError\",\"message\":\"Unable to load URL: http://es.example.com/newest because of error loading http://es.example.com/newest: Unknown error\"}"
Received "CurrentUrl()"
Started "CurrentUrl()"
Finished "CurrentUrl()" with response "Success(about:blank)"
Wrote response true "about:blank"
Received "CurrentUrl()"
Started "CurrentUrl()"
Finished "CurrentUrl()" with response "Success(about:blank)"
Wrote response true "about:blank"
Received "Reset()"
Started "Reset()"
undefined|1|SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.
```

I was able to solve it by adding to my /etc/hosts file:
`127.0.0.1 es.example.com`

And then in my spec_helper
```ruby
Capybara.configure do |config|
  config.always_include_port = true
end
```

Hope this helps someone.

**Comment by twalpole** [comment]
@flapjackfritz This is the Poltergeist project, not the capybara-webkit project - but yes,  if the hostnames you use don't resolve to anything you will have errors.

**Comment by flapjackfritz** [comment]
@twalpole Ah, I have so many similar tabs open on this I posted in the wrong thread.  Please feel free to delete if you like.
