### ISSUE TITLE
Inspector with Chrome on Windows does not load

### ISSUE THREAD

**Issue by lowjoel** [teampoltergeist/poltergeist#680]
When triggering the inspector on Windows, Chrome is started but does not open any tab with the URL of the inspector. The command line is correct, ie `chrome //localhost:port/`, but no tab is open.

The change was introduced in 9b73d618688c5cbdeaea600a193a514c58a754e6. I'm not sure why that was made, but to me protocol relative URLs only make sense relative to some page. In this case, there is no page, so protocol relative URLs doesn't seem to have any meaning.

Thoughts?

**Comment by tylerhunt** [comment]
This also doesn't work on OS X when Chrome isn't present and it falls back to the `open` command. In that case, the following error is displayed:

```
The file //localhost:9664 does not exist.
```

**Comment by twalpole** [comment]
Has Poltergeist 1.8.0 fixed this?

**Comment by twalpole** [comment]
The schem was readded in 1.8.0, so I'm closing this due lack of response and an assumption it's fixed.  If this is still an issue we can reopen if/when info is provided

**Comment by lowjoel** [comment]
Ah, I didn't get a notification. Thanks! It seems to work now.
