### ISSUE TITLE
current_url test with Phantomjs 2

### ISSUE THREAD

**Issue by twalpole** [teampoltergeist/poltergeist#687]
The [supports allowed characters](https://github.com/teampoltergeist/poltergeist/blob/master/spec/integration/session_spec.rb#L476) test fails when run with PhantomJS 2 - when visiting '/poltergeist/arbitrary_path/200/foo?a[b]=c' it returns exactly the same in `current_url` as opposed to '/poltergeist/arbitrary_path/200/foo?a%5Bb%5D=c' which is what the test expects (btw, its currently the only test still failing for PhantomJS2 on travis)

**Comment by twalpole** [comment]
@route  the behavior with PhantomJS 2 matches the behavior of capybara when used with selenium, in that it returns the current_url in the same form it was passed to visit (encoded or unencoded) -  all while showing the decoded form in the url bar.  Do you want to just remove this test, make it test for either the encode or unencoded format, or change code to try and make it always return in an encoded format?

**Comment by twalpole** [comment]
@route any thoughts on this?

**Comment by route** [comment]
@twalpole Sorry link shows a different line I suppose, did you mean this test https://github.com/teampoltergeist/poltergeist/blob/master/spec/integration/session_spec.rb#L512 ?

**Comment by twalpole** [comment]
@route yep, that's the one - sorry about that

**Comment by route** [comment]
I remember capybara raises an error if given url is invalid, I think we can simply get rid of it then
