### ISSUE TITLE
Remote debugging not working

### ISSUE THREAD

**Issue by amnesia7** [teampoltergeist/poltergeist#706]
I have set my driver using:

```
Capybara.register_driver :poltergeist_debug do |app|
  Capybara::Poltergeist::Driver.new(app, timeout: 60, inspector: true)
end
Capybara.javascript_driver = :poltergeist_debug
```
I'm on Ubuntu 12.04 and have chrome and firefox installed.

When I try to use `page.driver.debug` it launches chrome but saying Error file not found.

I have a test that works fine with selenium (firefox) but fails in headless poltergeist which is annoying so I'd like to be able to debug it somehow to see why the test is failing.

What information can I provide to help diagnose the poltergeist debug screen that's failing to launch properly or am I missing something?

**Comment by twalpole** [comment]
Versions of poltergeist and phantomjs used and the Url being opened in chrome would be a good start

**Comment by amnesia7** [comment]
Good point @twalpole 

From Gemfile.lock : `poltergeist (1.6.0)`

From commandline (`phantomjs --version`) : `1.9.8`

Debug page that loads : file:///localhost:9664/
> This web page has not been found
> ERR_FILE_NOT_FOUND

**Comment by twalpole** [comment]
Try updating your poltergeist - there was a fix including into 1.8+ to do with http vs https access when using remote debugging

**Comment by amnesia7** [comment]
That seems to have done it. Thanks @twalpole 
I now get the page with the 2 links and the second link loads the webkit inspector. 
I can now try to figure out why it's not working, hopefully a few carefully placed console.logs in the js code will highlight what's not running (even though it works on selenium and works using chrome normally). If this is using webkit; I wonder if something isn't running properly for webkit browsers...I'll have to see if I can get a webkit browser to test it with to see if that helps.

**Comment by twalpole** [comment]
@amnesia7 you probably want to try upgrading to phantomjs 2 - 1.9.8 is basically equivalent to a 5 year old browser

**Comment by amnesia7** [comment]
Thanks for the heads up @twalpole. I'll check that. 
I'm sure there was a reason originally why I went for 1.9.8 because of something not working in v2 but I can't remember what it was so I'll snapshot my development VM (so much easier to restore it again) and give it another go.

**Comment by amnesia7** [comment]
Haven't managed to update to v2 (it's not easy to get it working on ubuntu 12.04) so I went back to try to figure out if there was actually a bug. 
Turns out there was actually a bug in my code but it was only being highlighted by the headless poltergeist and not by selenium-firefox or my own use of the app in chrome...
