### ISSUE TITLE
Capybara::Poltergeist::StatusFailError occurs for every test after insecure content warning

### ISSUE THREAD

**Issue by ronwsmith** [teampoltergeist/poltergeist#707]
We're using the secure_headers gem to restrict content to only load from https.  A couple pages currently attempt to include a pixel that's hosted on http.

Test output looks like this:

```ruby
XXXX
  YYYY
The page at https://application_url.com/path/to/page ran insecure content from http://pixel.com/path.
    ZZZZ
    AAAA (FAILED - 1)
    BBBB (FAILED - 2)
```

The test that renders the page with insecure content passes.  Every other test that runs afterward fails on the first URL hit with the same error:

```ruby
      Capybara::Poltergeist::StatusFailError:
        Request to 'https://application_url.com/path/to/any_page' failed to reach server, check DNS and/or server status
```

I have attempted the following (from other similar issues) without success:

```ruby
RSpec.configure do |config|
    config.after(:each) do
      Capybara.reset_sessions!
      page.driver.restart if page.driver.respond_to?(:restart)
    end
end

poltergeist_options = { js_errors: false, phantomjs_options: ['--ignore-ssl-errors=yes', '--ssl-protocol=any'] }

Capybara.register_driver :poltergeist do |app|
  Capybara::Poltergeist::Driver.new(app, poltergeist_options)
end
```

Note: I am running against an app_host and run_server is false.  database_cleaner is required but I commented out every command within the RSpec configuration.

Any other ideas to try?

**Comment by twalpole** [comment]
What versions are you running, and can you provide a minimal example that reproduces the issue so we can look at it?

**Comment by ronwsmith** [comment]
ruby 2.2.3, rails 4.2.4

```ruby
    capybara (2.5.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    poltergeist (1.8.1)
      capybara (~> 2.1)
      cliver (~> 0.3.1)
      multi_json (~> 1.0)
      websocket-driver (>= 0.2.0)
    rspec-rails (3.4.0)
      actionpack (>= 3.0, < 4.3)
      activesupport (>= 3.0, < 4.3)
      railties (>= 3.0, < 4.3)
      rspec-core (~> 3.4.0)
      rspec-expectations (~> 3.4.0)
      rspec-mocks (~> 3.4.0)
      rspec-support (~> 3.4.0)
    secure_headers (2.4.3)
      user_agent_parser
    selenium-webdriver (2.47.1)
      childprocess (~> 0.5)
      multi_json (~> 1.0)
      rubyzip (~> 1.0)
      websocket (~> 1.0)
```

While listing this out I realized my default driver is using puffing-billy too, so let me try it without that to remove another variable before you look into this more deeply.

I'll do that and then build out a sample app if the problem persists.  Likely early next week due to the US holiday weekend.

**Comment by twalpole** [comment]
ok -- let us know what version of phantomjs you're using too please.

**Comment by ronwsmith** [comment]
phantomjs 2.0.0

Determined that using puffing-billy was the cause here.  When using vanilla poltergeist, I get the same insecure content warnings but other tests execute normally.

Here's the scenario that caused this for future searchers:
 * Test suite uses VCR and puffing-billy on Jenkins for speed and test isolation
 * Decided to use a subset of the test suite to run against pre-production app_host (external URL, not a rack app) before production deployments
 * Disabled VCR caching but had my default driver still set to `:pg_billy`
 * External host requests were attempting to be proxied through locally run puffing-billy server.

Not sure how it worked at all, but it definitely became unstable when any errors occurred.

Appreciate the fast responses @twalpole!
