### ISSUE TITLE
Capybara::Poltergeist::DeadClient when closing an iframe

### ISSUE THREAD

**Issue by mrsimo** [teampoltergeist/poltergeist#712]
I'm trying to test that an iframe closes when you press escape, and it's crashing hard. This is the code (used to work with capybara-webkit):

```ruby
    test 'the modal closes when the ESC key is pressed' do
      within_frame 'harvest-iframe' do
        assert_selector '.js-submit'
        execute_script '$("body").trigger($.Event("keydown", { which: 27 }));'
      end

      assert_no_selector '#harvest-iframe'
    end
```

I see this output running the test:

```
PhantomJS has crashed. Please read the crash reporting guide at
<http://phantomjs.org/crash-reporting.html> and file a bug report at
<https://github.com/ariya/phantomjs/issues/new>.
Please attach the crash dump file:
  /var/folders/3s/wls1m67j2yb2x5wct2mctqwh0000gn/T//B6B807A1-DE33-4EA4-9B07-8F5563E61CA3.dmp

  1) Error:
Platform::ModalTest#test_the_modal_closes_when_the_ESC_key_is_pressed:
Capybara::Poltergeist::DeadClient: PhantomJS client died while processing {"id":"c348b889-c20c-42ef-8be9-3c660f0f8ba1","name":"pop_frame","args":[]}
```

I'm not attaching the dump file, as it seems quite easy to reproduce, but let me know if you need it!

**Comment by twalpole** [comment]
What versions of poltergeist and phantomjs are you using? What does the html look like? We need all relevant details to attempt to replicate.  Also note that the errors specifically to report at the phantomjs project, so it's possible its a bug inside phantomjs and not poltergeist.

**Comment by mrsimo** [comment]
My apologies! I believe they were latest versions.

```
$ phantomjs -v
2.0.0
$ cat Gemfile.lock | grep poltergeist
    poltergeist (1.8.1)
```

I'm gonna try and come up with a working example.

**Comment by mrsimo** [comment]
Sorry, I'll close, as I can't figure out how to provide the proper example. Apologies for the noise.
