### ISSUE TITLE
Poltergeist doesn't wait for iframe reload

### ISSUE THREAD

**Issue by thehappycoder** [teampoltergeist/poltergeist#714]
When I do this:
find('input[name=NextPage]').click

The website reloads an iframe via location.href and poltergeist doesn't wait when it happens.

So I have to use sleep :(
Is it a bug or I am doing something wrong?

Same happens when iframe's src attribute value is changed.

**Comment by twalpole** [comment]
You're doing something wrong - capybara and poltergeist never wait for a click to do anything - they click and move on to the next thing -- If you want it to wait you need an expectation for something that will appear on the page. For instance

    find('input[name=NextPage]').click
    expect(page).to have_text('text that is only visible on the next page')  #this will wait up to Capybara.default_max_wait_time seconds for the text to appear

**Comment by thehappycoder** [comment]
Thank you for the tip!

I only started to use these tools. By the way, I use them not for testing but for using actual web application which doesn't have any API.
