### ISSUE TITLE
Custom host IP

### ISSUE THREAD

**Issue by arturocastro** [teampoltergeist/poltergeist#716]
I'm looking to use Poltergeist from Openshift, where it's not permitted to bind to localhost (127.0.0.1). So, I'm trying to use a [patched phantomjs](https://paolobernardi.wordpress.com/2015/02/25/phantomjs-with-ghostdriver-on-openshift/) that allows binding to a custom IP.

I can add an option to specify the host address that Poltergeist will use, not unlike the existing port option. It seems as it would only be necessary to make it work for `poltergeist/lib/capybara/poltergeist/web_socket_server.rb`, but I also found a reference to localhost in `poltergeist/lib/capybara/poltergeist/client/connection.coffee`.

Would it be necessary to add that change to the js part as well?

**Comment by arturocastro** [comment]
OK, I can confirm that changing the IP in `web_socket_server.rb` and `compiled/connection.js` worked fine for my Openshift setup. I'd be happy to work on a patch to add this feature from command line options.

**Comment by route** [comment]
Sounds good to me, go ahead!

**Comment by route** [comment]
I'll close this for now. Whenever you are ready just submit PR.
