### ISSUE TITLE
a[:href] returning scheme and host after upgrading from v1.7.0 to v1.8.0

### ISSUE THREAD

**Issue by erictheise** [teampoltergeist/poltergeist#717]
We have a simple cucumber step that looks like:
```
Then('I should see the "XYZ" link with directory url') do
  a = page.first('a', :text => "XYZ")
  expect(a[:href]).to eq directory_index_path
end
```
This has worked fine, but in upgrading from `v1.7.0` to `v1.8.0` I'm seeing:
```
      expected: "/xyz"
           got: "http://localhost.example.com:3001/xyz"
```
Seems this may be related to #579? I'm not sure what to make of it.

**Comment by twalpole** [comment]
From the Changelog -   Node#[] now prefers element properties over attributes when the property exists and is not an object. This is similar to the selenium driver behavior. 
The href property (as opposed to attribute) of an anchor tag returns a full normalized URL so thats what you get now.  If you want to verify the attribute you can either specify it in the find

    a = page.first(:link, 'XYZ', href: directory_index_path)

or better yet define your step as

    Then('I should see the "XYZ" link with directory url') do
      expect(page).to have_link("XYZ", href: directory_index_path, minimum: 1)  #minimum 1 allows for more than 1 matching link to be on the page (if that's why you were using first)
    end   

or you can access it through the attributes hash

    a.attributes['href']   # only supported with the poltergeist driver

**Comment by erictheise** [comment]
Thanks for taking the time to explain, @twalpole, especially on a holiday!

**Comment by linuxonrails** [comment]
Hi @twalpole 

How can i use the poltergeist driver with capybara? it is possible?

> a.attributes['href']   # only supported with the poltergeist driver

**Comment by twalpole** [comment]
@linuxonrails https://github.com/teampoltergeist/poltergeist/blob/master/README.md
