### ISSUE TITLE
Clone Capybara Session?

### ISSUE THREAD

**Issue by agoyen** [teampoltergeist/poltergeist#718]
Hi!

As poltergeist is not thread-safe and it's necessary to instance a new Capybara::Session for each thread, is there any way to clone a session so that we don't need to log in more than once?

Thanks!

**Comment by twalpole** [comment]
There's no built-in support for cloning a session, but if you're using cookies for your session storage you can read the relevant cookies from an existing session and then set them on new sessions you create using page.driver.cookies and page.driver.set_cookie
