### ISSUE TITLE
Clear browser cache?

### ISSUE THREAD

**Issue by thom-nic** [teampoltergeist/poltergeist#719]
I'm running into intermittent test failures that look like the following:
```
     Failure/Error: expect(status_code).to eql 200
       
       expected: 200
            got: 304
```
Clearly what's happening is, dependent on the order of my tests, it appears sometimes the same URL has already been fetched in a previous test. This is causing Poltergeist/ Phantom is sending an `ETag` header, causing the server to respond with a 304 instead of a 200.  Note I already have `config.before( :each) { Capybara.reset_sessions! }`.

Now, obv I can change my tests but the fact remains that tests are not isolated due to browser caching.  I found the [Browser#reset_cache!](http://www.rubydoc.info/github/jnicklas/capybara/Capybara%2FRackTest%2FBrowser%3Areset_cache!) method in the Capybara API but clearly doesn't apply to the Poltergeist driver.  I see methods for clearing cookies and localStorage, but nothing to clear the browser cache.  Is this possible?

**Comment by route** [comment]
Why do you have to check status code in the first place?
PhantomJS should behave like a real browser so generally speaking this case doesn't look like an issue.
`#reset_cache` belongs to rack_test driver not capybara which is why it's not compatible with the rest of drivers.

**Comment by thom-nic** [comment]
> Why do you have to check status code in the first place?

Because I'm testing the behavior of my app which includes the HTTP response.

> PhantomJS should behave like a real browser

Agreed but I don't understand why this precludes the ability to clear the browser's cache.  You can do that in a real browser.

From a purely functional perspective there are other reasons why I might want to test a user arriving at at page with an empty resource cache versus previously having visited the page.

Bottom line is, tests are not isolated, Poltergeist/ Phantom behave (slightly) differently based on prior tests or order of tests.  

I've found the `Driver.reset!` method but it's not clear whether or not it clears the browser cache.

**Comment by route** [comment]
I'm asking that because while it may sound reasonable to check status for unit tests for capybara we usually work with content, right? So maybe you could solve your case just a little modifying your spec.
I agree on the part of isolated tests but I suppose there's no such feature in PhantomJS right now. We do our best clearing cookies and localStorage between tests but we can't clear cache. So you can try to workaround it with headers or http://stackoverflow.com/questions/23390974/phantomjs-keeping-cache and if it works send us a PR. BTW `reset!` isn't for this purpose.

**Comment by thom-nic** [comment]
Ah thank you that's very helpful.  It looks like PhantomJS 2.0 has a `page.clearMemoryCache()` that looks like it could be exposed via Poltergeist maybe?

Also you're right, I could add a random param on my requests to force a cache miss as well.

Direct link to related phantomJS issue: ariya/phantomjs#10357

**Comment by route** [comment]
@thom-nic yes you can take a look at https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/client/web_page.coffee which is kind of a wrapper and try to call page.clearMemoryCache() in some place after each test, but I'm afraid of crashes to be honest.. Maybe it could work who knows. Also you could try to modify cache headers which sounds like a universal idea for all versions and probably better, not sure. Anyway there's no straightforward solution...

**Comment by thom-nic** [comment]
Understood.  Thanks for taking the time to explain!
