### ISSUE TITLE
Sidekiq, Capybara, Poltergeist, Phantom JS - memory quota exceeded errors

### ISSUE THREAD

**Issue by tomgallagher** [teampoltergeist/poltergeist#722]
Hello

Some background: Rails app. Background jobs. I'm running Sidekiq with multiple theads, each one of them is using Capybara, Poltergeist and PhantomJS in order to test and take screenshots of different pages.

I'm hitting critical memory quota exceeded errors in my worker. It seems highly likely that I'm collecting multiple instances of PhantomJS on my worker, despite the jobs finishing as expected.

I have tried something like Capybara::Session.close or Capybara::Session.quit, in a teardown routine at the end of my Sidekiq job and that did not make a difference. I can't see how to do this.

Any help would be massively appreciated.

Tom

**Comment by route** [comment]
First off you have to instantiate your own session manually like this:
```ruby
Capybara.register_driver(:poltergeist) do |app|
  Capybara::Poltergeist::Driver.new(app, js_errors: false, timeout: 60)
end
Capybara.default_driver = :poltergeist
session = Capybara::Session.new(:poltergeist)
session.visit(...)
session.find(...).click
```
then when you are sure you don't need it anymore call `session.driver.quit`.

**Comment by twalpole** [comment]
Depending on how many sites you're visiting - you may also want to call clear_network_traffic on the driver every now and then - since that is not cleared normally.

**Comment by chamnap** [comment]
I also faced this problem. Can't figure out how to solve it. I did exactly as route said, and the memory keeps pilling up.

**Comment by route** [comment]
@chamnap memory of what Ruby or PhantomJS process?
