### ISSUE TITLE
Capybara.default_driver in the documentation

### ISSUE THREAD

**Issue by DannyBen** [teampoltergeist/poltergeist#730]
Hi,

Shouldn't the README mention that Rails users (perhaps others as well?) should do `Capybara.default_driver = :poltergeist` and not `Capybara.javascript_driver = :poltergeist` ?

When I used the latter, and ran my cucumber features the driver was still `Rack::Test`

**Comment by route** [comment]
It's intended behaviour. In general you usually need poltergeist driver only for a part of tests not the whole bunch and for instance running controller tests on poltergeist would slow them down.
