### ISSUE TITLE
Timeout when setting whitelist

### ISSUE THREAD

**Issue by crazydog115** [teampoltergeist/poltergeist#732]
PhantomJS 2.1.1
Poltergeist 1.9.0
Capybara 2.5.0
Ruby 2.2.2
Poltergeist timeout is 60.

Occasionally, but not always, when calling `page.driver.browser.url_whitelist = ['list
, 'of', 'URLs']` I receive the following error.
```
Capybara::Poltergeist::TimeoutError: Timed out waiting for response to {"id":"7b833228-f264-45e5-9900-e89430bc0847","name":"set_url_whitelist","args":['list', 'of', 'URLs']}.
It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker.
```

**Comment by twalpole** [comment]
Does this only happen if this comes after a specific test -- ie if running in random order and you get the error, then you rerun with the same seed does the error happen again repeatedly?

**Comment by crazydog115** [comment]
In this use case I am actually using poltergeist in a production environment to emulate a browser, so it happens intermittently inside of a new thread.

**Comment by twalpole** [comment]
I don't believe poltergeist is threadsafe so this could really be anything --  setting url whitelist doesn't really do much other than sending the array over to the client running in phantomjs, storing it in a variable, and returning so there's not really much to go wrong - unless you're attempting to use it from another thread at the same time and command/responses are overlapping.  Do you have debug log output from around the error, and do you have js_errors turned on in your driver settings?

**Comment by crazydog115** [comment]
Na I'm not interacting with the same session across threads.

I don't have a debug log handy right now, but I can attempt to produce one. `js_errors` has been off, but I'll turn it on when getting the debug log and we'll see what happens.

**Comment by twalpole** [comment]
Closing due to lack of response, we can reopen if this is still an issue and more info is provided
