### ISSUE TITLE
Consider removing multi_json dependency

### ISSUE THREAD

**Issue by yob** [teampoltergeist/poltergeist#733]
Hi,

JSON has been part of the ruby stdlib since 1.9.0 (see https://github.com/ruby/ruby/commit/af1c4167), and the latest version of poltegeist requires ruby 1.9.3 or better.

Would you consider removing multi_json as a dependency, and just using `require 'json'` instead? Rails recently made a similar change (https://github.com/rails/rails/pull/23453), which has prompted other libraries to consider the same issue (like [simplecov](https://github.com/colszowka/simplecov/issues/458) and [stripe](https://github.com/stripe/stripe-ruby/pull/379)).

See also this recent [blog post](http://www.mikeperham.com/2016/02/09/kill-your-dependencies/).

Thanks for a great library!

**Comment by route** [comment]
Sounds good! Mind opening a PR?

**Comment by yob** [comment]
Sure, I've opened #734

**Comment by route** [comment]
Thank you!
