### ISSUE TITLE
window height fixed to 50px in latest versions?

### ISSUE THREAD

**Issue by AntonTrapp** [teampoltergeist/poltergeist#736]
Used poltergeist (with capybara) in previous projects, now I can't get a usable window height (with 1.9.0).

`Capybara::Poltergeist::Driver.new(app, window_size: [1920, 1080], ...`

sets only the width, `page.driver.resize_window(1920, 1080)` sets only the width, the height is always 50px - the width can be changed. If I do not specify any size I get 1024 x 50 Pixels.

Please, I **love** poltergeist, don't want to use other drivers for my tests... :)

**Comment by twalpole** [comment]
This is something specifically tested for in the specs - https://github.com/teampoltergeist/poltergeist/blob/master/spec/integration/driver_spec.rb#L77 - so it's unlikely to be a bug in poltergeist.  Have you changed anything else recently?  
Secondly -  poltergeist does now support the capybara window api (other than maximize) so to write your tests in a more driver agnostic manner you should be able to do

    page.current_window.resize_to(1920,1080)

**Comment by AntonTrapp** [comment]
@twalpole - Thank you for your fast answer.

New project, used poltergeist with the same code in the config for ages (and many projects). Now installed it, copied the config and I can set the width as usual, but not the heigt :D

Inspected the page.driver.browser config, the window-size from the configuration is set (both width and height), but when I produce a screenshot (capybara-screenshot 1.0.3) I get this 50 pixel height part of the screen (with no scrollbar, which IS funny). If I change it to selenium, everything is fine - but about 100 times slower ;)

Because of the missing scrollbar I tried something. **I just replaced the whole page with a dummy with some h1 (empty header)** and than poltergeist is able to **set the window height up to 1354 pixels (maximum, depending on the content length of the page** - can be shorter but not longer). Again no scrollbar if the page is longer.

I can add some empty space at the end of the bootstrap stuff so I can see my screenshots during testing, but I am willing to try find out what is going wrong. Any idea why (apart from some bootstrap problems) the height is always dynamic (up to the maximum)? Can I do something to help?

**Comment by twalpole** [comment]
Do you have anything accessing window.outerWidth or outerHeight ??  Those don't work in phantomjs so I guess that could cause issues.  Since it's dynamic, I'm guessing it has to be some JS in your project that is adjusting things, do you happen to be using the boostrap 4 alpha??  There could be bugs in that.  Other than that, If you updated your phantomjs version recently maybe there's a bug in the new release, I haven't come across any window size issues with phantomjs 2.1.1 though

**Comment by AntonTrapp** [comment]
No, only using outerWidth on a datetime picker on another page and the simple test was basically `<html><head></head><body><h1>TEST</h1>(multiple times)</body>`. Config is:

```
Capybara.register_driver :poltergeist do |app|
  Capybara::Poltergeist::Driver.new(
    app,
    # change when 2.0.1 is available with the file upload bugfix
    # phantomjs: "#{Rails.root}/bin/phantomjs_2_0_0_with_file_upload_bugfix",
    debug: false,
    window_size: [1920, 1200],
    timeout: 10,
    js_errors: true,
    # phantomjs_options: '--ignore-ssl-errors=yes',
    phantomjs_logger: Logger.new("#{Rails.root}/tmp/capybara/console_log.txt")
  )
end
```

I wrote a one-liner that extends the page in test environment, enough for me. Maybe we should close this bug and if other users stumble over the same topic in the next months reopen it and I could try to help reproducing it?

**Comment by twalpole** [comment]
ok -- will do.   FYI  phantomjs_logger is passed to phantomjs and is needs to be an IO (or IO dervied) object, which Logger is not - so I'm surprised you haven't had issues with that - also in poltergeist 1.9.0 should work with 2.0.0, 2.0.1, and 2.1.1 so you should be able to update to a newer version of phantomjs
