### ISSUE TITLE
Intermittent failures trying to fill a text area in test, multiple methods

### ISSUE THREAD

**Issue by mordocai** [teampoltergeist/poltergeist#740]
I am trying to fill in a simple textfield with poltergeist + phantomjs v2.1.1 on debian testing GNU/linux (phantomjs complied from source). Edit: Poltergiest version 1.8.1 (will try 1.9.0 shortly, just realized it existed)

I unfortunately cannot share my entire app, but i'll try to share enough to represent the issue faithfully.

This is an angularjs app, the markup is in a bootstrap modal  and looks like:

````
<div>
  <div class="modal-header">
    <h3>Comment on</h3>
  </div>
  <div class="modal-body">
    <form name="commentForm">
      <div>Please provide a comment:</div>
      <textarea id="comment" class="form-control" required ng-model="comment"></textarea>
    </form>
  </div>
  <div class="modal-footer">
    <button
       class="btn btn-secondary"
       ng-click="$dismiss()">
      Cancel
    </button>
    <button
            class="btn btn-primary"
            ng-disabled="! commentForm.$valid"
            ng-click="$close(comment)">
      Save
    </button>
  </div>
</div>

````

I have this expect first (to wait for the modal to pop up):

````
expect(page).to have_text("Please provide a comment:")
````

While it shouldn't matter to this problem, after attempting to fill in the comment I have:

````
expect(page).to have_button("Save", visible: true, disabled: false)
click_button("Save")
````
I have then tried various methods of putting in the comment.

First I tried the standard:

````
page.fill_in('comment', with: 'blah')
````

But this intermittently fails to work (it just doesn't fill the text field with anything when it fails).

After reading the source I then tried:

````
page.find(:fillable_field, 'comment').set("blah", nil)
````

Which had the same problem.

Next I tried:

````
page.find('#comment').trigger("click") # also tried with .click
page.send_key('blah')
````

~~But continued to have intermittent failures.~~ Just went back to look at results for this solution, this was actually just bad code. I'll need to look at it again.

Finally I tried:

````
locator = 'comment'
with = 'blah'
page.execute_script "document.getElementById('#{locator}').value = '#{with}'"
````

Which also had intermittent failures.

Any ideas on how to get consistent working behavior?

While I wait on responses I plan on writing something to try the standard fill_in solution over and over until it works or a max number of tries but i'd prefer to avoid that as a long term solution.

**Comment by mordocai** [comment]
Alright, upgraded to poltergeist 1.9.0 and fixed the send_key code example.

All of the above results seem to be the same with 1.9.0. The fixed send_key example (which also has intermittent failure) is

````
page.find('#comment').native.send_key('blah')
````

**Comment by mordocai** [comment]
This seems to work, but I don't consider this issue solved since this is awful. Most times this is only running twice.

````
      # XXX: See https://github.com/teampoltergeist/poltergeist/issues/740 for why we are doing this
      #      abomination.
      result = ""
      counter = 0
      while result.empty? && counter < MAX_RETRIES
        page.fill_in('comment', with: 'blah')
        sleep SLEEP_TIME
        result = page.find('#comment').value
        counter += 1
      end
````

**Comment by twalpole** [comment]
If you just put a `sleep(5)` in front of the `page.fill_in('comment', with: 'blah')` do the intermittent failures go away?

**Comment by mordocai** [comment]
I'd have to look at it again to be sure, but from memory I added a couple second sleep (2 or 3, not 5) before it with no positive results.

**Comment by twalpole** [comment]
@mordocai Things like this can be caused by fields having the scopes values rendered into them after/during capybara/poltergeist filling in the fields - which has the effect of removing the changes poltergeist is making. This can especially happen with modals if the scopes values aren't rendered until after the modal is fully visible, because poltergeist will start filling it in part way through the show animation (as soon as it finds the fields).  Usually adding a longish sleep before calling fill_in will determine if that is the case - once confirmed then ways to make the test more reliable can be looked at (waiting for classes that are added to the modal only when it's fully shown, turning off animations in test mode, etc)

**Comment by twalpole** [comment]
Closing due to lack of response
