### ISSUE TITLE
Poltergeist 2.0 development

### ISSUE THREAD

**Issue by twalpole** [teampoltergeist/poltergeist#744]
@route @simi  I pushed up a 2.0-dev branch to start the changes to move towards 2.0 .
So far I've moved the minimum ruby to 2.0.0, minimum phantomjs to 2.1.1, and some cleanup.
- [x] Only support ruby 2.0.0+
- [x] Only allow phantomjs 2.1.1+
- [x] Fix tests that require phantomjs to be in the path on travis
- [x] Remove workarounds for previous phantomjs issues
- [ ] Other?

**Comment by simi** [comment]
Can you add Roadmap to first comment with tickboxes, so we can track what's done and what's blocking?

**Comment by twalpole** [comment]
done -- we can add more items as we determine what they should be

**Comment by twalpole** [comment]
@route - whats your thought on Window#maximize?  Just resize to some fixed size? make a configurable size? Leave it like it is now with no support?

**Comment by simi** [comment]
@twalpole probably implementation of [Window#maximize](http://www.rubydoc.info/github/jnicklas/capybara/master/Capybara/Window#maximize-instance_method) ([src](https://github.com/jnicklas/capybara/blob/2a51b817b355f6c1a5e95a471a87f1a492562e55/lib/capybara/window.rb#L99)).

for example [capybara's implementation in selenium](https://github.com/jnicklas/capybara/blob/59d21b5b8264669b8d726ba2fee7e263f5855b6d/lib/capybara/selenium/driver.rb#L176)

some info about [maximize in phantomjs](https://github.com/ariya/phantomjs/blob/842715be9d2bb27865c179c12761290fa3f2929c/src/ghostdriver/request_handlers/session_request_handler.js#L324)

**Comment by twalpole** [comment]
@simi  - Yes - the issue with phantomjs is there is no physical screen size that limits the window size - so to support maximize we have to specify what size "maximize" means.  Whether that size is fixed, or configurable through the driver registration.  See https://github.com/teampoltergeist/poltergeist/commit/0812c826f7b941e33be93c47dab65265fc59f52e for implementation that would support it, with a configurable size, defaulting to 1366x768 if none specified.  If that type of config is acceptable then it's just a matter of deciding wether 1366x768 is an acceptable default size or whether it should be something else.

**Comment by simi** [comment]
@twalpole looks great!

**Comment by route** [comment]
@twalpole In general it sounds right for me not to have maximize at all, because it doesn't have screen. But in practice I think if we limit it to the size you've mentioned it'd be compatible with the rest of the drivers as well as webdriver.

**Comment by Will-Sommers** [comment]
Hey ya'll — is there a timeline for this release?

**Comment by twalpole** [comment]
@Will-Sommers No - no agreement yet on other potential features/changes - need to find some time to go through the other issues on here and see if there's anything we can do about any of them.   The only new feature listed above is the support for maximize which went into master and will likely be released in 1.11 sometime this week.

**Comment by Will-Sommers** [comment]
Cool — thank you for the update.

**Comment by twalpole** [comment]
Since PhantomJS has been abandoned and it looks like v2.5 will never be released, I'm looking at swapping from PhantomJS to Puppeteer for the Poltergeist 2 release.  Work is in progress in the puppeteer branch.  Currently there are a lot of failures around the windows and frames behavior, which are caused by current limitations of Puppeteer, but they are being worked on.
