### ISSUE TITLE
unable to click button on a bootstrap modal

### ISSUE THREAD

**Issue by floydpraveen** [teampoltergeist/poltergeist#748]
test
```ruby
describe "on click of delete" , :js => :true do
            before {
                click_link 'delete-tab',  href: "#delete"
                click_button("Delete Account")
            }

it "click on confirm with empty password gives error" do
                sleep 1
                expect(page).to have_selector('input#deletePassword')
                find_button('Confirm').trigger('click')
                save_screenshot('/Users/praveenkumar/codebase/forks/dashboard/screenshots/modal.png', :full => true)
                expect(page.first('div#errorMsg').text).to eq('invalid password') 
            end
```

unable to get the error message since click on the button which is inside a bootstrap modal is not happening 
screenshot taken during test 
![modal](https://cloud.githubusercontent.com/assets/2039089/13555858/7fae7f86-e3f1-11e5-8ea0-f1c4403bfb20.png)

test failure 
![screenshot 2016-03-06 23 18 45](https://cloud.githubusercontent.com/assets/2039089/13555880/eb80a036-e3f1-11e5-9579-a55326cfb9aa.png)

actual behaviour of modal
![screenshot 2016-03-07 08 52 00](https://cloud.githubusercontent.com/assets/2039089/13560120/ebfa15c4-e441-11e5-93ba-ddf256d117b1.png)

**Comment by twalpole** [comment]
Is this still an issue for you? A lot of issues with bootstrap modals can be solved by conditionally disabling animations in the test environment.

**Comment by twalpole** [comment]
Closing for now, we can reopen if more info is provided
