### ISSUE TITLE
Invisible text is being returned after breaking change 3fc1f4e

### ISSUE THREAD

**Issue by peterox** [teampoltergeist/poltergeist#749]
Commit 3fc1f4e for issue #483 has broken the behaviour of visibleText.

The change now returns:

`@element.innerText || @element.textContent` 

Which means that textContext will be returned if innerText returns both null OR and empty string. 

So if all the text of an element is hidden then the hidden text will now be returned from visibleText.

**Comment by gentaro-sakamoto** [comment]
:+1:

**Comment by peterox** [comment]
Can someone please merge the pull request for this?

**Comment by twalpole** [comment]
Should be fixed via PR #750
