### ISSUE TITLE
Stream closed error

### ISSUE THREAD

**Issue by gpcweb** [teampoltergeist/poltergeist#752]
I am using Capybara for web page scraping and I have a module that executes this line of code when I want to close the phantomjs.

`@session.driver.quit`

This line of code works fine 90% of the time but when the scraping task takes hours (6 or more) that line of code make my code crash.

The error on the sidekiq.log:

`2016-03-16T09:07:04.368Z 28285 TID-ch1b4 WARN: closed stream`

I really don`t know what is happening because it works most of the the time.

**Comment by gpcweb** [comment]
I was able to reproduce this error, every time I exectute `@session.driver.quit` this line of code kills phantomjs but if I run it again the line of code throw the close stream error.

**Comment by route** [comment]
Why do you need to call quit twice?

**Comment by twalpole** [comment]
Closing due to lack of response
