### ISSUE TITLE
Javascript not Execute

### ISSUE THREAD

**Issue by Uysim** [teampoltergeist/poltergeist#753]
Gemfile.rb

group :test do
  gem 'poltergeist',          '~> 1.9.0'
end

spec_helper.rb
require 'capybara/poltergeist'
Capybara.javascript_driver = :poltergeist

I just do a bit with js
alert('hello');

when I do page.save_screenshot
Image did not show any alert at all.
So I think my javascript did not not executed.

Phantomjs 2.1.1
Capybara 2.6.2
Poltergeist 1.9.0
Rails 4.2.2

**Comment by Uysim** [comment]
I found the solution it is because one of my team run rake asset:precompile and test always serve that assets

**Comment by PirunSeng** [comment]
@Uysim would you mind telling me how you solve the problem please?

I've just upgraded Capybara to 2.15.4 recently, and that caused saving screenshot to stop working. I feel like there are some dependencies problems between Capybara and Poltergeist.

```
Capybara 2.15.4
Poltergeist 1.9.0
```

**Comment by Uysim** [comment]
@PirunSeng Make sure that your Phantomjs the latest version

**Comment by PirunSeng** [comment]
@Uysim my Phantomjs is 2.1.1.
