### ISSUE TITLE
Caching and redirects can result in poltergeist thinking the document is empty

### ISSUE THREAD

**Issue by fcheung** [teampoltergeist/poltergeist#754]
Hi,

I've run across a weird issue where when a response is cached (304 not modified) poltergeist seems to think the document is empty (calls to `find` fail, `page.driver.body` is `<html><head></head><body></body></html>`). I've come up with a small reproduction script

``` ruby
ENV['RACK_ENV'] = 'test'
require 'sinatra'
require 'rack/cache'
require 'capybara'
require 'capybara/dsl'
require 'test/unit'
require 'capybara/poltergeist'

use Rack::Cache, {verbose: false}

get '/' do
  cache_control "no-cache"
  redirect to('/1')
end

get '/1' do
  cache_control "no-cache"
  redirect to('/2')
end

get '/2' do
  headers['Etag'] = 'dummy'
  cache_control "max-age=0, private, must-revalidate" 
  "<span>Hello World</span>"
end

Capybara.server_port = 12345

Capybara.app = Sinatra::Application.new

class HelloWorldTest < Test::Unit::TestCase
  include Capybara::DSL
  Capybara.default_driver = :poltergeist
  def test_it_works
    visit '/'
    find('span')
  end

  def test_it_still_works
    visit '/'
    find('span')
  end
end
```

When I run this ruby file (ruby 2.3.0, poltergeist 1.9, phantom js 2.1.1, OS X 10.11), the first test passes, but the second one fails (Capybara::ElementNotFound: Unable to find css "span"). If I stop caching occurring, (by commenting out the line that sets the Etag header), then both tests pass, which is why I believe this to be caching related.

It's also related to the redirects - if there is only redirect (change the tests to `visit '/1'`) or no redirects (change the tests to `visit '/2'`) then the tests pass.

A clear browser cache method (as in #719) might help, but it feels like a bandaid.

I'm not at all familiar with the internals of poltergeist, so I don't know if this is a phantomjs issue or a poltergeist issue, but obviously happy to take this upstream if that is the case (some help on reproducing this without poltergeist would be useful though!)

**Comment by afn** [comment]
I've encountered this as well, only after updating phantomjs from 1.9.8 to 2.1.1.

**Comment by twalpole** [comment]
This appears to be a phantomjs issue. master branch (will be 1.10.0) now supports calling clear_memory_cache which can be called after/before each test to work around the issue if needed.  Another option if you actually want the caching to work is to pass the phantomjs_option  --disk-cache=true, which (as the name implies) caches to disk and appears to work correctly.
