### ISSUE TITLE
save_screenshot wont save data when filename doesn't end with .png

### ISSUE THREAD

**Issue by sethwoodworth** [teampoltergeist/poltergeist#758]
Steps to reproduce:
```
session.visit('http://asdf.com')
session.save_screenshot('/tmp/this_is_a_file_with_no_ending')
```

This would be particularly helpful when using a `Tempfile` to generate a filename.  This can be worked around by explicitly appending a suffix `Tempfile.new(['screenshot', '.png'])`.  But ideally `save_screenshot` would either save, throw an error, or have the behavior documented

**Comment by simi** [comment]
Hello @sethwoodworth!

I just tried a quick test inspired by upstream [screen capture docs](http://phantomjs.org/screen-capture.html).

```javascript
var page = require('webpage').create();
page.open('http://github.com/', function() {
  page.render('github'); // works with github.png
  phantom.exit();
});
```

Following code also results in no data saved. I think this problem is in [phantomjs](http://phantomjs.org/). Can you please open issue there?

**Comment by simi** [comment]
Finally this is not a bug.

see [phantomjs render docs](http://phantomjs.org/api/webpage/method/render.html).

**Comment by simi** [comment]
I've prepared PR to support (similar API to [phantomjs render](http://phantomjs.org/api/webpage/method/render.html)):

```ruby
session.save_screenshot('/tmp/this_is_a_file_with_no_ending', format: 'png')
```
