### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by nqtien310** [teampoltergeist/poltergeist#761]
I followed the instruction to setup Poltergeist for my Cucumber specs, but end up in a Permission Denied error.
````Permission denied - /usr/local/lib/node_modules/phantomjs (Errno::EACCES)````

Any help would be highly appreciated 👍

**Comment by route** [comment]
Looks like you installed phantomjs with node which is kinda weird, download and binary to any place in your PATH variable http://phantomjs.org/download.html
