### ISSUE TITLE
select_file doesn't work as expected with phantomjs 2.1.1

### ISSUE THREAD

**Issue by siassaj** [teampoltergeist/poltergeist#762]
https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/browser.rb#L102

Attempting to use the following command with capybara 2.7.0, poltergeist 1.9.0 is acting inconsistently accross phantomjs versions.

```ruby
attach_file "my_file_input", "/path/to/image.png"
```

On phantomjs 2.1.1 this returns true however the elements ```$('#my_file_input')[0].files.length``` returns 0
On phantomjs 1.9.2 this returns true and  ```$('#my_file_input')[0].files.length``` returns 1, and ```$('#my_file_input')[0].files[0]``` returns the correct file

ruby is 2.2.3

**Comment by twalpole** [comment]
`attach_file` is tested in the capybara specs and poltergeist passes those with 1.9.8 and 2.1.1 -  If you can provide a minimal test case that shows the error we can try and track down whats causing it for you, otherwise it's most likely something in your JS or your JS interaction with phantomjs

**Comment by siassaj** [comment]
@twalpole very bizarre. I'll investigate further. Thank you

**Comment by siassaj** [comment]
Ok i just create a skeleton app to test this, works with 1.9.8 and breaks with 2.1.1

https://github.com/siassaj/phantomjs-test-app

**Comment by twalpole** [comment]
@siassaj  That example passes for me with 2.1.1  - Maybe your phantomjs 2.1.1 is screwed up?? Try reinstalling it.

**Comment by siassaj** [comment]
0_0

**Comment by twalpole** [comment]
For more info - I'm running on OSX using the phantomjs 2.1.1 installed by homebrew

**Comment by twalpole** [comment]
And I just tried the binary downloaded from phantomjs.org and that works fine too

**Comment by siassaj** [comment]
Ok i'm checking now. I used the ubuntu repo so i'll download the binary

**Comment by twalpole** [comment]
One aside to note -- in your test you're raising if the return of attach_file isn't truthy ---  attach_file doesn't actually have a declared return type so with some drivers it may actually return nil on success so raising based on its return isn't really valid.

**Comment by siassaj** [comment]
Yeah i wanted to catch any weirdness with that, just in case.
Anyway lesson learnt, the apt repo for phantom is giving me something broken. I'll take it up with them. Now i need to go figure out why phantom's being a jerk on our macs.
Thanks for your help
