### ISSUE TITLE
Zoom Factor should be documented

### ISSUE THREAD

**Issue by connorshea** [teampoltergeist/poltergeist#766]
I can't seem to get zoom factor to work. Implemented in #428 it's not really documented anywhere except in that PR and in the code itself.

The option should be documented so noobs like me can find and use it :)

**Comment by route** [comment]
PRs are always welcome

**Comment by twalpole** [comment]
zoom factor can be set via  `page.driver.zoom_factor= desired_zoom # 1= 100%, 0.25 = 25%, etc`  - it is documented here - http://www.rubydoc.info/gems/poltergeist/Capybara/Poltergeist/Driver#zoom_factor%3D-instance_method

As @route stated - PRs to improve documentation are always welcome
