### ISSUE TITLE
TimeoutError when using within_frame and yield in separate method

### ISSUE THREAD

**Issue by mwjeffcott** [teampoltergeist/poltergeist#772]
I'm trying to use Poltergeist to test some functionality within an iframe, but I'm getting TimeoutErrors when calling within_iframe in certain ways.

My test is calling something like this:
```ruby
within_launcher_iframe do
  LauncherPage.click_button
end
```
where `within_launcher_iframe` is defined as
```ruby
def within_launcher_iframe
  wait_for_ajax
  expect(page).to have_css("iframe[id='launcher']")
  within_frame('launcher') { yield }
end
```

When executing this test, I am getting the following debug info before it errors out:
```
{"id":"9d65f8a3-952d-4255-a67f-79001e8ea06b","name":"evaluate","args":["jQuery.active"]}
{"command_id":"9d65f8a3-952d-4255-a67f-79001e8ea06b","response":0}
{"id":"79c57720-9d86-4638-9f24-575707765dbc","name":"find","args":["css","iframe[id='launcher']"]}
{"command_id":"79c57720-9d86-4638-9f24-575707765dbc","response":{"page_id":3,"ids":[0]}}
{"id":"e1516d30-51d9-4cfa-91fd-cf5f7e86f960","name":"visible","args":[3,0]}
{"command_id":"e1516d30-51d9-4cfa-91fd-cf5f7e86f960","response":true}
{"id":"3d827dd4-0050-4a48-b718-01efbff749c9","name":"push_frame","args":["launcher"]}
{"id":"04ab4929-17f2-49fd-aa0c-75ca9bff9075","name":"pop_frame","args":[]}
{"command_id":"04ab4929-17f2-49fd-aa0c-75ca9bff9075","response":true}
F

Failures:

  1) Web Widget HC Search Blips should have the correct format
     Failure/Error: within_launcher_iframe do
     Capybara::Poltergeist::TimeoutError:
       Timed out waiting for response to {"id":"3d827dd4-0050-4a48-b718-01efbff749c9","name":"push_frame","args":["launcher"]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker.
     # /Users/mjeffcott/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.9.0/lib/capybara/poltergeist/web_socket_server.rb:99:in `rescue in send'
     # /Users/mjeffcott/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.9.0/lib/capybara/poltergeist/web_socket_server.rb:95:in `send'
     # /Users/mjeffcott/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.9.0/lib/capybara/poltergeist/server.rb:38:in `send'
     # /Users/mjeffcott/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:344:in `command'
     # /Users/mjeffcott/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:134:in `within_frame'
     # /Users/mjeffcott/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.9.0/lib/capybara/poltergeist/driver.rb:145:in `within_frame'
     # /Users/mjeffcott/.rvm/gems/ruby-2.2.3/gems/capybara-2.4.4/lib/capybara/session.rb:327:in `within_frame'
     # /Users/mjeffcott/.rvm/gems/ruby-2.2.3/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/support/widget_helper.rb:218:in `within_launcher_iframe'
     # ./spec/features/channels/widget/api_headless/widget_help_center_search_blip_spec.rb:11:in `block (2 levels) in <top (required)>'
     # /Users/mjeffcott/.rvm/gems/ruby-2.2.3/gems/rspec-wait-0.0.6/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
     # /Users/mjeffcott/.rvm/gems/ruby-2.2.3/gems/rspec-retry-0.4.3/lib/rspec/retry.rb:53:in `block (3 levels) in apply'
     # /Users/mjeffcott/.rvm/gems/ruby-2.2.3/gems/rspec-retry-0.4.3/lib/rspec/retry.rb:44:in `times'
     # /Users/mjeffcott/.rvm/gems/ruby-2.2.3/gems/rspec-retry-0.4.3/lib/rspec/retry.rb:44:in `block (2 levels) in apply'

Finished in 2 minutes 15.8 seconds (files took 1.58 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/features/channels/widget/api_headless/widget_help_center_search_blip_spec.rb:8 # Web Widget HC Search Blips should have the correct format


1 example, 1 failure

Took 138 seconds (2:18)
Tests Failed
```
I have experimented with different timeouts and with taking screenshots to verify what's on the page. The iframe I'm looking for is definitely present on the page, so the TimeoutError isn't coming from that.

Curiously, if I change my test to just do the following without the external method, it works fine:
```ruby
within_frame('launcher') do
  LauncherPage.click_button
end
```
The problem with this approach is that a second `within_frame` block after that fails. These different failures are happening every time. I am unable to find a workaround for this issue, nor do I know where to begin trying to fix this. Does anyone know either a) how I might get around these issues? or b) what's involved in fixing this?

**Environment details**
OS X El Capitan 10.11.4
Poltergeist 1.9.0
PhantomJS 2.1.1

**Comment by twalpole** [comment]
try rewriting as

    def within_launcher_iframe
      within_frame(find(:css, "iframe#launcher")) { yield }
    end

and see if it makes a difference

**Comment by mwjeffcott** [comment]
@twalpole Thanks for the quick response. I tried your suggesting for `within_launcher_iframe` but unfortunately it didn't solve the problem.

From the debug log, it's hanging on this command: `{"id":"8b20517c-a3fd-4864-9e3b-033d66a3786b","name":"push_frame","args":[[3,0]]}` before it ends with the TimeoutError.

Regarding the iframe url suggestion - the iframe we're using doesn't work in that way. We load an external JS file on page load, which handles creating the iframe and its logic. We're also using this in the iframe if it's any help: https://facebook.github.io/react/tips/dangerously-set-inner-html.html

**Comment by twalpole** [comment]
ok -- that may explain your issue then - If the frames url is 'about:blank' poltergeist waits for it to change so it knows the frame has loaded - if that never changes then poltergeist will timeout - Is location.href for the frame 'about:blank'? and can your code set it to something else once it's built it?

**Comment by mwjeffcott** [comment]
The location.href is in fact about:blank. The downside is that we're not able to change anything in our iframe so that the url gets updated. I tried doing this manually, and it caused the iframe to disappear from the page.

I haven't looked at the Poltergeist source yet to know, but is it possible to add another mechanism for determining an iframe has loaded?

**Comment by twalpole** [comment]
@mwjeffcott another mechanism could be implemented, if we can figure one out, no guarantee on timeframe though.  I'm assuming your iframes src attribute is blank/non-existent? If so maybe we could just skip waiting for load if src is empty - do you use the Iframes srcdoc attribute for setting your frames content?

**Comment by mwjeffcott** [comment]
@twalpole Correct - we don't have the src attribute set on our iframes. Skipping the wait would work - we have other things in our iframes/JS that I can use to check it's loaded. We're not using srcdoc either.

**Comment by mwjeffcott** [comment]
@twalpole If you want an example of the iframes I'm trying to access, head to https://developer.zendesk.com/ and use the iframe with CSS `iframe#launcher`.

**Comment by twalpole** [comment]
@mwjeffcott Can you test with the master branch and see if that solves it for you?

**Comment by mwjeffcott** [comment]
@twalpole That does solve my issue, thanks so much! How long would it be until it's pushed in a proper release?

**Comment by twalpole** [comment]
Not sure -- depending on the other PRs in the queue I may push a release this weekend - we'll see

**Comment by mwjeffcott** [comment]
No problem - I'll just reference that commit on master for now, and update to the release when it happens. Thanks again!

**Comment by ahar** [comment]
I have the same issue with capybara 1.17.0. 

Do @twalpole you changed smth? 

Actual error is: 
Capybara::Poltergeist::TimeoutError: Timed out waiting for response to {"id":"5ba877d3-d8fc-40ff-8e33-d3d4796767c5","name":"push_frame","args":[[6,357]]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker.

**Comment by twalpole** [comment]
@ahar Since it fixed the OP problem and the issue was closed, obviously something was changed (the change was even linked in this issue).  If you're having a similar problem then please open a new issue with enough detail to reproduce and/or debug it, along with what you have attempted to fix it.  The error alone doesn't tell us very much.
