### ISSUE TITLE
Unintuitive behaviour of `page.status_code`

### ISSUE THREAD

**Issue by danyalaytekin** [teampoltergeist/poltergeist#776]
We have a feature:

```
@smoke @acceptance
Scenario: Home page is available
  When I visit the home page url
  Then I expect no error code
```

With the final line implemented as:

```
Then(/^I expect no error code$/) do
  expect(page.status_code).to eq 200
end
```

This sometimes fails.  When debugging we've found the following:

- the page itself _always_ responds with `200`
- however, one resource within the page sometimes responds with `204` (which causes the test to fail)

This suggests that `page.status_code` does not equal the status code of the actual URL requested, but could be set to the status code of any (or presumably the last?) of the resources requested by the page.

Is this the correct explanation, and is it the expected behaviour of `page.status_code`?

Notes:

- I realise that `204` could be construed as success, but this is not the focus of this issue

**Comment by twalpole** [comment]
The status code returned should be that of initial page request (or redirected request) -- can you provide the output of page.driver.network_traffic when this occurs so we can see what requests were made?

**Comment by twalpole** [comment]
Closing due to lack of response
