### ISSUE TITLE
setting javascriptEnabled to true

### ISSUE THREAD

**Issue by jcreencia** [teampoltergeist/poltergeist#778]
I need to set PhantomJS with the following: 
`phantom.javascriptEnabled = true`
`page.settings.javascriptEnabled = true`

Is there a way I can do this through Poltergeist?

Thanks.

**Comment by twalpole** [comment]
There is no way for a user to change those settings, but they are `true` by default so I'm not sure why you would need to set them again?

**Comment by twalpole** [comment]
Closing due to lack of response
