### ISSUE TITLE
Timeout in minutes( docs fix )

### ISSUE THREAD

**Issue by rusikf** [teampoltergeist/poltergeist#779]
It looks, that we can specify timeout for poltergeist not only in seconds, but also in munutes, like this:
```ruby
Capybara.register_driver 'poltergeist' do |app|
options = {
  timeout: 5.minutes
}
Capybara::Poltergeist::Driver.new(app, options)
```
May be we can notice about this in readme?

**Comment by twalpole** [comment]
Numeric#minutes is a method provided by ActiveSupport and basically just multiples the number by 60.  No need to document this in poltergeist.
