### ISSUE TITLE
upgrade phantomjs

### ISSUE THREAD

**Issue by naw** [teampoltergeist/poltergeist#782]
I thought it might be good to upgrade phantomjs to 2.1.1, possibly to reduce intermittent spec failures on CI.

With the upgrade, locally I'm seeing several  `PhantomJS client died while processing` errors.  

Turns out this is related (possibly indirectly) to the hot module reloading plugin used when we use webpack dev server.  Errors go away when we run specs against the a compiled bundle.

I'm going to hold off for now, but wanted to record my notes.

**Comment by twalpole** [comment]
Poltergeist is tested on Travis with phantomjs 2.1.1 and overall is much more stable than 1.9.8 ever was

**Comment by adamnbowen** [comment]
It sounds likely that this is caused by the hot module reloading plugin—if it still happens, perhaps open an issue for that project, but this issue should be closed.

**Comment by naw** [comment]
I agree this should be closed. My apologies for filing this on the wrong project and generating noise.  I meant to post this to a private repo, and it definitely wasn't my intention to imply any kind of bug in poltergeist --- just had the wrong window open, I guess. Human error.
