### ISSUE TITLE
intermittent Poltergeist.MouseEventFailed: click

### ISSUE THREAD

**Issue by jasonfb** [teampoltergeist/poltergeist#785]
intermittent failure on one of my specs

Capybara::Poltergeist::BrowserError:
     #   There was an error inside the PhantomJS portion of Poltergeist. If this is the error returned, and not the cause of a more detailed error response, this is probably a bug, so please report it. 
     #   
     #   Poltergeist.MouseEventFailed: click

**Comment by twalpole** [comment]
What versions of poltergeist and phantomjs are you using?  MouseEventFailed is usually raised when the element you're trying to click on has another element covering it -- try taking a screenshot and seeing if the element is covered -- or is being animated into view -- conditionally disable animations in the test environment.  If neither of those suggestions help you'll need to provide at least the full error message

**Comment by jasonfb** [comment]
Everything reported on https://github.com/teampoltergeist/poltergeist/issues/781 is relevant here, this is in fact the exact same spec. 

Full details coming soon. Sorry sometimes I open issues before completing all notes...

**Comment by jasonfb** [comment]
Full spec failure: 
https://gist.github.com/jasonfb/ecb20c7979e1e2cecc18e9a78794eb07

full gemfile.lock
https://gist.github.com/jasonfb/846fc51852a0436fea2be1f0f1a0ecf2

poltergeist (1.9.0)
phantomjs (2.1.1.0)

Animations are definitely involved in my app -- we love animations. We have them all over the place. I will do some debugging now to see if I can look for that. Yes, it sounds like animations.

**Comment by jasonfb** [comment]
@twalpole -- how do you recommend I disable animations? I found this just now: https://gist.github.com/andyjbas/9962218

any better way to do this?

**Comment by jasonfb** [comment]
actually I'm fairly certain I know already what the problem is:

```
      find("#header-cart-icon").click
      within('#mini-cart-drawer') do
        click_button "Checkout"
      end
```

There is a 0.5 sec animation between these two lines of code, and I had no mechanism to tell the test runner to pause. When I add a ```sleep 1``` after the ``` find("#header-cart-icon").click``` line, it looks like it works.

**Comment by jasonfb** [comment]
I spoke too soon. Still intermittent with ```sleep 1```

I'm trying ```sleep 2``` now. Since it is intermittent it's hard to know when it's actually gone

**Comment by twalpole** [comment]
How to disable animations depends on what you're using for the animations -- for instance jQuery.show() performs an animation which can be disabled by setting `jQuery.fx.off = true` , boostrap has `$.support.transition = false`, etc...

**Comment by jasonfb** [comment]
Right ok, makes sense. We use a mix, So basically, the answer is, do it at the JS/CSS level, which I can do.

**Comment by jasonfb** [comment]
Looks like it is better with the ```sleep 2```. Also I think I have some initialization timing problems --- my app takes a small sec before it initializes all its view objects. To get around this, I'm using a the self explanatory:

```
def wait_for_mw_app
  counter = 0
  while page.evaluate_script("typeof(MW.app) === 'undefined' ||  typeof(MW.app._initialized) === 'undefined'")
    counter += 1
    print "~"
    $stdout.flush
    sleep(0.1)
    raise "MW.app not initialized after 10 seconds." if counter >= 100
  end
end
```

**Comment by jasonfb** [comment]
this has been fixed using wait_for_ajax and specialized wait for app as explained above. 

**SOLVED**
