### ISSUE TITLE
seeing run order lockup issues (Capybara::Poltergeist::TimeoutError) on full test runs; also spilling over into non-poltergeist test suite

### ISSUE THREAD

**Issue by jasonfb** [teampoltergeist/poltergeist#789]
poltergeist (1.9.0)
phantomjs (2.1.1.0)

I am seeing my entire test suite lock-up about halfway through when run through end-to-end. 

Capybara::Poltergeist::TimeoutError:
              Timed out waiting for response to {"id":"946c02fa-5300-42bb-a37e-179be5baf5bb","name":"reset","args":[]}.

the full run looks like so:
https://gist.github.com/jasonfb/d4a002f9e7a280d5a7fec8b449433be6

please note I recently added:
• Wait for ajax
• Sleeps
• Mechanisms to wait for the app's own initialization

Interestingly, you will notice that it looks like failures are thrown on non-Javascript specs (model specs), which shouldn't be dependent on Poltergeist at all

**Comment by jasonfb** [comment]
looks like all test failures are hiccuping on a single line

```
  config.after(:each) do
    Spree::User.auditing_enabled = false # if we don't disable auditing we run into a StackLevelTooDeep
   Capybara.reset_sessions!
    Warden.test_reset!
  end
```

it appears to be failing on the ```Capybara.reset_sessions!```. I have disabled this line and am re-running. 

Should I not be explicitly resetting sessions like this? Note this code was recently upgraded from older versions of capybara, poltergeist, etc.

**Comment by twalpole** [comment]
You shouldn't be doing anything with Capybara/poltergeist in specs that don't use it.  If you've required [capybara/rspec](https://github.com/jnicklas/capybara/blob/2.7_stable/lib/capybara/rspec.rb#L19) then the sessions should already be being resetting where needed, if you're not using that file, for some reason, then you need to configure your after block to only run when the Capybara::DSL is used for the tests - You can do that like in the mentioned file, or with something like  

    config.before(:type => :feature) do  # assuming your capybara tests are of type :feature
        do_whatever
    end

**Comment by twalpole** [comment]
Once you've removed the extraneous resetting of sessions, then try running just one of the tests thats failing visit with a timeout.  If it still fails then try catching the error and dumping the full network_traffic info  for that test since that might give some indication of whats going on (unless it's somehow hung poltergeist/phantomjs in which case we'd have no clue)

**Comment by twalpole** [comment]
@jasonfb  - Also, could you try the visit_closure branch and see if that makes a difference in the errors you get when visit hits a timeout - grasping at straws here.
