### ISSUE TITLE
Strange Javascript error when using PhantomJS driver

### ISSUE THREAD

**Issue by volkanunsal** [teampoltergeist/poltergeist#790]
I'm seeing some Javascript errors that only happen in PhantomJS and trying to puzzle out why that might be. Here is the error message:

```
SyntaxError: Unexpected token ','
           at http://localhost:8080/assets/App.js:5296 in eval
           at http://localhost:8080/assets/App.js:5296
           at http://localhost:8080/assets/common.js:51 in __webpack_require__
```

This comes from a file loaded from a different port. The test runner is on port 9876, and the files are loaded from 8080. Could that be the reason? I can't figure out why it works on Chrome and only fails in PhantomJS. Does anyone know?

**Comment by twalpole** [comment]
Most likely you're using new syntax (ES6?) thats not supported by PhantomJS.  Whats at that line of App.js?  Note also that requests to a different server can't be tracked by Capybara which is okay as long as they're just for assets but will can create all sorts of issues if those requests interact with the database.

**Comment by volkanunsal** [comment]
That's strange. I do use ES6, but Babel compiles it to ES5. Here is the line in question:

https://gist.githubusercontent.com/volkanunsal/d1cadef212d88d87c6e29518047eebba/raw/95d75b5780221eeb8d4feb8a557b071af2b0917e/gistfile1.js

I can't find anything wrong with it, but maybe you can pick out a problem there. 

I also tried gzipping the file for production and compressing it –– just to see if that might iron out the issue –– but I got a different error this time. It now complains about not finding a variable, which is actually defined in one of the JS files –– and I never get this error in Chrome.

```
ReferenceError: Can't find variable: bv_form
       ReferenceError: Can't find variable: bv_form
           at http://127.0.0.1:9887/users/sign_in:13
           at http://127.0.0.1:9887/assets/common-3c4910e796947932c803.js:5 in c
           at http://127.0.0.1:9887/assets/common-3c4910e796947932c803.js:5 in fireWith
           at http://127.0.0.1:9887/assets/common-3c4910e796947932c803.js:5 in ready
           at http://127.0.0.1:9887/assets/common-3c4910e796947932c803.js:4 in d
```

Here is a schema of my page layout just to show you how strange this is:

```haml
!!!
%html
  %head
    =javascript_include_tag 'common'
    = javascript_include_tag 'App'
    = javascript_include_tag 'Map'
  %body{class: page_class}
      ...
      :javascript
          bv_form('form')
```

Btw, I'm using PhantomJS 2.0. Should I try upgrading to 2.1?

**Comment by twalpole** [comment]
@volkanunsal Definitely upgrade to 2.1.1

**Comment by volkanunsal** [comment]
@twalpole Just tried it in 2.1.1. Still getting the same error. :(

**Comment by twalpole** [comment]
@volkanunsal It appears the error is being generated because you have a hash with two identical keys being declared -   around  `style: _styles.rowStyle,\n          align: 'center',\n          style: { borderBottom: 'solid 1px #999' }`   -- note how 'style' is repeated -- why phantomjs throws an error there I'm not sure  but I think that is it.

**Comment by volkanunsal** [comment]
@twalpole Yes, that was definitely the issue.

**Comment by volkanunsal** [comment]
@twalpole I wonder if there is a way to get a backtrace from PhantomJS in the event of a crash? I'm now getting a DeadClient error and want to file a bug report, but all I can see is the backtrace from Capybara...

**Comment by twalpole** [comment]
@volkanunsal Turning on debug mode in poltergeist and phantomjs (phantomjs_options  --debug=true)  should give some more info.   Closing this issue since it's not a poltergeist issue.
