### ISSUE TITLE
run this in chrome instead of phantomjs???

### ISSUE THREAD

**Issue by catmando** [teampoltergeist/poltergeist#793]
I can't run our software with chromedriver because of a conflict between opalrb and the chromedriver.  Been waiting for a fix (it has to be in chromedriver) for a year.

So I am thinking why can't I run the client side of this (+/-) in chrome, and just include whatever code is needed when I boot up my app.   Given I am loading opalrb plus lots of other stuff, having some kind of js driver sitting on the browser in addition would not hurt my feelings.

Plus this would. 

sorry if there was a better place to ask this question....

**Comment by twalpole** [comment]
The client code depends on the PhantomJS api.
