### ISSUE TITLE
Allow XPath selector in save_screenshot

### ISSUE THREAD

**Issue by beneills** [teampoltergeist/poltergeist#794]
## Summary

`save_screenshot` takes an options `Hash`, which may include a 
`:selector` value.  This is used to calculate a _clipRect_ for the screenshot, and is interpreted as any supported CSS selector.

However, in contrast to other parts of the Poltergeist API, it does not seem possible to use XPath selectors in this context.  I have tried changing the `default_selector` config option to no avail, and know of no other way to force XPath use.

**XPath selection is desirable, since the set of XPath-selectable elements strictly contains the set of CSS-selectable elements.**
## Reproduction Steps

``` ruby
require 'capybara'
require 'capybara/poltergeist'

Capybara.register_driver :poltergeist do |app|
  Capybara::Poltergeist::Driver.new(app, :js_errors => false)
end

Capybara.javascript_driver = :poltergeist
Capybara.run_server = false
Capybara.default_selector = :xpath

session = Capybara::Session.new(:poltergeist)
session.visit('https://www.wikipedia.org/')
session.save_screenshot 'en-link-box.png', :selector => '//div[@id="js-link-box-en"]'

# inspect en-link-box.png and see that the selector failed and we have the whole page
```
## Solution
- I'm unsure at what level this has to be first addressed: perhaps a PhantomJS change is required.
- **I'll submit a pull request to clarify the current limitation in the README.**
- A temporary solution is to manually compute the clipping rectangle, using [this](https://github.com/teampoltergeist/poltergeist/blob/39894c8d7373dd55e777677995efd298833da595/lib/capybara/poltergeist/client/compiled/web_page.js#L376) Javascript function, then crop the full screenshot image, as `save_screenshot` doesn't accept `:width` or `:height` either.

**Comment by twalpole** [comment]
This has nothing to do with PhantomJS, it's just the way the selector option is implemented.  Adding xpath would require agreement on how to specify it in a non ambiguous fashion, best solution may be to just allow passing an element which can then be found using any of Capybaras finders

**Comment by twalpole** [comment]
Closing this because a CSS selector works just fine, if someone wants to implement passing in an element we will consider the PR
