### ISSUE TITLE
Tips on debugging drag_to failure

### ISSUE THREAD

**Issue by brendon** [teampoltergeist/poltergeist#798]
I've been having trouble getting https://github.com/isocra/TableDnD working with `drag_to` in my application tests.

I was wondering if someone could give me some tips on how to debug this problem? I've made sure that I'm targeting the correct element and dragging it to the appropriate place. I've also tried dragging it to far above where I want it (in order to move the item to the top of the list). It all results in nothing moving at all.

I've tried using the debug webkit console but I can't see how I'd emulate the drag_to command from here (via javascript?).

I've also tried to change the display type of the element I'm dragging: block, inline-block, inline etc...

Also tried setting the viewport larger as per a previous closed poltergeist issue.

Any tips would be appreciated :)

**Comment by twalpole** [comment]
From a quick look (so I could be missing something) at the TableDnD library it appears that the actual moving of the rows only occurs in the mousemove handler.  This won't work with poltergeist currently since when you call drag_to it just emits a mousedown  event in one location and then a mouseup in another with no move between

**Comment by brendon** [comment]
Thanks @twalpole, that's a good idea. Just out of interest, did you use the 'handle' functionality in your test or were you dragging the whole row?

**Comment by twalpole** [comment]
@brendon My test was very basic so just the whole row -- I'll swap it to use a handle and report back in a bit

**Comment by twalpole** [comment]
@brendon seems to work fine with 'handle' functionality too - https://gist.github.com/twalpole/64c090941bfba5d5e35843a180460bba

**Comment by brendon** [comment]
Thanks @twalpole, your assistance helped point me in the right direction.

The problem ended up being that I only had two items in my table and dragging the bottom item to the top item doesn't seem to actually move the bottom item.

The solution was to have three items in the table, drag the bottom item to the top item, and this would place the dragged item in between the top and bottom item. That's good enough proof that the drag and drop works.

Thanks again! A total time saver! :) Do you accept donations? I'd be happy to flick you some coin.

**Comment by twalpole** [comment]
@brendon You're welcome, no need for donations, but if you know anyone looking to hire I am in the market currently.

**Comment by brendon** [comment]
Thanks @twalpole, being out here in NZ I'm not much in touch with other Rails/Ruby businesses but I'll if I hear of anything I'll let you know :) What kind of job would you be looking for? Full/part time?

**Comment by twalpole** [comment]
@brendon Ah -- hadn't looked at your bio to see NZ - Been running dev teams for quite a while and looking for a new full-time opportunity, but wanting to stay in southern California. Only just starting to look though.

**Comment by brendon** [comment]
That's all good :) It never hurts to ask anyway hey? Good luck with your search and if I happen to hear or something I'll let you know :)
