### ISSUE TITLE
Poltergeist throws js error for React warnings

### ISSUE THREAD

**Issue by moimael** [teampoltergeist/poltergeist#802]
Hi,

When React throws warnings, poltergeist interpret them as JS errors, which makes the tests breaks. Any way to ignore warning without setting js_errors to false (I'd like to keep the real errors but not the warnings) ?

Thanks !

**Comment by twalpole** [comment]
The errors being shown are what are passed to the phantomJS `onError` function  http://phantomjs.org/api/webpage/handler/on-error.html - If that is actually being called with anything that isn't an actual error it seems like a bug in phantomjs - or possibly react issues its warning throuw console.error ?  Either way there's nothing Poltergeist can do about it, although I believe if you use the production version of react it disables warnings.

**Comment by sbleon** [comment]
React does throw warnings as errors, presumably because the React team wants you to have a stack trace to figure out where the problem is.

I wonder if there's a way to filter errors such that if they start with "Warning:" they are suppressed but otherwise they are raised as exceptions.

**Comment by twalpole** [comment]
@sbleon Poltergeist can't be in the business of parsing messages from different libraries to try and determine if they are really errors or not.  If they are just warnings then they should be output as warnings and not errors.

**Comment by sbleon** [comment]
Thomas, I completely agree. I was thinking more of injecting a custom onError() somewhere in my test suite setup.
