### ISSUE TITLE
Native drag and drop support

### ISSUE THREAD

**Issue by aom** [teampoltergeist/poltergeist#803]
Poltergeist is lacking support for native HTML5 Drag and Drop Events. It seems that it's expecting site to listen for **mouseup → mousedown** events. Most libraries do use these events for maximum backward compatibility. 

My case is using native events on top of vanilla – coffeescript – JavaScript. Where we expect minimum of **dragstart → dragover → drop**. 

Related: https://github.com/teampoltergeist/poltergeist/issues/798

Failing example: https://gist.github.com/aom/0100e66f708951120b79ab5e887b609a

**Comment by twalpole** [comment]
PRs welcome - even if just test cases that fully test the correct behavior :)

**Comment by twalpole** [comment]
PhantomJS doesn't produce drag/drop events and there's nothing Poltergeist can really do about that.

**Comment by aom** [comment]
Too bad :( `mousemove` is here to stay.
