### ISSUE TITLE
Timed out waiting for response

### ISSUE THREAD

**Issue by pcsgithubid** [teampoltergeist/poltergeist#804]
i get the below time out error when i execute the command save_and_open_opage

ruby-2.2.2
phantomjs 2.1.1.

[1] pry(#<RSpec::ExampleGroups::TadDeal>)> save_and_open_page
Capybara::Poltergeist::TimeoutError: Timed out waiting for response to {"id":"fe37472e-cc7f-416f-b401-a934e0ac4c8c","name":"body","args":[]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker.
from /Users/ChandrasekharPasupuleti/.rvm/gems/ruby-2.2.2@tad/gems/poltergeist-1.9.0/lib/capybara/poltergeist/web_socket_server.rb:99:in `rescue in send'

**Comment by vgvinay2** [comment]
This is a Same issue which I'm Getting while putting `byebug` In between. I'm unable to debug my code :(

**Comment by twalpole** [comment]
Without details, such as the version of Poltergeist being used, and a reproducible example there's nothing we can really troubleshoot.

**Comment by pcsgithubid** [comment]
poltergeist 1.8.0 
ruby-2.2.2
phantomjs 2.1.1.
capybara 2.7.1
pry-rails 0.34

my feature spec is executes succesfully, but when i put binding.pry in the spec and type any capybara commands it gives timeout error.

    125:
    126:
    127:   def i_edit_the_newly_created_deal
    128:     binding.pry
    129:
 => 130:     click_on 'Big Deal'
    131:     save_and_open_page
    132:     binding.pry
    133:     # verify_from_property_0
    134:     # verify_to_property_0
    135:     click_on 'add_shift_from_property'

[1] pry(#<RSpec::ExampleGroups::TadDeal>)> all('a')
{"id":"a0bec0a7-8b28-4e05-a74f-8f8ab95234b4","name":"find","args":["css","a"]}
Capybara::Poltergeist::TimeoutError: Timed out waiting for response to {"id":"a0bec0a7-8b28-4e05-a74f-8f8ab95234b4","name":"find","args":["css","a"]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker.
from /Users/ChandrasekharPasupuleti/.rvm/gems/ruby-2.3.1@tad/gems/poltergeist-1.8.0/lib/capybara/poltergeist/web_socket_server.rb:98:in `rescue in send'

**Comment by twalpole** [comment]
could https://github.com/pry/pry/wiki/FAQ#threads-dont-work-whats-wrong be the issue you're seeing?

**Comment by BandanaPandey** [comment]
@vgvinay2, even I have the same issue, when i used byebug for debugging it shows::
Capybara::Poltergeist::TimeoutError: Timed out waiting for response to {"id":"f9029cd8-7f6c-4944-b05c-33041bdfff36","name":"click","args":[1,19]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details).

And I resolved it by increasing the timeout to higher value by including these lines in my spec file

Capybara.register_driver :poltergeist do |app|
      Capybara::Poltergeist::Driver.new(app, timeout: 2.minute)
end

Hope this works.

**Comment by twalpole** [comment]
Closing due to lack of response
