### ISSUE TITLE
Resize on the fly not working

### ISSUE THREAD

**Issue by ingolfured** [teampoltergeist/poltergeist#805]
I'm trying to resize my browser on the fly the following way

    session = Capybara::Session.new(:poltergeist)
    session.driver.browser.resize(320, 568)

However, it doesn't resize. It just stays `[1024,768]`. Is there any way to resize the browser by calling a method on the`session` object?

**Comment by twalpole** [comment]
Ideally you should be calling `session.current_window.resize_to(320, 567)` rather than using driver specific methods.  However what you have called should work - what are you basing the statement "It just stays [1024,768]" on?

**Comment by twalpole** [comment]
Closing due to lack of response - we can reopen if more info is provided.
