### ISSUE TITLE
send_keys ignores whitespaces

### ISSUE THREAD

**Issue by MarianoSalerno** [teampoltergeist/poltergeist#806]
Using version 1.10 of this gem and phantomjs 2.1.1 in ubuntu 14.04 when I call, for example, input.native.send_keys("Punta Cana") my test fails because the input is filled with "PUNTACANA". 

Digging into the source I found that the problem lies in the keyCode function of the [web page](https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/client/web_page.coffee) script, the name parameter is a whitespace but the key for it in the native().event.key object is named "Space" so I fixed it like [this](https://github.com/MarianoSalerno/poltergeist/commit/04048d2babd3897db00d6d3b18b7a8aef148600a).

I tried with version 1.9.8 of phantom js and latest commit of this project and had the same problem, is this a bug or some problem on my end?

**Comment by twalpole** [comment]
Firstly you should be calling `input.send_keys("Punta Cana")` (no .native) - but other than that it should work fine, and is tested for in the Poltergeist tests.  Does the input element you're sending the keys to have event handlers attached to it that are expecting events we aren't emulating?

**Comment by twalpole** [comment]
Even stranger is that the keyCode function should actually never be called if you're passing a string to send_keys - since the individual characters of the string shouldn't have a `key` property.  I think we'll need a minimal example to debug this.

**Comment by MarianoSalerno** [comment]
Strange, a few days ago it wasn't working but now without the .native bit it works. I'll close the issue for now and reopen it with more info if I can reproduce it again, thanks for the help!
