### ISSUE TITLE
Punctuation marks used with send_keys and modifiers don't create the correct key events

### ISSUE THREAD

**Issue by siruguri** [teampoltergeist/poltergeist#807]
It appears that only the :Shift modifier doesn't work in Poltergeist.

**Environment**

* Poltergeist gem 1.9
* Phantomjs 2.1.1
* OSX El Cap
* Rails 4.2.6

The test code that appears to offend is:

```
   #page.find('#category-text').send_keys [:Shift, '.']
   page.find('#category-text').send_keys [:Alt, 'a']
```

In my code, I allow both shift-. (that is, the > symbol), and _Alt-a_ to perform the same function. Both keys work in the browser (Chrome 50+, OSX), but only the 2nd line above works in the test.

Elsewhere in my code and tests, `:Ctrl` works fine.

Is this something peculiar to how `:Shift` works on an MBP perhaps?

**Comment by twalpole** [comment]
As answered in your stackoverflow question - http://stackoverflow.com/questions/39314352/poltergeist-ruby-gem-fails-to-process-shift-modifier-in-send-keys - it's not actually the :shift that is the answer here, it's the '.'  - PhantomJS doesn't provide a mapping from punctuation marks to keycode in event.key - https://github.com/ariya/phantomjs/commit/cab2635e66d74b7e665c44400b8b20a8f225153a - as a workaround you should be able to use `page.find('#category-text').send_keys [:shift, :period]`.  I'm not sure there is anything Poltergeist can do to fix this - other than storing our own keymap, which I'd rather not do, but I'll look into it.

**Comment by twalpole** [comment]
Fixed via https://github.com/teampoltergeist/poltergeist/commit/28cb0d6fd427424acaddc4800514c13efedcb199
