### ISSUE TITLE
Any plans for slimerjs support?

### ISSUE THREAD

**Issue by mipearson** [teampoltergeist/poltergeist#810]
slimerjs purports to be a nearly API compatible with phantomjs.

Even though it's not properly headless, it using a modern gecko engine is very compelling versus PhantomJS' old (and very unreliable/crashy) qt-webkit engine.

I'm also interested in giving this a go, but I'm curious as to whether anybody else has tried getting it working.

**Comment by route** [comment]
No plans for that and I'd say it had to be a different driver rather than same one. Feel free to use our code base let's see how it goes.
