### ISSUE TITLE
set_cookie is returning Cookie object for attribute instead of passed in value

### ISSUE THREAD

**Issue by chrisjoywebb** [teampoltergeist/poltergeist#812]
Hey all,

We're trying to set an id as a cookie using:

`page.driver.set_cookie(:developer_id, developer.id)` where `developer.id` equals `592400036977969111` in this test.

After setting the cookie, `page.driver.cookies` equals
```
{
"developer_id" =>
#<Capybara::Poltergeist::Cookie:0x007f847c4c1d70 @attributes={"domain"=>"127.0.0.1", "httponly"=>false, "name"=>"developer_id", "path"=>"/", "secure"=>false, "value"=>"5.9240003697796915e+17"}>
}
```

The id is there, but the `developer_id` cookie value is the entire Cookie object.

Any tips would be greatly appreciated!

Running:

Poltergeist 1.9.0
PhantomJS 2.1.1
Capybara 2.7.1
Rails 4.2.6
Ruby 2.1.4

macOS Sierra

**Comment by route** [comment]
Any tips what for?

**Comment by chrisjoywebb** [comment]
Hey sorry. I didn't explain it clearly enough.

Is this the normal behavior for setting a cookie? We're having an issue logging in the user during tests when running `page.driver.set_cookie(:developer_id, developer.id)` where `developer.id` is `592400036977969111`.

Just wondering if what is being returned for `page.driver.cookies` (below) is correct.
```
{
"developer_id" =>
#<Capybara::Poltergeist::Cookie:0x007f847c4c1d70 @attributes={"domain"=>"127.0.0.1", "httponly"=>false, "name"=>"developer_id", "path"=>"/", "secure"=>false, "value"=>"5.9240003697796915e+17"}>
}
```

Or should the returned cookie be
```
{
"developer_id" => "592400036977969111"
}
```

Trying to figure out if the issue is with Poltergeist or somewhere else.

**Comment by twalpole** [comment]
As returned is correct - the cookie needs to store the domain and  other than the fact the value attribute of the cookie may not actually be what you're setting due to numeric conversion.  Try

    page.driver.cookies['developer_id'].value 

and see if that matches what you expect and if it doesn't then you probably want to be calling

    page.driver.set_cookie(:developer_id, developer.id.to_s)

or something like to make sure it gets set correctly.

**Comment by chrisjoywebb** [comment]
Excellent! I'll test this out. Thanks for your help.
