### ISSUE TITLE
Poltergeist at the wrong URL

### ISSUE THREAD

**Issue by pupeno** [teampoltergeist/poltergeist#814]
I have a test that does this:

```ruby
click_link @fan.display_name
click_link "Profile"
click_link "Connect to Twitter"
```

The first link is JavaScript, it opens up a menu in the page. Clicking "Profile" is a normal link that takes to /users/edit. When I click the Connect to Twitter, the HTTP_REFERER is "/organizations/organization-1", an URL from a previous test that is no longer valid. That's where my test crashes.

This works fine in webkit and during manual testing. It's only Poltergeist that's causing this problem. If the tests are run in a different order, then, the problem doesn't happen. Thankfully I have the seed to reproduce this problem (TESTOPTS="--seed=31596").

The whole test looks like this, it tests Omniauth integration that is mocked out:

```ruby
context "In an organization" do
    setup do
      @owner = create(:full_user)
      @organization = create(:organization, owner: @owner)
      visit root_url
    end

    context "as a fan" do
      setup do
        @fan = create(:full_user, organization: @organization, membership_kind: :fan)
        create(:twitter_task, organization: @organization, creator: @owner)
        mock_twitter(@fan)
        log_in(@fan.email)
      end

      should "add Twitter access" do
        click_link @fan.display_name
        click_link "Profile"
        assert_difference "@fan.social_media_accesses.count" => +1 do
           click_link "Connect to Twitter"
        end

        # Not re-add the same one.
        assert_difference "@fan.social_media_accesses.count" => 0 do
          page.visit new_social_media_account_url(provider: "twitter") # Once you have one, the link to connect to twitter is hidden.
        end
      end

      should "add a Twitter access by clicking retweet" do
        puts "Now3 in #{current_path}"
        assert_difference "@fan.social_media_accesses.count" => +1 do
          click_link "retweet"
        end
      end
    end

    context "as the owner" do
      setup do
        mock_twitter(@owner)
        log_in(@owner.email)
      end

      should "add Twitter account" do
        click_link @owner.display_name
        click_link "Social Media Accounts"
        assert_difference "SocialMediaAccount.count" => +1,
                          "@organization.social_media_accounts.count" => +1 do
          click_link "Add Twitter Account"
        end

        # Not re-add the same one.
        assert_difference "SocialMediaAccount.count" => 0,
                          "@organization.social_media_accounts.count" => 0 do
          click_link "Add Twitter Account"
        end
      end
    end
  end
```

I run out of ideas of things to try to figure this out. If you have any ideas, I'll try to provide more information.

**Comment by twalpole** [comment]
Sounds like a caching issue - call page.diver.clear_memory_cache at the beginning of the test

**Comment by pupeno** [comment]
Yes, that fixes it. Why is this happening? am I doing something wrong? I'm already doing Capybara.reset_sessions! at the end of each test.

**Comment by twalpole** [comment]
reset_sessions! doesn't clear the cache because it's nice to have for non-changing things like the assets.  To figure out why you're having the issue you'd have to look at what responses your server is sending and any headers that affect caching ( Etags, etc ) - You might also want to read Issue #754 and Issue #621
