### ISSUE TITLE
Memory leak caused by at_exit handler

### ISSUE THREAD

**Issue by afn** [teampoltergeist/poltergeist#817]
The `at_exit` block registered by `Capybara::Poltergeist::Client` is never unregistered (in fact, there doesn't appear to be a way to unregister `at_exit` hooks), which results in a memory leak: the hook makes a reference to `self` (the `Capybara::Poltergeist::Client`).

Is this block even needed? It seems that the only necessary cleanup work (killing the phantomjs process) is already handled by the finalizer registered via `ObjectSpace.define_finalizer` — and object finalizers are invoked on exit.

I'll submit a PR under the assumption that the block can be eliminated. If there's a reason to keep it, I'll come up with an alternate implementation that avoids the memory leak.

**Comment by twalpole** [comment]
From a quick glance I think you're right, but then the question becomes whether `process_killer` should be more like '#kill_phantomjs' and whether the other things `#stop` does need to be handled

**Comment by twalpole** [comment]
Also, need to verify that the reason for this code being added in the first place isn't necessary any more - https://github.com/teampoltergeist/poltergeist/issues/497

**Comment by afn** [comment]
@twalpole #497 didn't add the `at_exit` hook; it added a thread around the call to `stop` (see the first relevant commit here: 4719294b18251aa911eafa9fd99d3c6ea0e43395).

The `at_exit` hook was added (back) in 73ac614f1448c97c308cab16bfed1346b66f78cb, with the comment

> I'm a bit stupid for not testing it, but Ruby does not automatically
reap the child processes, so without this we get lots of orphaned
processes. Not good!

... but this was a year and half before the `ObjectSpace.define_finalizer` call was added in 6ed8dc805cb2b202a5e2634c4cfe81af59bd779e.

**Comment by afn** [comment]
As for your earlier question, yeah I don't see any reason not to call `kill_phantomjs` from the finalizer. I can rework the pull request to include this change.

**Comment by twalpole** [comment]
@afn Ok -- then it seems like the whole at_exit section can go 👍 .  Obviously you can't just call kill_phantoms from the finalizer since it's an instance method and the whole point of this change is to stop holding a reference to the instance, but reworking process_killer to do what kill_phantomjs is doing and then calling it from kill_phantoms should be workable

**Comment by afn** [comment]
Done - see 6dc84d371c4f3df0e6082090e1c4a631fb5de014.
