### ISSUE TITLE
Attaching files silently fails when using `set`

### ISSUE THREAD

**Issue by stevendaniels** [teampoltergeist/poltergeist#821]
Not really a bug... but, I noticed that poltergeist seems to have odd behavior when trying to attach a file that doesn't exist.
```
session.attach_file("input[type='file']", "/tmp/nonexistent_file") 
# Capybara::FileNotFound: cannot attach file, "/tmp/nonexistent_file" does not exist

input = session.find(:css, "input[type='file']")
input.set("/tmp/nonexistent_file")
# => true
input.value 
# => ""
```
Obviously `set` doesn't do everything that `attach_file` does, but I'd sort of expect that `set` would return false if the value wasn't actually set properly. Is the current behavior the desired behavior?

Here's the HTML I used.
```html
<html>
<head></head>
<body>
    <form id="form_id" action="/test" method="POST">
        File upload
      <label>
        <input id="file_one" type="file" name="file_one">
        Fil
      </label>
      <button type="submit">Next</button>
    </form>
</body>
</html>
```

**Comment by twalpole** [comment]
`#set` doesn't have a defined return type in Capybara < 2.11 - http://www.rubydoc.info/gems/capybara/Capybara/Node/Element#set-instance_method - so the returned value is meaningless.  In 2.11+ it will most likely be defined to return the element `#set` was called on.  Additionally the behavior of calling `#set` directly on a file input with an invalid filename is undefined, and not really supported.  If you want to attach a file to a file input call `#attach_file` - why are you calling `#set` for that?

**Comment by stevendaniels** [comment]
Thanks for the explanation.

In this case, I was calling `#set` directly because I had to deal with situations where the locator might find more than one element. `#attach_file` doesn't support this and `#set` seems to be the crucial call for `#attach_file`

```
# capybara/node/actions.rb @ line 266:
# Owner: Capybara::Node::Actions
# Visibility: public
# Number of lines: 7

def attach_file(locator, path, options={})
  locator, path, options = nil, locator, path if path.is_a? Hash
  Array(path).each do |p|
    raise Capybara::FileNotFound, "cannot attach file, #{p} does not exist" unless File.exist?(p.to_s)
  end
  find(:file_field, locator, options).set(path)
end
```

**Comment by twalpole** [comment]
If the locator would find more than one file then you just need to scope the attach_file call to a wrapper that would make it unique -  Obviously this is something very specific to your page but  something like

```
<html>
<head></head>
<body>
    <form id="form_id" action="/test" method="POST">
        File upload
      <ul>
        <li>        
         <label>
          <input type="file">
          File
        </label>
       </li>
        <li>        
         <label>
          <input type="file">
          File
        </label>
       </li>
      </ul>
        <button type="submit">Next</button>
    </form>
</body>
</html>
```

    find('#form_id li:first-child').attach_file('File', '/tmp/myfile.txt')
