### ISSUE TITLE
Poltergeist doens't work on Ubuntu for Windows 10

### ISSUE THREAD

**Issue by hartator** [teampoltergeist/poltergeist#822]
It's very specific, but I think there is an issue with how Poltergeist and PhantomJS are exchanging information via socket on Ubuntu for Windows 10. Linux subsystem for Windows 10 has an odd way to handle network calls that seems to pose an issue either to Poltergeist or PhantomJS.

I am getting `PhantomJS client died while processing` no matter what version of PhantomJS I am using (Tried with `1.9.0` and `2.1.1`) or Poltergeist (Tried `1.11.0` and `1.9.0`) or driver options I am passing.

Related post on another language driver: https://github.com/karma-runner/karma-phantomjs-launcher/issues/124

**Comment by hartator** [comment]
Debug output: https://gist.github.com/hartator/5a49360381dcdf47fc512f5fa1026b77

**Comment by hartator** [comment]
Found a solution, the `/run/lock` directory was missing, just run `mkdir -p /run/lock`.

**Comment by hartator** [comment]
Never mind; spoke too fast.

**Comment by route** [comment]
@hartator sorry but you have to dig deep on your own haha)) I once tried to run big ruby project on windows, failed and will never do it again. In this case there are plenty of places where bug can lurk (ruby, phantomjs or even arch)

**Comment by mbland** [comment]
FYI, I'm reasonably sure the source of the crash is [the lack of nonblocking `connect()` support in WSL causing a low-level QT error when using WebSockets](https://github.com/Microsoft/BashOnWindows/issues/903#issuecomment-306066510).
