### ISSUE TITLE
`url_whitelist` breaking specs

### ISSUE THREAD

**Issue by kleinjm** [teampoltergeist/poltergeist#828]
Environment: Rails 3.2.13, Ruby 2.1.2, Capybara 2.4.3, Poltergeist 1.11.0

`url_whitelist` causes my specs to run without loading anything. `url_blacklist` on the other hand works. I'd like to do a whitelist strategy so that we don't need to remember to block any new external dependencies.

![image](https://cloud.githubusercontent.com/assets/2565158/20396332/d70378e6-acb3-11e6-895f-7f8e9a6423ad.png)

```
require 'capybara/poltergeist'

Capybara.register_driver :poltergeist do |app|
  options = {
    js_errors: true,
    window_size: [1200, 1000],
    url_whitelist: [
      "http://cdn.jsdelivr.net/lodash/4.12.0/lodash.min.js",
      ...
    ]
  }
  Capybara::Poltergeist::Driver.new(app, options)
end

Capybara.javascript_driver = :poltergeist
```

**Comment by route** [comment]
If you could create a reproducible test that was what would really help

**Comment by twalpole** [comment]
Have you whitelisted your actual apps pages?  Assuming normal setup it would be something like

    url_whitelist: [
      "http://127.0.0.1:*,
      "http://cdn.jsdelivr.net/lodash/4.12.0/lodash.min.js",
      ...
    ]

**Comment by kleinjm** [comment]
That was it, thanks! I had tried something similar but without widecarding the port
