### ISSUE TITLE
Poltergeist selects elements even within template tags

### ISSUE THREAD

**Issue by matstc** [teampoltergeist/poltergeist#829]
I noticed that `querySelectorAll` will include matching elements even if those elements are inside a `template` tag. For example, the following code finds the element:

    document.querySelectorAll('element')

from this HTML:

    <template><element /></template>

This behavior is different from the firefox driver and is somewhat unexpected. I didn't expect the contents of template tags to be searched. Could this be a bug?

I am also seeing poltergeist submitting inputs even if they are within a template tag.

**Comment by twalpole** [comment]
Poltergeist uses phantomjs, the latest release (2.1.1) of which is based on a version of QtWebkit that is roughly equivalent to a browser from 4-5 years ago and as such most likely does not support the `template` element.  Therefore it treats it as just a regular custom element and everything inside it is treated normally.  There is nothing poltergeist can do about that.
