### ISSUE TITLE
PhantomJS crashes intermittently

### ISSUE THREAD

**Issue by justin808** [teampoltergeist/poltergeist#830]
Only when running on Travis (linux), the use of a react animation will crash. 

You can see the [failing build](https://travis-ci.org/shakacode/react-webpack-rails-tutorial/builds/178785805).

And a [passing one](https://travis-ci.org/shakacode/react-webpack-rails-tutorial/builds/178788316) if I add a `sleep 1` before checking if the value shown from the animation is there.

Apparently, the `sleep` will allow the animation to complete.

Here's the offending code.

```js
        <ReactCSSTransitionGroup
          transitionName={cssTransitionGroupClassNames}
          transitionEnterTimeout={300}
          transitionLeaveTimeout={300}
        >
          {this.errorWarning()}
        </ReactCSSTransitionGroup>
```

I'm not sure if this is a phantomjs issue, poltergeist issue, or a capybara issue.

I'm using phantomjs 2.1.1 and the latest libraries.

Here is the PR:

https://github.com/shakacode/react-webpack-rails-tutorial/pull/344

**Comment by twalpole** [comment]
If you enable debug mode for poltergeist - https://github.com/teampoltergeist/poltergeist#customization - and also pass ['--debug=true'] as :phantomjs_options a lot more specific info will be logged, but with the current logs it looks like this is a bug in PhantomJS causing it to crash which Poltergeist can't really do anything about.

**Comment by justin808** [comment]
Related to: https://github.com/teampoltergeist/poltergeist/issues/232

**Comment by justin808** [comment]
@twalpole I can reproduce the issue reliably locally with a given seed for rspec. If I run the single failing test, there is no crash.

Is there some way to recreate a "clean" environment to simulate as if the test ran by itself.

**Comment by justin808** [comment]
I'd file the bug report, but this looks onerous on Mac OS Sierra.

**Comment by twalpole** [comment]
@justin808 Assuming you're already calling Capybara.reset_sessions (which ends up calling `page.driver.reset`) between tests, I think the only other thing would be to call `page.driver.clear_memory_cache` as well and see if that makes a difference.  Other than that, run it with the debug mode settings and post the relevant sections of the logs.  That may give a clue, but it does really sound like a PhantomJS race condition which we can't really do anything about.

**Comment by justin808** [comment]
If this helps, turning `js_errors: false` seems to have stopped the crashes.

**Comment by justin808** [comment]
https://github.com/shakacode/react-webpack-rails-tutorial/pull/344

**Comment by twalpole** [comment]
Hmm, that would seem to imply a specific JS error is causing the crash. Would be interesting to know what that error is if it's possible to figure out

**Comment by twalpole** [comment]
FYI - playing with your repo a bit I've narrowed it down to something happening in an 'input' event handler thats causing PhatnomJS to crash - haven't been able to get more specific than though.

**Comment by justin808** [comment]
@twalpole Hi Thomas, I eventually resorted to using selenium on Travis and CodeShip.

Please let me know if you have any suggestions for this article:
https://blog.shakacode.com/yak-shaving-failing-integration-tests-with-react-a93444886c8c#.wwrs1tstr

Thanks again for your help! I would capture the dump if it were easier!

BTW, I bet LOTS of people are having this issue with phantomjs!

**Comment by twalpole** [comment]
@justin808 yep, the spread of react, ember, etc with PhantomJS have stability issues.  The release of PhantomJS 2.5 with ES2015 support can't come soon enough - or Chromes headless mode. I had left one comment on your article wrt capybara and selenium 3.x - it is supported, it's just that with Firefox there are issues due to geckodriver & marionette being feature incomplete - works fine with chromedriver/chrome

**Comment by justin808** [comment]
@twalpole do you recommend that I update https://github.com/shakacode/react-webpack-rails-tutorial with Selenium 3.x?

Thanks again!

**Comment by twalpole** [comment]
@justin808 If you need to support firefox, you're kind of stuck for now -- if you're willing to not support  firefox until it becomes feature complete, then yes.

**Comment by justin808** [comment]
@twalpole Any advantage to updating sooner? Would you expect better handling of react code with animations around opacity?

**Comment by shepmaster** [comment]
As a note to future searchers, it appears that PhantomJS has troubles with certain types of sourcemaps (ariya/phantomjs#14335). Disabling these when running CI has seen a marked reduction in the number of PhantomJS crashes.

```js
const enableSourcemaps = (process.env.ENABLE_SOURCEMAPS || 'true') === 'true';

// ...

if (enableSourcemaps) {
  module.exports.devtool = 'eval-source-map';
}
```
