### ISSUE TITLE
parseInt on page execute script, can't call method on undefined

### ISSUE THREAD

**Issue by Lackoftactics** [teampoltergeist/poltergeist#831]
We are using poltergeist (1.11.0) and phantomjs (2.1).

We noticed weird behaviour in tests after some debugging, we found that:

it's problem with `parseInt` function

in chrome browser it works: `parseInt(undefined)` returns `NaN`
in poltergeist `page.evaluate_script('parseInt(undefined)')`  it's also `NaN`
but on `page.execute_script('parseInt(undefined)')` it throws:

```
   One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

       TypeError: Can't call method on  undefined
       TypeError: Can't call method on  undefined
           at undefined:3 in exports
           at :23 in trim
           at :5 in trim
           at :0 in call
           at :0 in call
           at :1958 in parseInt
           at :2
           at :3
           at :3
```

Weirdly `+undefined` works fine

I am really curious where this weird behaviour comes from.

**Comment by twalpole** [comment]
Do you really mean `page.execute_script('parseInt(undefined')` or do you mean `page.execute_script('parseInt(undefined)')`   ??

**Comment by Lackoftactics** [comment]
sorry for that, yep the second one. Will edit my code

**Comment by twalpole** [comment]
I can't replicate this https://gist.github.com/twalpole/4775247a2ed6389a58a39e67f47dee84  - both return nil, are you overriding the native parseInt or something?   Without a way to reproduce there is nothing we can do.

**Comment by Lackoftactics** [comment]
@twalpole your code also works for me, but still code during my tests fails, it could be part of my setup during rspec.

**Comment by twalpole** [comment]
It's more likely to. Be some JS in your app overriding some native JS methods for some reason. Try the master branch of Polyergeist, it doesn't depend on some of the native JS in the browser context that the current release does
