### ISSUE TITLE
`send_key` can cause Capybara::Poltergeist::MouseEventFailed

### ISSUE THREAD

**Issue by ragesoss** [teampoltergeist/poltergeist#833]
I'm working on a test that involves hitting the 'Enter' key after setting an input field.

It looks like this:

```ruby
        within('.language-select') do
          find('input').set('fr')
          find('input').native.send_key(:Enter)
        end
```

This fails with

```
Failure/Error: find('input').native.send_key(:Enter)

Capybara::Poltergeist::MouseEventFailed
```

I don't care about overlapping elements, but I cannot find a way to use `trigger` for this keyboard event (instead of just a click).

It's also confusing that this error message describes it as a click rather than a key press.

**Comment by twalpole** [comment]
To send keys to an element the element needs to have focus, for that to happen we click the element - https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/client/browser.coffee#L346 .  This is behaving as expected/designed since Poltergeist is not intended to support interacting with elements a user couldn't interact with.

**Comment by ragesoss** [comment]
Is there a way to combine send_key with the 'trigger' workaround for clicks? The user is able to interact with it in real usage.

**Comment by twalpole** [comment]
You can try triggering click on the element before sending the key - it may set the selection to it, not sure.  The real solution is to figure out why if a user is able to interact in real usage that Poltergeist thinks it can't.  Take a screenshot and see if anything is overlapping, or try making the default screen size larger in your driver registration.  If you fix that then you don't have to try working around issues.

**Comment by ragesoss** [comment]
Thanks much for the suggestions. I'm working with https://github.com/JedWatson/react-select which renders a select dropdown in conjunction with an input field, and it doesn't seem to play nicely.

I wasn't able to find a nice way around it, but with enough trial and error I did make it work without relying on `send_key`. I think if there was a way to send_keys to whatever has focus, it might make it easier to test things that do complex but user-friendly UX things like that.

**Comment by ragesoss** [comment]
(And by the way, thanks for all the great work on Poltergeist!)

**Comment by twalpole** [comment]
@ragesoss taking a quick look at the library you're using, the input is not actually visible for that control and a user cannot interact directly with the input.  Instead you should be doing what a user has to do, which is interact with the elements that JS driven widget adds to the page.  Below is some code that shows interacting with the control on the demo page

    require 'capybara'
    require "capybara/poltergeist"

    sess = Capybara::Session.new(:poltergeist, nil)
    sess.visit("http://jedwatson.github.io/react-select/")
    #Confirm it's there with original value
    sess.assert_selector('input[name="selected-state"][value="new-south-wales"]', visible: false)
    #send keys to the interactable element
    sess.find('div.Select--single div.Select-value').send_keys("Wes", :enter)
    #confirm the hidden inputs value has changed
    sess.assert_selector('input[name="selected-state"][value="western-australia"]', visible: false)

 
If using that type of control a lot, I would probably write a custom Capybara selector to make it easier to deal with.

**Comment by ragesoss** [comment]
Wow, thank you!
