### ISSUE TITLE
drag_by not dragging

### ISSUE THREAD

**Issue by Onychoprion** [teampoltergeist/poltergeist#834]
I'm working on an app where one feature is dragging events — represented by `<div>` panels — onto a fullcalendar area. This is working wonderfully, but testing it has proved to be a challenge. The first two passes below are setup for the problem, and the third contains the failing areas

Sidenote: Not sure if this should go here or on Capybara's page (or on StackOverflow, since it's possible I'm just using it wrong), so apologies if this isn't in the right place

## First Pass
My first solution was simply using Capybara's Node::Element#drag_to, specifying an element as deep within the calendar as I could. This didn't work, and I assumed the reason was because the deepest element was still very much on the edge of the calendar, and thus the calendar wasn't registering it as a proper drop.

## Second Pass
Since I needed a way to drag via specified offsets, I moved to using Capybara::Poltergeist::Node#drag_by. I built my own dragging function in the spec, partly for reusability, but mostly to sequester it all into one place so the spec itself can look not-ugly.

That failed to work. I went into a binding.pry environment and played around with the drag_by function, and nothing I did worked. I used x and y offsets from the current position, absolute x and y positions, and even started randomly throwing numbers in on the hopes that enough dragged darts would eventually hit the dartboard.

### Building a testing environment
I decided to build a special page just to test that drag_by was working at all. Following the example offered [here](http://stackoverflow.com/questions/7278409/html5-drag-and-drop-to-move-a-div-anywhere-on-the-screen) I set up a page exactly like robertc's, with a draggable aside box. Here are the relevant files:

**View page - edit.html.slim**
```
aside draggable="true" id="dragme"
  | This is an aside, drag me.
p
  | Lorem ipsum ....
```
With 4 paragraphs of filler text

**View page - what's actually created**
```
<aside draggable="true" id="dragme">This is an aside, drag me.</aside>
<p>Lorem ipsum....</p>
<!-- And so on for 4 paragraphs -->
```

**Stylesheet - application.scss**
```
aside {
  position:  absolute;
  left: 0;
  top: 0; /* set these so Chrome doesn't return 'auto' from getComputedStyle */
  width: 200px;
  background: rgba(255,255,255,0.66);
  border: 2px  solid rgba(0,0,0,0.5);
  border-radius: 4px; padding: 8px;
}
```

**Javascript - scheduling.js**
```
$(document).on('turbolinks:load',function() {
    var dm = document.getElementById('dragme');
    if (dm != null) {
        dm.addEventListener('dragstart', drag_start, false);
        document.body.addEventListener('dragover', drag_over, false);
        document.body.addEventListener('drop', drop, false);
    }
});

function drag_start(event) {
    var style = window.getComputedStyle(event.target, null);
    event.dataTransfer.setData("text/plain",
        (parseInt(style.getPropertyValue("left"),10) - event.clientX) + ',' + (parseInt(style.getPropertyValue("top"),10) - event.clientY));
}
function drag_over(event) {
    event.preventDefault();
    return false;
}
function drop(event) {
    var offset = event.dataTransfer.getData("text/plain").split(',');
    var dm = document.getElementById('dragme');
    dm.style.left = (event.clientX + parseInt(offset[0],10)) + 'px';
    dm.style.top = (event.clientY + parseInt(offset[1],10)) + 'px';
    event.preventDefault();
    return false;
}
```

And finally, my spec function:
**Spec file - scheduling_spec.rb**
```
def drag_to_calendar(element_identifier, x_off = 0, y_off = 0)
    binding.pry # <-- To get into the binding environment
    find(element_identifier).native.drag_by(x_off, y_off)
end

scenario 'drag_to works?', js: true do
  # Navigate to the specified page
  drag_to_calendar("#dragme")
end
```

### Results
The test page itself works just as in robertc's example, being able to drag the aside around anywhere within the paragraphs. However, when in the binding.pry environment and calling
`find("#dragme").native.drag_by(x, y)`
for any x and y, and subsequently taking screenshots, doesn't move the aside anywhere.

Has the poltergeist's drag_by been broken/rendered nonfunctional?

**Comment by twalpole** [comment]
Poltergeist only generates mousedown, mousemove, and mouseup events when dragging - it does not generate any of the drag/drop events.  IIRC it's because of a limitation in the events that can be generated through PhantomJS send_event, but I could be mistaken on that.  PRs are welcome if you can figure it out.

**Comment by Onychoprion** [comment]
That's what I was expecting, and it's also what I'm not seeing. One of those three — mousedown, mousemove, and/or mouseup — isn't happening. If all three were firing correctly, messing around with the drag_by in the test page (see "Third Pass") would move the aside box around. It's not.

Unless it's not supposed to drag things? In which case why have drag_by if it doesn't drag?

**Comment by twalpole** [comment]
Your "Third Pass" example depends on the dragstart, drag, and drop events - not mousedown, mousemove, mouseup

**Comment by Onychoprion** [comment]
Ah, apologies for the misunderstanding. Thank you; I'll look into fixing it.
