### ISSUE TITLE
Is it possible to check for mixed content when using https?

### ISSUE THREAD

**Issue by onnimonni** [teampoltergeist/poltergeist#839]
Hey!

I would want to use this driver to check for mixed content errors.

I already did similiar check for resources which are 404:
```ruby
# 404 check
RSpec::Matchers::define :have_missing_assets do
  match do |page|
    page.driver.network_traffic.each do |request|
        request.response_parts.uniq(&:url).each do |response|
            # Check if any of the urls has mixed content
             return true if response.status == 404
        end
    end
    return false
  end

  failure_message_when_negated do |page|
    errors = []
    page.driver.network_traffic.each do |request|
        request.response_parts.uniq(&:url).each do |response|
            # Check if any of the urls has mixed content
             errors.push(response.url) if response.status == 404
        end
    end
    "Expected not to have any 404 requests but these were missing: \n\n#{errors.map{|w| "- #{w}"}.join("\n")}\n"
  end
end
```

Phantomjs is so clever that it won't even load `http://` resources from `https://` protected pages so inspecting the `page.driver.network_traffic` won't help me here.

**Comment by twalpole** [comment]
While PhantomJS (2.1.1 is what I tested) does output a warning to the console about the page running insecure content, the http URL does still appear in the request url of  `page.driver.network_traffic' for me.

    page.driver.network_traffic.each do |request|
      puts "insecure content" if request.url.match?(/http:\/\//)
    end
