### ISSUE TITLE
Phantom crash

### ISSUE THREAD

**Issue by ArnisL** [teampoltergeist/poltergeist#841]
There's a peculiar phantom crash happening in [react_on_rails tutorial app](https://github.com/shakacode/react-webpack-rails-tutorial) test suite

Crash occurs at [spec/features/shared/contexts.rb:51](https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/spec/features/shared/contexts.rb#L51)

When test execution briefly stopped with byebug before line:51 - test passes

[Strace](http://pastebin.com/raw/Ybuuz7iB) (got full 30k+ lines log too)

What seems to be telling:

```
open("/home/lapsa/.rvm/gems/ruby-2.3.1/gems/websocket-driver-0.6.4/lib/websocket/driver/hybi.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = 16
(..)
read(16, "module WebSocket\n  class Driver\n"..., 8192) = 8192
read(16, "ror, \"Unrecognized frame opcode:"..., 8192) = 3890
```

Found on [stackoverflow](http://stackoverflow.com/questions/12583338/unrecognized-frame-opcode-5-and-web-socket-closes) something seemingly related about frame opcodes and web sockets

My uneducated guess is that either:
- something (what?) is using outdated WebSocket protocol
- or there is some kind of race condition problem in [Capybara::Poltergeist::WebSocketServer](https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/web_socket_server.rb)
  
Any ideas what's going on?

**Comment by twalpole** [comment]
The most likely cause of this is PhantomJS which we have no control over.  What version are you using?  Could you try running it with the PhantomJS 2.5 beta - https://groups.google.com/forum/#!topic/phantomjs/AefOuwkgBh0 -, and master branch of Poltergeist?

**Comment by ArnisL** [comment]
Used PhantomJS 2.1.1

Having some troubles testing beta version at the moment.
Unsure how to get that up and running on Arch Linux.

**Comment by twalpole** [comment]
Any update on this? Were you able to try PhantomJS 2.5 ?

**Comment by ArnisL** [comment]
Sorry... Real life happened and completely forgot about this.

Will give it another shot this weekend.
