### ISSUE TITLE
Getting Content-Length Response Headers in gzipped Network Traffic

### ISSUE THREAD

**Issue by tomgallagher** [teampoltergeist/poltergeist#849]
Hi

When content is gzipped, Phantom or one of its constituent parts deletes the content-length header.

See this issue https://github.com/ariya/phantomjs/issues/10156

Not sure why it would do this but can anyone suggest a workaround with Capyabara/Poltergeist DSL?

Thanks

Tom

**Comment by twalpole** [comment]
If PhantomJS isn't providing the info there is no way for Poltergeist to get it.
