### ISSUE TITLE
Getting random Capybara::Poltergeist::ObsoleteNode error

### ISSUE THREAD

**Issue by crazyshot** [teampoltergeist/poltergeist#860]
The line in minitest capybara looks like this:
`page.find('#portfolio_sort').click`
And it randomly crashes with Capybara::Poltergeist::ObsoleteNode.

I couldn't reproduce it on purpose, every time that I stop in debugger before this line and run it, everything is fine. Will be happy to try any way to troubleshoot it.

**Comment by twalpole** [comment]
Please show the test steps surrounding the line giving you issues.

**Comment by twalpole** [comment]
Closing due to lack of response - we can reopen if/when the needed info is provided
