### ISSUE TITLE
page.driver.debug opens chrome file_not_found

### ISSUE THREAD

**Issue by ChrisCPO** [teampoltergeist/poltergeist#863]
expecting:
 { inspector: true } with page.driver.debug to open a chrome window with two links.

actual:
   A chrome window is open was opened but reported file not found
```
Your file was not found

It may have been moved or deleted.
ERR_FILE_NOT_FOUND
```

settings:
```ruby
  Capybara::Poltergeist::Driver.new(
    app,
    inspector: true,
    debug: false,
    phantomjs_logger: StringIO.new,
    timeout: timeout_time.to_i,
    js_errors: false,
    window_size: [1300, 1000],
    phantomjs_options: [
      "--debug=no",
      "--load-images=no",
      "--ignore-ssl-errors=yes",
      "--ssl-protocol=TLSv1",
    ],
  )
```

Once test I was able to open debug and view the ip of the on

**Comment by ChrisCPO** [comment]
sorry my cursor is not responding correctly, 

Once during a test I turned on debug: true and was able to view the testing site via a url/ip in the debug info

**Comment by twalpole** [comment]
Current chromes are no longer compatible with the PhantomJS remote debugging, you'd need to use a legacy version (before the blink engine split) or safari.
