### ISSUE TITLE
Cannot find the PhantomJS.EXE file

### ISSUE THREAD

**Issue by luke-hill** [teampoltergeist/poltergeist#873]
Copied from: https://github.com/yaauie/cliver/issues/19 & https://github.com/yaauie/cliver/issues/22

```
Cliver::Dependency::NotFound: Could not find an executable at given path 'C:/Webdrivers for RubyMine/phantomjs.EXE'.If this path was not specified explicitly, it is probably a bug in [Cliver](https://github.com/yaauie/cliver/issues).
```

I'm aware it's throwing me to Cliver. However I've asked on there a few times and had no joy. The chap there mentioned the `CLIVER_NO_VERIFY` variable, but didn't tell me how / where to set it.

This has been a problem from version 1.9 of the gem to today, Affecting me. I use Windows 7 and the only way around it is the monkeypatch mentioned in the thread. The monkeypatch exerpt is below

```
module Cliver
  class ShellCapture
    def initialize(_command)
      @stderr = ''
      @stdout = '2.1.1'
      @command_found = true
    end
  end
end
```

**Comment by twalpole** [comment]
I guess the first question to answer is whether there is actually an executable binary at 'C:/Webdrivers for RubyMine/phantomjs.EXE'  on your system (shouldn't it be `C:\Webdrivers for RubyMine\phantomjs.EXE`)? Although after that I'm not really sure what you would want Poltergeist to do about this?

As far as CLIVER_NO_VERIFY goes, a quick search of the Cliver code shows - https://github.com/yaauie/cliver/blob/develop/lib/cliver/dependency.rb#L110 - which indicates that CLIVER_NO_VERIFY would need to be set as an environment variable.  However it also shows that it only affects the version detection and so MAY not affect the issue you're having.

**Comment by luke-hill** [comment]
I have the lower case variety, but the code is searching for an uppercase variety. The `.exe` is hidden and maintained by Windows. But I never specify any extension.

I'll try setting that ENV variable in my `.env` file, and see if that works. And get back to you, along with some more playing (And a newer version of the gem - we previously used 1.11)

**Comment by twalpole** [comment]
@luke-hill  Which looks like something going wrong in the webdrivers gem attempting to download some version of phantomjs - again nothing to do with Poltergeist.

**Comment by luke-hill** [comment]
When I've tried removing `webdrivers` phantomJS complains and something in poltergeist wants it back. I'm not quite sure what's going on, I feel as though I don't know exactly where to post this issue, as it seems to dovetail many areas / gems of responsibility.

I get the following stacktrace when I remove webdrivers and rebundle

```
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.14.4/lib/bundler/rubygems_integration.rb:350:in `block (2 levels) in replace_gem': webdrivers is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
	from C:/Ruby22/bin/phantomjs:22:in `<main>'
```

The file in ruby22/bin says

```
#! ruby
#
# This file was generated by RubyGems.
#
# The application 'webdrivers' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

gem 'webdrivers', version
load Gem.bin_path('webdrivers', 'phantomjs', version)
```

**Comment by twalpole** [comment]
I'm sorry, I don't have any more time to try and help you through this, it's pretty basic troubleshooting and not a Poltergeist issue.  

Things to check would be 
1. that you do actually have a file at 'C:/Webdrivers for RubyMine/phantomjs.EXE''
2. that it is actually executable
3. that it is  is actually PhantomJS
4. that whatever user you're running your tests at has permission to execute it

If all of those are true then set a breakpoint in your Cliver gems `Cliver::Detector#detect_version` method (where the error comes from) and step through the ShellCapture initialization and see what is being output and why the error is occurring, then provide that info to the Cliver project.

**Comment by luke-hill** [comment]
Done all of that, but frankly it's taken too long to get this fixed and I've been told by others that phantom doesn't offer the kind of speed increase I believed. So I think I'll shelve it.

The issue was that `command_found = true` was coming through but `std_err` was a huge string and `std_out` was `''`. Whereas it was expecting `std_out` to be `2.1.1` and str_err` to be `''`.

I'll update the cliver repo accordingly with my findings. The offending lines were the `Open3.popen3` bit where it was ascertaining the values of i,o,e

**Comment by twalpole** [comment]
The one piece of info that would have been the most help to someone trying to figure out your issue would have been the "huge string" content of `std_err`, is there a reason you didn't provide that to the cliver maintainers?

**Comment by luke-hill** [comment]
Sorry that was the one mentioned above: (4 days ago)

It begins
```
C:/Ruby22/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
```

**Comment by twalpole** [comment]
@luke-hill But that error is coming from the webdrivers gem and I thought you had removed that?  If that is really the string that is ending up in std_err, then it would imply that 'C:/Webdrivers for RubyMine/phantomjs.EXE'' isn't actually the phantomjs binary but rather a stub installed by webdrivers that attempts to download the latest version, but that can't be because you confirmed that it is the phantomjs binary.
