### ISSUE TITLE
How to ignore console.error and still use js_errors: true

### ISSUE THREAD

**Issue by vemv** [teampoltergeist/poltergeist#877]
Hi!

Let's say a JS library outside of my control likes to `console.error` on warnings. They don't break my app in any way.

In that case, the `js_errors: true` option would cause my build to fail. So I have to set it to `false`, which is quite undesirable.

Is there a way to observe only actual errors, disregarding `console.error` output?

Cheers - Victor

**Comment by twalpole** [comment]
Nope, ask the library to stop outputting non-errors to console.error or check if the library has a production mode that doesn't output non-errors to console.error

**Comment by vemv** [comment]
Alright, mind to clarify why is this not possible? Phantomjs thing or poltergeist implementation detail?

**Comment by twalpole** [comment]
Poltergeist relies on the PhantomJS onError callback which is called when console.error is called - The name `console.error` is pretty self explanatory, not sure why "some" libraries choose to use it for warnings.

**Comment by vemv** [comment]
Thanks so much for the explanation!
