### ISSUE TITLE
PhantomJS maintainer steps down

### ISSUE THREAD

**Issue by olivierlacan** [teampoltergeist/poltergeist#882]
https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE

I don't mean to spell doom as I understand that Poltergeist will still work with existing versions of PhantomJS but that makes me curious if there are any ongoing efforts to target [Headless Chromium](https://www.chromestatus.com/features/5678767817097216) (with this gem or another).

Thanks so much for all your hard work regardless.

**Comment by twalpole** [comment]
It doesn't surprise me.  With the number of people repeatedly posting issues in the PhantomJS repo, that were obviously issues with Webki,t trying to develop/maintain PhantomJS was probably a nightmare.   There has been no work done in Poltergeist with regards to Headless Chrome, however once it is released it should be usable through selenium.

**Comment by bf4** [comment]
@olivierlacan Thanks for the link. fwiw, it links to https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md which looks particularly useful

**Comment by olivierlacan** [comment]
Something even more comprehensive came out yesterday: https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by twalpole** [comment]
FYI - Capybara is being tested with headless chrome currently -- there are a couple of issues at the moment - https://github.com/teamcapybara/capybara/issues/1860

**Comment by twalpole** [comment]
Closing since there's nothing we can do about this
