### ISSUE TITLE
Passing environment variables to PhantomJS

### ISSUE THREAD

**Issue by enricostano** [teampoltergeist/poltergeist#885]
Hi,

I would like to know if there is any option we can pass instantiating the poltergeist driver to set some environment variable for the PhantomJS process. For instance I want to pass the `TZ` environment variable to PhantomJS process but I don't want to use `TZ='Australia' bundle exec rspec spec`.

Thanks!

**Comment by twalpole** [comment]
PhantomJS is launched from https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/client.rb#L70 which doesn't have any support for passing the optional initial `env` parameter - so, No ther is no support for what you're looking for.
