### ISSUE TITLE
Automatic download files via poltergeist

### ISSUE THREAD

**Issue by ramugogurla** [teampoltergeist/poltergeist#893]
We are able to download files using selenium driver and I can specify download directory with Capybara Driver like below but the same is not available with poltergeist.
Could you please help me resolving the issue

Capybara.register_driver :selenium_chrome do|app|
        prefs = {"download" => {"default_directory" => 'C:\Downloads'}}
        @session_1=Capybara::Selenium::Driver.new(app, :browser => :chrome, :prefs => prefs, :detach => :unspecified)
       end
Capybara.default_driver=:selenium_chrome

Capybara.register_driver :poltergeist_debug do |app|
  Capybara::Poltergeist::Driver.new(app, :inspector => true)
end
Capybara.javascript_driver = :poltergeist

**Comment by twalpole** [comment]
It's not supported, and is dependent on PhantomJS adding support (which isn't likely).
