### ISSUE TITLE
Typo in keys method

### ISSUE THREAD

**Issue by Odaeus** [teampoltergeist/poltergeist#901]
I was just browsing the code looking for something else when I noticed "multiply" has been written "mulitply" on this line in browser.rb:
https://github.com/teampoltergeist/poltergeist/blame/master/lib/capybara/poltergeist/browser.rb#L442

**Comment by twalpole** [comment]
Thanks! - fixed via 7cbdf1f6353eca4fb874300754cb384095491ece @twalpole twalpole committed an hour ago
