### ISSUE TITLE
Version of JS supported

### ISSUE THREAD

**Issue by TomasBarry** [teampoltergeist/poltergeist#902]
This issue has been brought up before (Poltergeist not supporting ES6): https://github.com/teampoltergeist/poltergeist/issues/823

However it should be made explicit in the README what version of JS is supported by Poltergeist. We have spent a significant amount of time debugging a silent issue that came down to the version of JS used (meaning we could not use `includes` or `startsWith`).

Thanks.

**Comment by twalpole** [comment]
This is a limitation of the version of PhantomJS being used. If you want to submit a PR making that clear in the README (which no one actually reads) it will be considered
