### ISSUE TITLE
current_url returns empty string on about:blank

### ISSUE THREAD

**Issue by romikoops** [teampoltergeist/poltergeist#927]
## Meta
Poltergeist Version: 1.18.0

## Expected Behavior

'about:blank' string as in version `1.17.0`

## Actual Behavior

empty string

## Steps to reproduce

```ruby
visit 'about:blank'
page.current_url
```

**Comment by romikoops** [comment]
@twalpole I confirm, it works as expected in the branch

**Comment by twalpole** [comment]
Fixed via PR #928  - If you need the fix right now use master branch, otherwise I'll probably release a 1.18.1  later this week.
