### ISSUE TITLE
page.current_path always root

### ISSUE THREAD

**Issue by milgner** [teampoltergeist/poltergeist#930]
After upgrading to Poltergeist from 1.17 to 1.18, `page.current_path` always returns the root path `/`.
Downgrading solved the issue again.

**Comment by twalpole** [comment]
The following gist shows `current_path` working fine - https://gist.github.com/twalpole/5f14160e792ce64f06499376adb95558 - so we'll need a reproducible example to look at this.

**Comment by twalpole** [comment]
Will reopen if a reproducible example is provided
